### ISSUE TITLE
Snapshots to S3: IndexShardSnapshotFailedException

### ISSUE THREAD

**Issue by subbu-sw** [elastic/curator#1032]
we are running elasticsearch version 5.5.0 on 2 data nodes, 1 master and 1 client node, curator 5.1.1 on amazon aws (ubuntu). our repository is in S3. our active shards is around 5200 with primary shards half of that. we take daily snapshots of elasticsearch and push it to S3. However, of late, snapshot process does not succeed and goes into PARTIAL state with below failure status being returned on GET /snapshot query.

```
{
          "index": "merch_category_insight_2017_07_11",
          "index_uuid": "merch_category_insight_2017_07_11",
          "shard_id": 0,
          "reason": "IndexShardSnapshotFailedException[Failed to perform snapshot (index files)]; nested: IOException[Unable to upload object indices/pZR0A6ynSn-5pHXJO9uZIQ/0/__3]; nested: AmazonS3Exception[Your socket connection to the server was not read from or written to within the timeout period. Idle connections will be closed. (Service: Amazon S3; Status Code: 400; Error Code: RequestTimeout; Request ID: 11652F0576F61F53)]; ",
          "node_id": "kdcvElZNS9qsb90nUEnksg",
          "status": "INTERNAL_SERVER_ERROR"
        }
```

Following is the corresponding log from elasticsearch. 

```
[2017-08-14T11:36:35,871][WARN ][o.e.s.SnapshotShardsService] [data-1] [[merch_category_insight_2017_07_01][0]] [sl_es_s3_repo:curator-20170814112236/Pg8Zv8u0QWa6IyAQiFxgLg] failed
to create snapshot
org.elasticsearch.index.snapshots.IndexShardSnapshotFailedException: Failed to perform snapshot (index files)
        at org.elasticsearch.repositories.blobstore.BlobStoreRepository$SnapshotContext.snapshot(BlobStoreRepository.java:1377) ~[elasticsearch-5.5.0.jar:5.5.0]
        at org.elasticsearch.repositories.blobstore.BlobStoreRepository.snapshotShard(BlobStoreRepository.java:972) ~[elasticsearch-5.5.0.jar:5.5.0]
        at org.elasticsearch.snapshots.SnapshotShardsService.snapshot(SnapshotShardsService.java:382) ~[elasticsearch-5.5.0.jar:5.5.0]
        at org.elasticsearch.snapshots.SnapshotShardsService.access$200(SnapshotShardsService.java:88) ~[elasticsearch-5.5.0.jar:5.5.0]
        at org.elasticsearch.snapshots.SnapshotShardsService$1.doRun(SnapshotShardsService.java:335) [elasticsearch-5.5.0.jar:5.5.0]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:638) [elasticsearch-5.5.0.jar:5.5.0]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-5.5.0.jar:5.5.0]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_101]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_101]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
Caused by: java.io.IOException: Unable to upload object indices/OaKO9YwJSzqQ3DEn8E1e5g/0/__3
        at org.elasticsearch.repositories.s3.DefaultS3OutputStream.upload(DefaultS3OutputStream.java:112) ~[?:?]
        at org.elasticsearch.repositories.s3.DefaultS3OutputStream.flush(DefaultS3OutputStream.java:99) ~[?:?]
        at org.elasticsearch.repositories.s3.S3OutputStream.flushBuffer(S3OutputStream.java:69) ~[?:?]
        at org.elasticsearch.repositories.s3.S3OutputStream.close(S3OutputStream.java:87) ~[?:?]
        at org.apache.lucene.util.IOUtils.close(IOUtils.java:89) ~[lucene-core-6.6.0.jar:6.6.0 5c7a7b65d2aa7ce5ec96458315c661a18b320241 - ishan - 2017-05-30 07:29:46]
        at org.apache.lucene.util.IOUtils.close(IOUtils.java:76) ~[lucene-core-6.6.0.jar:6.6.0 5c7a7b65d2aa7ce5ec96458315c661a18b320241 - ishan - 2017-05-30 07:29:46]
        at org.elasticsearch.common.io.Streams.copy(Streams.java:88) ~[elasticsearch-5.5.0.jar:5.5.0]
        at org.elasticsearch.common.io.Streams.copy(Streams.java:60) ~[elasticsearch-5.5.0.jar:5.5.0]
        at org.elasticsearch.repositories.s3.S3BlobContainer.writeBlob(S3BlobContainer.java:100) ~[?:?]
        at org.elasticsearch.repositories.blobstore.BlobStoreRepository$SnapshotContext.snapshotFile(BlobStoreRepository.java:1433) ~[elasticsearch-5.5.0.jar:5.5.0]
        at org.elasticsearch.repositories.blobstore.BlobStoreRepository$SnapshotContext.snapshot(BlobStoreRepository.java:1375) ~[elasticsearch-5.5.0.jar:5.5.0]
```

Below is my curator config.
```
actions:
  1:
    action: snapshot
    description: >-
    options:
      repository: sl_es_s3_repo
      # Leaving name blank will result in the default 'curator-%Y%m%d%H%M%S'
      name:
      # Leaving indices blank will result in restoring all indices in the snapshot
      indices:
      ignore_unavailable: True
      include_global_state: True
      partial: False
      wait_for_completion: True
      skip_repo_fs_check: False
      timeout_override: 12000
      continue_if_exception: False
      disable_action: False
    # Take all indices
    filters:
    # PLACEHOLDER FOR FILTER PATTERN
    - filtertype: closed
      exclude: True
    - filtertype: pattern
      kind: regex
      value: '^.*(merch_category_).*$'
      exclude:      
```

Changing the timeout_override setting in curator config does not make a difference. Can someone point me towards how this can be resolved?

**Comment by untergeek** [comment]
Based on what you've shared, I think I can help:

> I am running elasticsearch version 5.5.0 on 2 data nodes, 1 master and 1 client node, curator 5.1.1 on amazon aws (ubuntu). our repository is in S3. our active shards is around 5200

This is your problem in a nutshell: **You have heap exhaustion.**  

You have 2 data nodes, with 2600 shards per node.   I don't even have to look at any of the other statistics, or configuration.  Even with a 30G heap size, you shouldn't have more than 1000 shards per node.  If you look at the JVM stats, I am convinced you'll find that your heap is well over 70% full, all the time, and it's trying to do full GCs one right after the other.  This is why your requests are timing out.  The data nodes are out of usable memory, and they are fighting to do what you ask, but it's just taking too long.

If you want things to work properly again, your recourses are as follows:

1. Add more nodes to bring the shard count per node well below 1000 (especially if your data node heap size is < 30g)
1. Delete a ton of indices to bring the shard count per node down to well below 1000.
1. Increase the heap (if even possible), though this won't help much if the shard count is still over 1000 per node.

**Comment by subbu-sw** [comment]
Our data nodes are having 16G heap each. On checking the node stats (jvm), i realize that both of them are having >70% full. Let me try closing certain old indices and see if that improves the situation.

**Comment by untergeek** [comment]
As this is not a Curator bug, I'm going to close the issue.  If you have further questions about the issue at hand, I suggest asking them at https://discuss.elastic.co

**Comment by subbu-sw** [comment]
we added a new data node and see that the backup process is running successfully. closing this issue.
