### ISSUE TITLE
es_repo_mgr failed to create elasticsearch with Connection failure error message

### ISSUE THREAD

**Issue by mikemchau** [elastic/curator#1057]
Hi,

ES : 1.7.5
Curator : 3.0.0

I have a cron job on a separate instance to take snapshots of a remote ES every hour and upload them to AWS S3.  Last week, I added another cron job to take snapshots of another ES instance.  And this  somehow broke both cron jobs. 

On the command line, it fails at this following command:

es_repo_mgr --debug --host myhostname create s3 --repository $REPOSITORY_NAME --bucket $BUCKET_NAME --base_path $BASE_PATH

Do you think that I need to restart ES?

Here is the debug log:

<snip>

NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f249f1cb210>: Failed to establish a new connection: [Errno 111] Connection refused
2017-09-13 22:01:10,694 DEBUG              elasticsearch       log_request_fail:90   > None
2017-09-13 22:01:10,694 DEBUG         urllib3.util.retry               from_int:200  Converted retries value: False -> Retry(total=False, connect=None, read=None, redirect=0, status=None)
2017-09-13 22:01:10,694 DEBUG     urllib3.connectionpool              _new_conn:208  Starting new HTTP connection (4): localhost
2017-09-13 22:01:10,694 WARNING            elasticsearch       log_request_fail:82   GET http://localhost:9200/ [status:N/A request:0.000s]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/connection/http_urllib3.py", line 78, in perform_request
    response = self.pool.urlopen(method, url, body, retries=False, headers=self.headers, **kw)
  File "/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python2.7/dist-packages/urllib3/util/retry.py", line 333, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 357, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python2.7/httplib.py", line 979, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1013, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 975, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 835, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 797, in send
    self.connect()
  File "/usr/local/lib/python2.7/dist-packages/urllib3/connection.py", line 166, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python2.7/dist-packages/urllib3/connection.py", line 150, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f249f1cb1d0>: Failed to establish a new connection: [Errno 111] Connection refused
2017-09-13 22:01:10,695 DEBUG              elasticsearch       log_request_fail:90   > None
ERROR: Connection failure.

Thanks

**Comment by untergeek** [comment]
Curator 3.0 is no longer supported.

With that said, there is at least one thing you can try.  

Upgrade to Curator 3.5.1, which is the last release in the 3.x series, and has all of the fixes and patches that might have addressed things.  There were several changes in the versions between that may or may not have addressed this.

However, after all is said and done, I note this:

```
es_repo_mgr --debug --host myhostname ...
```

But in the logs, it says this:

```
2017-09-13 22:01:10,694 WARNING elasticsearch log_request_fail:82 GET http://localhost:9200/ [status:N/A request:0.000s]
```

The urllib3 error that says `Connection refused` is what Curator gets back from attempting to reach the host in question.  If it was unable to make a connection, it is because you have a firewall blocking access, or an incorrect host/port combination, or security credentials or a proxy in the way preventing access.

**Comment by mikemchau** [comment]
Thank you for your quick reply.

1) I also noticed the warning about GET http://localhost:9200/. However, I don't understand why it calls the localhost (and not GET http:// myhostname:9200) when I state specifically the hostname in my es_repo_mgr statement.

Again, I run my cron script from a separate instance. Here is my script:

es_repo_mgr --host myhostname delete --yes --repository $REPOSITORY_NAME
es_repo_mgr --host myhostname create s3 --repository $REPOSITORY_NAME --bucket $BUCKET_NAME --base_path $BASE_PATH
curator  --host myhostname --timeout 21600 snapshot --name $SNAPSHOT_NAME --repository $REPOSITORY_NAME indices --all-indices

On this instance, I am able to run curl -XGET  myhostname:9200/_snapshot?pretty. Of course, GET http://localhost:9200/ fails. The cron job used to work 

2) Will also look into your suggestion of upgrading curator to 3.5.1

3) Another question, do you know what elasticsearch-curator==3? In the other cron script, I see the following:

if ! type "curator" > /dev/null; then
  apt-get -y install python-pip
  pip install elasticsearch-curator
  pip install -U elasticsearch-curator==3
fi

Looking at the timestamp, after setting up this second script, both scripts failed

Thanks

**Comment by mikemchau** [comment]
Never mind about  elasticsearch-curator==3. That is to specify the version of curator.

**Comment by mikemchau** [comment]
Ok, upgrading curator to 3.5.1 seems to fix the problem. I don't see Connection Failure anymore.

pip install -U elasticsearch-curator==3.5.1

Thanks
