### ISSUE TITLE
No meaningful error if the config file does not exist

### ISSUE THREAD

**Issue by robin13** [elastic/curator#1061]
Running curator 5.2.0 with:

```
curator_cli --loglevel DEBUG --config config.yaml delete_indices ...
```

If the config file `config.yaml` does not exist, there is no error logged which says that it could not open the config file, it simply takes defaults (tries to connect to localhost), and fails with another error - in my case that the authentication did not work:

```
Traceback (most recent call last):
  File "/usr/local/bin/curator_cli", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/curator/curator_cli.py", line 5, in main
    cli(obj={})
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/curator/singletons.py", line 256, in delete_indices_singleton
    client = get_client(**c_args)
  File "/usr/local/lib/python2.7/dist-packages/curator/utils.py", line 800, in get_client
    'Error: {0}'.format(e)
elasticsearch.exceptions.ElasticsearchException: Unable to create client connection to Elasticsearch.  Error: TransportError(401, u'security_exception', u'missing authentication token for REST request [/]')
```

As I was just investigating issues with authentication, this lead me down the wrong path for a long time...
Would it be possible to note clearly if the defined configuration file does not exist and cannot be read?

**Comment by untergeek** [comment]
That sounds like a bug.  I'll see what I can do about that.  I thought there was a check in the part reading the YAML file, but I'll have to double-check that.

**Comment by untergeek** [comment]
I can't replicate this.  If the file doesn't exist, it does give an error, as expected: 
```
root@esclient:~# curator --config nonexistent.yml --dry-run rollover.yml
Usage: curator [OPTIONS] ACTION_FILE

Error: Invalid value for "--config": Path "nonexistent.yml" does not exist.
```
However, if it's _empty,_ it uses all the defaults (localhost, port 9200, INFO logging, etc...):
```
root@esclient:~# curator --config empty.yml --dry-run rollover.yml
2018-03-04 16:09:43,467 INFO      Preparing Action ID: 1, "rollover"
<EOF...that's literally all it shows>
```
Is it possible the user had an _empty_ config file, rather than a missing one?  Closing, as that isn't the same bug as the title.

**Comment by tmehlinger** [comment]
Please reopen this issue, it's still a bug. I'm running into it as well and it took me a couple hours to realize it wasn't a problem with my environment or configuration.

Please also note that the original report was about `curator_cli` and not `curator`. This is a very important distinction.

Here's a test case in a Docker container:

```
root@2ca141b154bd:/app# .venv/bin/curator_cli --config this-file-does-not-exist.yaml delete-indices --filter_list '{"filtertype":"none"}'
2021-07-01 22:46:21,233 INFO      Instantiating client object
2021-07-01 22:46:21,233 INFO      Testing client connectivity
2021-07-01 22:46:21,237 ERROR     HTTP N/A error: HTTPConnectionPool(host='127.0.0.1', port=9200): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f32b0cd8610>: Failed to establish a new connection: [Errno 111] Connection refused'))
2021-07-01 22:46:21,237 CRITICAL  Curator cannot proceed. Exiting.
Traceback (most recent call last):
  File "/app/.venv/bin/curator_cli", line 8, in <module>
    sys.exit(main())
  File "/app/.venv/lib/python3.9/site-packages/curator/curator_cli.py", line 10, in main
    cli(obj={})
  File "/app/.venv/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/app/.venv/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/app/.venv/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/app/.venv/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/app/.venv/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/app/.venv/lib/python3.9/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/app/.venv/lib/python3.9/site-packages/curator/cli_singletons/delete.py", line 31, in delete_indices
    action = cli_action(
  File "/app/.venv/lib/python3.9/site-packages/curator/cli_singletons/object_class.py", line 90, in __init__
    self.client = get_client(**client_args)
  File "/app/.venv/lib/python3.9/site-packages/curator/utils.py", line 1049, in get_client
    raise exceptions.ClientException
curator.exceptions.ClientException
```

As you can see, there is no output indicating `curator_cli` failed to load the configuration. It seems as if `curator_cli` doesn't even _attempt_ to load a configuration file.

Contrast with `curator`.

```
root@4146f20a2c92:/app# .venv/bin/curator --config does-not-exist.yaml
Usage: curator [OPTIONS] ACTION_FILE
Try 'curator --help' for help.

Error: Invalid value for '--config': Path 'does-not-exist.yaml' does not exist.
```
