### ISSUE TITLE
Wrong version number in incompatibility exception

### ISSUE THREAD

**Issue by IngaFeick** [elastic/curator#1089]
Tried to run an older version of curator (4.2.5) against a 5.6.3 cluster and the error message was not helpful:

> user@server:$ bin/curator  --config curator/config.yaml  curator/actions.yaml
Traceback (most recent call last):
  File "/home/unpriv/.pyenv/versions/2.7.9/bin/curator", line 9, in <module>
    load_entry_point('elasticsearch-curator==4.2.5', 'console_scripts', 'curator')()
  File "/home/unpriv/.pyenv/versions/2.7.9/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/unpriv/.pyenv/versions/2.7.9/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/unpriv/.pyenv/versions/2.7.9/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/unpriv/.pyenv/versions/2.7.9/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/unpriv/.pyenv/versions/2.7.9/lib/python2.7/site-packages/curator/cli.py", line 166, in cli
    client = get_client(**client_args)
  File "/home/unpriv/.pyenv/versions/2.7.9/lib/python2.7/site-packages/curator/utils.py", line 603, in get_client
    'Error: {0}'.format(e)
elasticsearch.exceptions.ElasticsearchException: Unable to create client connection to Elasticsearch.  Error: Elasticsearch version 5.6.3 incompatible with this version of Curator (5.6.3)

Expected behaviour: the error message should be: 
     _Elasticsearch version 5.6.3 incompatible with this version of Curator (4.2.5)_
because 
> user@server:$ bin/curator --version
curator, version 4.2.5

**Comment by IngaFeick** [comment]
Probably this line: https://github.com/elastic/curator/blob/master/curator/utils.py#L698

**Comment by untergeek** [comment]
This is already the fixed version. Compare to https://github.com/elastic/curator/blob/v4.2.5/curator/utils.py#L442

**Comment by IngaFeick** [comment]
Thank you! @untergeek
