### ISSUE TITLE
curator not working on CentOS 7

### ISSUE THREAD

**Issue by queszama** [elastic/curator#1127]
### Specifications
  - Version: elasticsearch-curator-5.4.1-1.x86_64 
  - Platform: RHEL 7.2 , python-2.7.5
  
Problem Statement: 
                              curator command fails with the following error

$/usr/bin/curator
Traceback (most recent call last):
  File "/home/buh/.local/lib/python3.6/site-packages/cx_Freeze/initscripts/__startup__.py", line 14, in run
  File "/home/buh/.local/lib/python3.6/site-packages/cx_Freeze/initscripts/Console.py", line 26, in run
  File "run_curator.py", line 23, in <module>
  File "/home/buh/curator/curator/__init__.py", line 6, in <module>
  File "/home/buh/curator/curator/utils.py", line 2, in <module>
  File "/home/buh/.local/lib/python3.6/site-packages/elasticsearch/__init__.py", line 17, in <module>
  File "/home/buh/.local/lib/python3.6/site-packages/elasticsearch/client/__init__.py", line 4, in <module>
  File "/home/buh/.local/lib/python3.6/site-packages/elasticsearch/transport.py", line 4, in <module>
  File "/home/buh/.local/lib/python3.6/site-packages/elasticsearch/connection/__init__.py", line 3, in <module>
  File "/home/buh/.local/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py", line 2, in <module>
  File "/usr/local/lib/python3.6/ssl.py", line 101, in <module>
ImportError: /lib64/libcrypto.so.10: version `OPENSSL_1.0.2' not found (required by /opt/elasticsearch-curator/lib/_ssl.cpython-36m-x86_64-linux-gnu.so)

$ls -l /lib64/libcrypto.so.10
lrwxrwxrwx 1 root root 19 May 12  2017 /lib64/libcrypto.so.10 -> libcrypto.so.1.0.1e

Followed the following documentation to install curator for YUM based on RHEL 7.  
https://www.elastic.co/guide/en/elasticsearch/client/curator/current/yum-repository.html

**Comment by queszama** [comment]
I installed curator which is for RHEL 6 and this seems is working

$sudo rpm -ivh https://packages.elastic.co/curator/5/centos/6/Packages/elasticsearch-curator-5.4.1-1.x86_64.rpm
Retrieving https://packages.elastic.co/curator/5/centos/6/Packages/elasticsearch-curator-5.4.1-1.x86_64.rpm
Preparing...                          ################################# [100%]
Updating / installing...
   1:elasticsearch-curator-5.4.1-1    ################################# [100%]
$/usr/bin/curator
Usage: curator [OPTIONS] ACTION_FILE
Error: Missing argument "action_file".
