### ISSUE TITLE
Snapshots Failing: TransportError(404, 'snapshot_missing_exception', ...)

### ISSUE THREAD

**Issue by yangas** [elastic/curator#1161]
### Expected Behavior
When taking snapshots for a large set of indices (individual actions per index) snapshots shouldn't be marked as missing once the action has already been started.

### Actual Behavior
When taking snapshots for a large number of unique indices some will fail throwing snapshot missing exception after some execution time (at which point a snapshot should already exist).

**Curator Output:**
```
2018-03-05 03:59:30,836 INFO      Trying Action ID: SNAPSHOT_DAILY_<redacted>, "snapshot": daily index: <redacted>
2018-03-05 03:59:39,046 INFO      Creating snapshot "snapshot-20180305035936_<redacted>" from indices: ['<redacted>_index_2018.03.04']
2018-03-05 03:59:39,946 INFO      Snapshot snapshot-20180305035936_<redacted> still in progress.
2018-03-05 03:59:49,079 INFO      Snapshot snapshot-20180305035936_<redacted> still in progress.
2018-03-05 03:59:58,261 INFO      Snapshot snapshot-20180305035936_<redacted> still in progress.
2018-03-05 04:00:07,400 INFO      Snapshot snapshot-20180305035936_<redacted> still in progress.
2018-03-05 04:00:16,526 INFO      Snapshot snapshot-20180305035936_<redacted> still in progress.
2018-03-05 04:00:25,655 INFO      Snapshot snapshot-20180305035936_<redacted> still in progress.
2018-03-05 04:00:35,101 INFO      Snapshot snapshot-20180305035936_<redacted> still in progress.
2018-03-05 04:00:44,275 INFO      Snapshot snapshot-20180305035936_<redacted> still in progress.
2018-03-05 04:00:53,419 INFO      Snapshot snapshot-20180305035936_<redacted> still in progress.
2018-03-05 04:01:02,605 INFO      Snapshot snapshot-20180305035936_<redacted> still in progress.
2018-03-05 04:01:11,793 INFO      Snapshot snapshot-20180305035936_<redacted> still in progress.
2018-03-05 04:01:20,965 INFO      Snapshot snapshot-20180305035936_<redacted> still in progress.
2018-03-05 04:01:30,253 INFO      Snapshot snapshot-20180305035936_<redacted> still in progress.
2018-03-05 04:01:39,424 INFO      Snapshot snapshot-20180305035936_<redacted> still in progress.
2018-03-05 04:01:48,609 INFO      Snapshot snapshot-20180305035936_<redacted> still in progress.
2018-03-05 04:01:57,851 INFO      Snapshot snapshot-20180305035936_<redacted> still in progress.
2018-03-05 04:02:07,146 INFO      Snapshot snapshot-20180305035936_<redacted> still in progress.
2018-03-05 04:02:16,266 INFO      Snapshot snapshot-20180305035936_<redacted> still in progress.
2018-03-05 04:02:25,395 INFO      Snapshot snapshot-20180305035936_<redacted> still in progress.
2018-03-05 04:02:34,748 INFO      Snapshot snapshot-20180305035936_<redacted> still in progress.
2018-03-05 04:02:43,944 INFO      Snapshot snapshot-20180305035936_<redacted> still in progress.
2018-03-05 04:02:53,903 INFO      Snapshot snapshot-20180305035936_<redacted> still in progress.
2018-03-05 04:03:03,033 INFO      Snapshot snapshot-20180305035936_<redacted> still in progress.
2018-03-05 04:03:12,165 INFO      Snapshot snapshot-20180305035936_<redacted> still in progress.
2018-03-05 04:03:21,289 INFO      Snapshot snapshot-20180305035936_<redacted> still in progress.
2018-03-05 04:03:30,451 INFO      Snapshot snapshot-20180305035936_<redacted> still in progress.
2018-03-05 04:03:39,570 INFO      Snapshot snapshot-20180305035936_<redacted> still in progress.
2018-03-05 04:03:48,676 ERROR     Failed to complete action: snapshot.  <class 'curator.exceptions.FailedExecution'>: Exception encountered.  Rerun with loglevel DEBUG and/or check Elasticsearch logs for more information. Exception: Unable to obtain information for snapshot "snapshot-20180305035936_<redacted>" in repository "repo". Error: TransportError(404, 'snapshot_missing_exception', '[repo:snapshot-20180305035936_<redacted>] is missing')
2018-03-05 04:03:48,676 INFO      Continuing execution with next action because "continue_if_exception" is set to True for action snapshot
2018-03-05 04:03:48,676 INFO      Action ID: SNAPSHOT_DAILY_<redacted>, "snapshot" completed.
```

**ES logs:**
```
[2018-03-05T04:03:44,735][INFO ][o.e.s.SnapshotShardsService] [0AB1Ezt] snapshot [repo:snapshot-20180305035936_<redacted>/2OKxaLkfSIm-Te5TWkamWQ] is done
[2018-03-05T04:03:44,897][WARN ][o.e.s.SnapshotsService   ] [0AB1Ezt] [repo:snapshot-20180305035936_<redacted>/2OKxaLkfSIm-Te5TWkamWQ] failed to finalize snapshot
org.elasticsearch.repositories.RepositoryException: [repo] concurrent modification of the index-N file, expected current generation [1290], actual current generation [1293] - possibly due to simultaneous snapshot deletion requests
        at org.elasticsearch.repositories.blobstore.BlobStoreRepository.writeIndexGen(BlobStoreRepository.java:825) ~[elasticsearch-5.5.3.jar:5.5.3]
        at org.elasticsearch.repositories.blobstore.BlobStoreRepository.finalizeSnapshot(BlobStoreRepository.java:564) ~[elasticsearch-5.5.3.jar:5.5.3]
        at org.elasticsearch.snapshots.SnapshotsService$5.run(SnapshotsService.java:950) [elasticsearch-5.5.3.jar:5.5.3]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:569) [elasticsearch-5.5.3.jar:5.5.3]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_131]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
```

### Steps to Reproduce the Problem
Snapshotting ~20 individual indices (1 per action) using the same structure as the snippet shown below. Index sizes range from 200kb - 1.5tb, however the index that failed above had a size of ~15gb.

**Action File Snippet:**
```
SNAPSHOT_DAILY_<redacted>:
  action: snapshot
  description: "daily index: <redacted>"
  options:
    repository: 'repo'
    name: 'snapshot-%Y%m%d%H%M%S_<redacted>'
    ignore_empty_list: True
    continue_if_exception: True
    disable_action: False
  filters:
  - filtertype: kibana
    exclude: True
  - filtertype: period
    source: name
    range_from: -1
    range_to: -1
    timestring: '%Y.%m.%d'
    unit: days
  - filtertype: pattern
    kind: prefix
    value: <redacted>
```

### Specifications
  - Version: Curator 5.1.1; ES 5.5.3
  - Platform: Python 2.7.5; Rhel7

## Context (Environment)
This issue started showing up once I updated the snapshotting strategy based on structural changes. Went from single cluster single snapshot for all Daily indices (which had high likelihood of causing partial snapshots) to multi-cluster where each cluster had action file with 1 action per daily index (giving more granularity and visibility on snapshots that fail).

**Comment by untergeek** [comment]
Please understand that the error is not from Curator, but from Elasticsearch.  Curator is an index selection wrapper on plain old Elasticsearch API calls.  If you had made the API call directly (e.g. command-line, or the Console in Kibana), the result would have been the exact same.

With that said, the error _may_ (or may not) indicate something else going on:
```
org.elasticsearch.repositories.RepositoryException: [repo] concurrent modification of the index-N file, expected current generation [1290], actual current generation [1293] - possibly due to simultaneous snapshot deletion requests
```
You're trying to snapshot to a file that is being modified _while_ you are snapshotting.  This should not be possible.  What kind of repository is it? Do you have multiple clusters accessing the same repository?  [Curator will not allow a `snapshot_delete` to happen while a snapshot is `IN_PROGRESS`](https://github.com/elastic/curator/blob/v5.4.1/curator/actions.py#L971-L976), as it tests to see if something is going on, but that state is only within a single cluster (if you had multiples accessing the same repository).

I can't say for sure what's happening in your cluster, but I can say with much certainty that it isn't likely to be Curator that is causing the problem.

**Comment by untergeek** [comment]
And that's what I get for not reading deeper:
> Went from single cluster single snapshot for all Daily indices (which had high likelihood of causing partial snapshots) to multi-cluster where each cluster had action file with 1 action per daily index (giving more granularity and visibility on snapshots that fail).

It seems my guess was not far from the mark.

If you're doing a multi-cluster snapshot to the same shared filesystem, at least be wise and have the filesystem paths for each cluster be different. Create different repositories, each using their own filesystem path.  It seems certain you ended up with these collisions because of this approach.

**Comment by untergeek** [comment]
As this is not a Curator bug, and a workable solution to your problem presented, I am closing this.

**Comment by yangas** [comment]
@untergeek Thanks a bunch, hadn't realized the overlap and yes it was indeed both clusters writing to the same base_path within an s3 repo. Thanks for the quick resolution and guidance 👍
