### ISSUE TITLE
Curator looking for but cannot find libssl 1.0.0 on Debian stretch

### ISSUE THREAD

**Issue by eirc** [elastic/curator#1241]
### Expected Behavior
Curator should run

### Actual Behavior
<pre>
# curator --version
Traceback (most recent call last):
  File "/home/buh/.local/lib/python3.6/site-packages/cx_Freeze/initscripts/__startup__.py", line 14, in run
  File "/home/buh/.local/lib/python3.6/site-packages/cx_Freeze/initscripts/Console.py", line 26, in run
  File "run_curator.py", line 23, in <module>
  File "/home/buh/curator/curator/__init__.py", line 6, in <module>
  File "/home/buh/curator/curator/utils.py", line 1, in <module>
  File "/home/buh/.local/lib/python3.6/site-packages/elasticsearch/__init__.py", line 17, in <module>
  File "/home/buh/.local/lib/python3.6/site-packages/elasticsearch/client/__init__.py", line 4, in <module>
  File "/home/buh/.local/lib/python3.6/site-packages/elasticsearch/transport.py", line 4, in <module>
  File "/home/buh/.local/lib/python3.6/site-packages/elasticsearch/connection/__init__.py", line 3, in <module>
  File "/home/buh/.local/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py", line 2, in <module>
  File "/usr/local/lib/python3.6/ssl.py", line 101, in <module>
ImportError: libssl.so.1.0.0: cannot open shared object file: No such file or directory
</pre>

### Steps to Reproduce the Problem
  1. Use debian stretch
  2. Run curator

### Specifications

  - Version: 5.5.4
  - Platform: Debian Stretch

## Context (Environment)

LibSSL 1.0.2 and 1.1 are installed:

<pre>
# dpkg -l | grep libssl
ii  libssl-dev:amd64                 1.1.0f-3+deb9u2                amd64        Secure Sockets Layer toolkit - development files
ii  libssl-doc                       1.1.0f-3+deb9u2                all          Secure Sockets Layer toolkit - development documentation
ii  libssl1.0.2:amd64                1.0.2l-2+deb9u3                amd64        Secure Sockets Layer toolkit - shared libraries
ii  libssl1.1:amd64                  1.1.0f-3+deb9u2                amd64        Secure Sockets Layer toolkit - shared libraries
</pre>

<pre>
# ls -la /usr/lib/x86_64-linux-gnu/libssl*
-rw-r--r-- 1 root root 357024 Οκτ   7  2017 /usr/lib/x86_64-linux-gnu/libssl3.so
-rw-r--r-- 1 root root 738444 Μάρ  29 13:51 /usr/lib/x86_64-linux-gnu/libssl.a
lrwxrwxrwx 1 root root     13 Μάρ  29 13:51 /usr/lib/x86_64-linux-gnu/libssl.so -> libssl.so.1.1
-rw-r--r-- 1 root root 431232 Μάρ  29 14:10 /usr/lib/x86_64-linux-gnu/libssl.so.1.0.2
-rw-r--r-- 1 root root 442920 Μάρ  29 13:51 /usr/lib/x86_64-linux-gnu/libssl.so.1.1
</pre>

Tried linking libssl1.0.0 and libcrypt1.0.0 to the installed 1.0.2 so files but it again won't work:

<pre>
# curator --version
Traceback (most recent call last):
  File "/home/buh/.local/lib/python3.6/site-packages/cx_Freeze/initscripts/__startup__.py", line 14, in run
  File "/home/buh/.local/lib/python3.6/site-packages/cx_Freeze/initscripts/Console.py", line 26, in run
  File "run_curator.py", line 23, in <module>
  File "/home/buh/curator/curator/__init__.py", line 6, in <module>
  File "/home/buh/curator/curator/utils.py", line 1, in <module>
  File "/home/buh/.local/lib/python3.6/site-packages/elasticsearch/__init__.py", line 17, in <module>
  File "/home/buh/.local/lib/python3.6/site-packages/elasticsearch/client/__init__.py", line 4, in <module>
  File "/home/buh/.local/lib/python3.6/site-packages/elasticsearch/transport.py", line 4, in <module>
  File "/home/buh/.local/lib/python3.6/site-packages/elasticsearch/connection/__init__.py", line 3, in <module>
  File "/home/buh/.local/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py", line 2, in <module>
  File "/usr/local/lib/python3.6/ssl.py", line 101, in <module>
ImportError: /usr/lib/x86_64-linux-gnu/libcrypto.so.1.0.0: version `OPENSSL_1.0.0' not found (required by /opt/elasticsearch-curator/lib/_ssl.cpython-36m-x86_64-linux-gnu.so)                                                                
</pre>

A workaround would be awesome to have backups at least work until a proper fix is issued :)

**Comment by untergeek** [comment]
You must have installed the Debian Jessie package.  There is a Debian-stretch package:

    deb [arch=amd64] https://packages.elastic.co/curator/5/debian9 stable main


Please see https://www.elastic.co/guide/en/elasticsearch/client/curator/current/apt-repository.html#_repository_configuration for more information.

**Comment by eirc** [comment]
You are right, I'm sorry for that. Thanks a lot!!

**Comment by heroInCommunity** [comment]
Had the same problem, but firstly found working solution https://unix.stackexchange.com/a/419737/85467,
only after found this issue and official solution.
