### ISSUE TITLE
Error during reindex

### ISSUE THREAD

**Issue by benkeil** [elastic/curator#1242]
## To submit a bug or report an issue
Reindex fails with `09:21:35 - curator.actions.reindex - ERROR - The index described as "INDEX" was not found after the reindex operation. Check Elasticsearch logs for more information.`

### Expected Behavior
It should work

### Actual Behavior
It doesn't work :D

### Steps to Reproduce the Problem
It happens only sometimes randomly for some index during the whole process. On some days it will run without failures... I don't know how to reproduce. After the job fails, it will restart and get the same error for this indices.

### Specifications

- Version: 6.3.0
- Platform: CentOS 7.5

### Nodes

    $ curls elk03.mycompany.com:9200/_cat/nodes?v
    ip         heap.percent ram.percent cpu load_1m load_5m load_15m node.role master name
    10.2.90.22           49          98  38    8.39    9.98    10.45 mdi       -      elk02.mycompany.com
    10.2.90.21           33          99  36   15.53   14.98    13.59 mdi       -      elk01.mycompany.com
    10.2.90.23           43          36   0    0.00    0.01     0.05 mi        *      elk03.mycompany.com
    10.2.90.24           31          98  66   22.13   20.90    20.00 mdi       -      elk04.mycompany.com

### Script Log
    09:21:26 - curator.actions.reindex - DEBUG - Reindexing indices: ['integration.sandbox-mls.mls-customer-apikey-service-v1.logs-6.2.1-2018.07.02', 'integration.sandbox-mls.mls-customer-apikey-service-v1.logs-6.2.1-2018.07.03', 'integration.sandbox-mls.mls-customer-apikey-service-v1.logs-6.2.1-2018.07.04', 'integration.sandbox-mls.mls-customer-apikey-service-v1.logs-6.2.1-2018.07.01', 'integration.sandbox-mls.mls-customer-apikey-service-v1.logs-6.2.1-2018.07.06', 'integration.sandbox-mls.mls-customer-apikey-service-v1.logs-6.2.1-2018.07.07', 'integration.sandbox-mls.mls-customer-apikey-service-v1.logs-6.2.1-2018.07.05']
    09:21:26 - curator.actions.reindex - DEBUG - source_list: ['integration.sandbox-mls.mls-customer-apikey-service-v1.logs-6.2.1-2018.07.02', 'integration.sandbox-mls.mls-customer-apikey-service-v1.logs-6.2.1-2018.07.03', 'integration.sandbox-mls.mls-customer-apikey-service-v1.logs-6.2.1-2018.07.04', 'integration.sandbox-mls.mls-customer-apikey-service-v1.logs-6.2.1-2018.07.01', 'integration.sandbox-mls.mls-customer-apikey-service-v1.logs-6.2.1-2018.07.06', 'integration.sandbox-mls.mls-customer-apikey-service-v1.logs-6.2.1-2018.07.07', 'integration.sandbox-mls.mls-customer-apikey-service-v1.logs-6.2.1-2018.07.05']
    09:21:26 - curator.actions.reindex - INFO - Commencing reindex operation
    09:21:26 - curator.actions.reindex - DEBUG - REINDEX: request body: {'source': {'index': ['integration.sandbox-mls.mls-customer-apikey-service-v1.logs-6.2.1-2018.07.02', 'integration.sandbox-mls.mls-customer-apikey-service-v1.logs-6.2.1-2018.07.03', 'integration.sandbox-mls.mls-customer-apikey-service-v1.logs-6.2.1-2018.07.04', 'integration.sandbox-mls.mls-customer-apikey-service-v1.logs-6.2.1-2018.07.01', 'integration.sandbox-mls.mls-customer-apikey-service-v1.logs-6.2.1-2018.07.06', 'integration.sandbox-mls.mls-customer-apikey-service-v1.logs-6.2.1-2018.07.07', 'integration.sandbox-mls.mls-customer-apikey-service-v1.logs-6.2.1-2018.07.05'], 'query': {'bool': {'filter': {'bool': {'must_not': [{'regexp': {'url_path': '/health.*'}}, {'regexp': {'url_path': '/metrics.*'}}, {'match': {'class': 'com.sedo.service.spring.controller.StatusController'}}]}}}}}, 'dest': {'index': 'integration.sandbox-mls.mls-customer-apikey-service-v1.logs-6.2.1-2018.07'}} with arguments: refresh=True requests_per_second=-1 slices=32 timeout=60s wait_for_active_shards=1 wait_for_completion=True
    09:21:26 - curator.actions.reindex - DEBUG - TASK ID = wa6mTh10SUiCLgUr_OnbAQ:980315623
    09:21:26 - curator.utils - INFO - Task "reindex from [integration.sandbox-mls.mls-customer-apikey-service-v1.logs-6.2.1-2018.07.02, integration.sandbox-mls.mls-customer-apikey-service-v1.logs-6.2.1-2018.07.03, integration.sandbox-mls.mls-customer-apikey-service-v1.logs-6.2.1-2018.07.04, integration.sandbox-mls.mls-customer-apikey-service-v1.logs-6.2.1-2018.07.01, integration.sandbox-mls.mls-customer-apikey-service-v1.logs-6.2.1-2018.07.06, integration.sandbox-mls.mls-customer-apikey-service-v1.logs-6.2.1-2018.07.07, integration.sandbox-mls.mls-customer-apikey-service-v1.logs-6.2.1-2018.07.05] to [integration.sandbox-mls.mls-customer-apikey-service-v1.logs-6.2.1-2018.07]" with task_id "wa6mTh10SUiCLgUr_OnbAQ:980315623" has been running for 0.132693231 seconds
    09:21:35 - curator.utils - INFO - Task "reindex from [integration.sandbox-mls.mls-customer-apikey-service-v1.logs-6.2.1-2018.07.02, integration.sandbox-mls.mls-customer-apikey-service-v1.logs-6.2.1-2018.07.03, integration.sandbox-mls.mls-customer-apikey-service-v1.logs-6.2.1-2018.07.04, integration.sandbox-mls.mls-customer-apikey-service-v1.logs-6.2.1-2018.07.01, integration.sandbox-mls.mls-customer-apikey-service-v1.logs-6.2.1-2018.07.06, integration.sandbox-mls.mls-customer-apikey-service-v1.logs-6.2.1-2018.07.07, integration.sandbox-mls.mls-customer-apikey-service-v1.logs-6.2.1-2018.07.05] to [integration.sandbox-mls.mls-customer-apikey-service-v1.logs-6.2.1-2018.07]" completed at 2018-07-09T09:21:27Z.
    09:21:35 - curator.actions.reindex - ERROR - The index described as "integration.sandbox-mls.mls-customer-apikey-service-v1.logs-6.2.1-2018.07" was not found after the reindex operation. Check Elasticsearch logs for more information.
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/site-packages/curator/actions.py", line 1378, in do_action
        self._post_run_quick_check(dest)
      File "/usr/local/lib/python3.6/site-packages/curator/actions.py", line 1303, in _post_run_quick_check
        'not found.'.format(index_name)
    curator.exceptions.FailedExecution: Reindex failed. The index or alias identified by "integration.sandbox-mls.mls-customer-apikey-service-v1.logs-6.2.1-2018.07" was not found.

### /_cat/indices

    $ curls elk03.mycompany.com:9200/_cat/indices?v | grep-skip1 integration.sandbox-mls.mls-customer-apikey-service-v1.logs-6.2.1-2018.07
    health status index                                                                                         uuid                   pri rep docs.count docs.deleted store.size pri.store.size
    green  open   integration.sandbox-mls.mls-customer-apikey-service-v1.logs-6.2.1-2018.07.07                  NDXoq8g9RGa3TGs54N-bMg   1   2      25920            0     19.1mb          6.3mb
    green  open   integration.sandbox-mls.mls-customer-apikey-service-v1.logs-6.2.1-2018.07.06                  _BGTdXYdRWqPJiSuUKSwiA   1   2      25920            0     19.1mb          6.3mb
    green  open   integration.sandbox-mls.mls-customer-apikey-service-v1.logs-6.2.1-2018.07.04                  nDl1J_BbR3SRVZgxTgX7PA   3   1      25932            0     13.3mb          6.7mb
    green  open   integration.sandbox-mls.mls-customer-apikey-service-v1.logs-6.2.1-2018.07.01                  mRsG3nLET-2Tt5Fp38uC1A   2   1      25921            0     12.9mb          6.4mb
    green  open   integration.sandbox-mls.mls-customer-apikey-service-v1.logs-6.2.1-2018.07.03                  hybDa0ofRzexVskwsHY-AA   2   1      46628            0     18.9mb          9.4mb
    green  open   integration.sandbox-mls.mls-customer-apikey-service-v1.logs-6.2.1-2018.07.08                  ch0iP7vLTFSkVLwtEF-2wQ   1   2      25941            0     19.1mb          6.3mb
    green  open   integration.sandbox-mls.mls-customer-apikey-service-v1.logs-6.2.1-2018.07.09                  mUd8U8HnRmyfG65mNe1MtA   1   2      10323            0      7.9mb          2.6mb
    green  open   integration.sandbox-mls.mls-customer-apikey-service-v1.logs-6.2.1-2018.07.02                  zuLRcH56TJu0-DLTbV9Uew   2   1      25935            0     13.1mb          6.5mb
    green  open   integration.sandbox-mls.mls-customer-apikey-service-v1.logs-6.2.1-2018.07.05                  sf7rMQl2S1WtYSF95Hj4FQ   1   2      25922            0     19.2mb          6.4mb

### /.tasks

For all 32 slices the same data:

    "node": "wa6mTh10SUiCLgUr_OnbAQ",
    "id": 980315623,
    .
    .
    .
    "status": {
      "total": 0,
      "updated": 0,
      "created": 0,
      "deleted": 0,
      "batches": 0,
      "version_conflicts": 0,
      "noops": 0,
      "retries": {
        "bulk": 0,
        "search": 0
      },
    .
    .
    .
    "slices": [
      {
        "slice_id": 0,
        "total": 0,
        "updated": 0,
        "created": 0,
        "deleted": 0,
        "batches": 0,
        "version_conflicts": 0,
        "noops": 0,
        "retries": {
          "bulk": 0,
          "search": 0
        },
        "throttled_millis": 0,
        "requests_per_second": -1,
        "throttled_until_millis": 0
      },

## Detailed Description
I'm wondering that the task finished so quickly (maybe it's ok, because there are only a few documents).

Maybe it's a timing problem, because the task finished to fast?

As a workaround I must create the index for myself and then the job runs without failures.

**Edit**

Added detail from the task. Maybe it could not read the data?

Additional: if there is really no data to reindex, the reindex operation should not fail (and maybe create an empty index)

**Edit II**

The workaround is not really a workaround, because the monthly index has 0 documents.

**Comment by benkeil** [comment]
It was very stupid of me... we have a query to skip health checks for reindexing and the index contains only health check logs...
