### ISSUE TITLE
Curator fails on Elasticsearch 6.4

### ISSUE THREAD

**Issue by Iril** [elastic/curator#1261]
### Expected Behavior
Curator should show me the indices for my elasticsearch ( 6.4 )

### Actual Behavior
$ curator_cli show_indices --verbose
Traceback (most recent call last):
  File "/usr/bin/curator_cli", line 11, in <module>
    load_entry_point('elasticsearch-curator==4.2.5', 'console_scripts', 'curator_cli')()
  File "/usr/lib/python2.7/dist-packages/curator/curator_cli.py", line 5, in main
    cli(obj={})
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/curator/singletons.py", line 532, in show_indices_singleton
    client = get_client(**c_args)
  File "/usr/lib/python2.7/dist-packages/curator/utils.py", line 603, in get_client
    'Error: {0}'.format(e)
elasticsearch.exceptions.ElasticsearchException: Unable to create client connection to Elasticsearch.  Error: Elasticsearch version 6.4.0 incompatible with this version of Curator (6.4.0)

### Steps to Reproduce the Problem
  1. Install elastic / kibana / logstash / curator from : https://www.elastic.co/guide/en/logstash/current/installing-logstash.html
  1. create a .curator directory and install a curator.yml as per
$ cat .curator/curator.yml
# Remember, leave a key empty if there is no value.  None will be a string,
## not a Python "NoneType"

client:
  hosts:
    - localhost
  port: 9200
  url_prefix:
  use_ssl: False
  certificate:
  client_cert:
  client_key:
  ssl_no_validate: False
  http_auth:
  timeout: 30
  master_only: False

logging:
  loglevel: DEBUG
  logfile: /home/fred/logs
  logformat: default
  blacklist: ['elasticsearch', 'urllib3']

  1. run show_indices
$ curator_cli show_indices --verbose

### Specifications

  - Version: Elasticsearch 6.4 
  - curator_cli --version
curator_cli, version 4.2.5
  - Platform: Debian 9 Stretch

**Comment by untergeek** [comment]
You have version 4.2.5, which is not compatible with Elasticsearch 6. You need Curator version 5.5.4.

**Comment by Iril** [comment]
Yep now I see where I went wrong..
Get:7 http://ftp.au.debian.org/debian stretch/main amd64 elasticsearch-curator all 4.2.5-1 [53.9 kB]
It seems version 4.2.5 is the default when you install via the logstash and elasticsearch instructions.

ie its in
deb https://artifacts.elastic.co/packages/6.x/apt stable main

but I needed
deb [arch=amd64] https://packages.elastic.co/curator/5/debian stable main

Apologies..
