### ISSUE TITLE
Cannot connect to elasticsearch using SSL/TLS. Attempting to verify SSL certificate

### ISSUE THREAD

**Issue by tbennett6421** [elastic/curator#1262]
### Expected Behavior

Curator should take the certificate parameter and use that certificate to validate the certificate presented by elasticsearch.

### Actual Behavior
running the following `curator --config curator.yml action.yml` normally presents the following output
`2018-08-27 17:18:53,451 INFO      Preparing Action ID: 1, "forcemerge"`

with options `blacklist []` and `loglevel: DEBUG` set in `curator.yml` I get the following backtrace
```
2018-08-27 17:15:38,249 INFO                 curator.cli                    run:146  Preparing Action ID: 1, "forcemerge"
2018-08-27 17:15:38,249 DEBUG              curator.utils             get_client:803  kwargs = {'hosts': ['m1.example.com'], 'port': 9200, 'use_ssl': True, 'certificate': '/etc/ssl/certs/sub_ca.pem', 'ssl_no_validate': False, 'http_auth': 'admin:pass', 'master_only': False, 'aws_key': None, 'client_cert': None, 'url_prefix': '', 'client_key': None, 'aws_secret_key': None, 'aws_sign_request': False, 'aws_token': None, 'timeout': 21600}
2018-08-27 17:15:38,249 DEBUG              curator.utils             get_client:809  Attempting to verify SSL certificate.
2018-08-27 17:15:38,254 DEBUG              curator.utils             get_client:880  Not using "requests_aws4auth" python module to connect.
2018-08-27 17:15:38,255 DEBUG         urllib3.util.retry               from_int:200  Converted retries value: False -> Retry(total=False, connect=None, read=None, redirect=0, status=None)
2018-08-27 17:15:38,255 DEBUG     urllib3.connectionpool              _new_conn:824  Starting new HTTPS connection (1): m1.example.com
2018-08-27 17:15:38,273 WARNING            elasticsearch       log_request_fail:97   GET https://m1.example.com:9200/ [status:N/A request:0.019s]
Traceback (most recent call last):
  File "/home/buh/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
  File "/home/buh/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 346, in _make_request
  File "/home/buh/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 850, in _validate_conn
  File "/home/buh/.local/lib/python3.6/site-packages/urllib3/connection.py", line 326, in connect
  File "/home/buh/.local/lib/python3.6/site-packages/urllib3/util/ssl_.py", line 329, in ssl_wrap_socket
  File "/usr/local/lib/python3.6/ssl.py", line 407, in wrap_socket
  File "/usr/local/lib/python3.6/ssl.py", line 814, in __init__
  File "/usr/local/lib/python3.6/ssl.py", line 1068, in do_handshake
  File "/usr/local/lib/python3.6/ssl.py", line 689, in do_handshake
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:833)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/buh/.local/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py", line 166, in perform_request
  File "/home/buh/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 639, in urlopen
  File "/home/buh/.local/lib/python3.6/site-packages/urllib3/util/retry.py", line 333, in increment
  File "/home/buh/.local/lib/python3.6/site-packages/urllib3/packages/six.py", line 685, in reraise
  File "/home/buh/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
  File "/home/buh/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 346, in _make_request
  File "/home/buh/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 850, in _validate_conn
  File "/home/buh/.local/lib/python3.6/site-packages/urllib3/connection.py", line 326, in connect
  File "/home/buh/.local/lib/python3.6/site-packages/urllib3/util/ssl_.py", line 329, in ssl_wrap_socket
  File "/usr/local/lib/python3.6/ssl.py", line 407, in wrap_socket
  File "/usr/local/lib/python3.6/ssl.py", line 814, in __init__
  File "/usr/local/lib/python3.6/ssl.py", line 1068, in do_handshake
  File "/usr/local/lib/python3.6/ssl.py", line 689, in do_handshake
urllib3.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:833)
2018-08-27 17:15:38,278 DEBUG              elasticsearch       log_request_fail:105  > None
2018-08-27 17:15:38,279 WARNING            elasticsearch              mark_dead:148  Connection <Urllib3HttpConnection: https://m1.example.com:9200> has failed for 1 times in a row, putting on 60 second timeout.
```

The user I'm running curator as has access to `/etc/ssl/certs/sub_ca.pem` and can read the contents of it. I'm not sure that curator is actually accessing that certificate file

### curator.yml
```
---
client:
  hosts:
    - m1.example.com
  port: 9200
  url_prefix:
  use_ssl: True
  certificate: '/etc/ssl/certs/sub_ca.pem'
  client_cert:
  client_key:
  ssl_no_validate: False
  http_auth: 'admin:pass'
  timeout: 30
  master_only: False

logging:
  loglevel: INFO
  logfile:
  logformat: default
  blacklist: []
```
### action.yml
```
---
actions:
  1:
    action: forcemerge
    description: "Apply ForceMerge to all vuln-whisperer indexs"
    options:
        max_num_segments: 1
        delay: 120
        ignore_empty_list: True
        continue_if_exception: False
        disable_action: False
    filters:
    - filtertype: pattern
      kind: prefix
      value: logstash-vuln*
```

### Specifications
I'm using the binary version of curator
$> curator --version
`curator, version 5.5.4`

## Context (Environment)
* Setting `ssl_no_validate: True` works as a workaround
* We are using the latest patched Ubuntu 16.04 server

**Comment by untergeek** [comment]
Did you mean that `ssl_no_validate: True` works as a workaround?
```
urllib3.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:833)
```
This is not Curator.  This is the upstream urllib3 library that can't verify the certificate.  I do not know why this is, but it's trying, and failing.

**Comment by tbennett6421** [comment]
sorry, that is what I meant.

I'm not sure if curator/urllib3 is seeing the certificate file I'm passing in, at least that's not what I can readily tell in the debug output. Is there anyway to tell?

We use this same CA to secure our entire elasticstack

**Comment by tbennett6421** [comment]
Just moved the pem file into my home directory and tested with the same results.
This is running as myself in an interactive terminal, switching to root didn't seem to make a difference.

**Comment by untergeek** [comment]
What happens if you run:
```
curl --cacert /etc/ssl/certs/sub_ca.pem https://m1.example.com:9200
```

Also, noting the name says `sub_ca`, are there multiple CAs associated? i.e. is `sub_ca` an intermediate certificate signed by a top-level CA?

**Comment by tbennett6421** [comment]
If I run `curl -u admin:pass --cacert /etc/ssl/certs/sub_ca.pem https://m1.example.com:9200` 
I get the elasticsearch version and build info

To your second; there is, we have a corporate Root CA and several Sub CAs.
With that in mind, I generate the CA chain using `cat sub_ca.pem root_ca.pem > chain.pem` and retry
with the follow options
```
certificate: /etc/ssl/certs/chain.pem 
ssl_no_validate: False
```
and it appears to work as expected.

**Comment by untergeek** [comment]
Sorry for the confusion.  It does seem to me that urllib3 expects all parts of a CA to be present to validate the chain.  I will mark this as closed.
