### ISSUE TITLE
Some CLI actions do not work with latest Click version

### ISSUE THREAD

**Issue by Andrewsville** [elastic/curator#1279]
In version 7 authors of Click have changed the auto-naming logic so that it [replaces underscores with dashes](https://github.com/pallets/click/commit/5d1df0e042b2f8b0dee8f6dd9ce74edce331a950). This change makes show_* CLI actions impossible to use.

### Expected Behavior

`curator_cli show_snapshots --repository=repo` outputs a list of snapshots.

### Actual Behavior

`curator_cli show_snapshots` output:

```
Usage: curator_cli [OPTIONS] COMMAND [ARGS]...
Try "curator_cli --help" for help.

Error: No such command "show_snapshots".
```

(Because of the mentioned change in click) curator_cli forces you to think that the actions are actually called show-* but the internal logic of Curator expects them to be called show_* making them impossible to use.

### Specifications

  - Version: 5.5.4
  - Platform: Linux
  - Subsystem: Python 3.7 Alpine based Docker image

## Detailed Description

`curator_cli --help` output snippet:

```
Usage: curator_cli [OPTIONS] COMMAND [ARGS]...

...
  show-indices      Show Indices
  show-snapshots    Show Snapshots
...
```

It correctly outputs action names with dashes (that does not match documentation, though). However trying to use them, you hit a dead end:

`curator_cli show-snapshots` outputs that the `--repository` option is needed. That is correct:

```
Usage: curator_cli show-snapshots [OPTIONS]
Try "curator_cli show-snapshots --help" for help.

Error: Missing option "--repository".
```

But providing it you get an error you can't really fix:

```
2018-10-03 07:54:32,856 CRITICAL  Action must be one of ['alias', 'allocation', 'close', 'cluster_routing', 'create_index', 'delete_indices', 'delete_snapshots', 'forcemerge', 'index_settings', 'open', 'reindex', 'replicas', 'restore', 'rollover', 'shrink', 'snapshot']
Traceback (most recent call last):
  File "/usr/local/bin/curator_cli", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/curator/curator_cli.py", line 8, in main
    cli(obj={})
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/curator/cli_singletons/show.py", line 82, in show_snapshots
    action = cli_action(ctx.info_name, ctx.obj['config']['client'], {}, filter_list, ignore_empty_list, repository=repository)
  File "/usr/local/lib/python3.7/site-packages/curator/cli_singletons/object_class.py", line 52, in __init__
    self.check_options(option_dict)
  File "/usr/local/lib/python3.7/site-packages/curator/cli_singletons/object_class.py", line 103, in check_options
    options.get_schema(self.action),
  File "/usr/local/lib/python3.7/site-packages/curator/validators/options.py", line 144, in get_schema
    for each in action_specific(action):
  File "/usr/local/lib/python3.7/site-packages/curator/validators/options.py", line 129, in action_specific
    return options[action]
KeyError: 'show-snapshots'

```

---

There are three (?) ways to fix that:

1. Introduce an upper version limit to Click.
2. Increase the minimal required version of Click to 7 and make Curator think there are dashes in action names, not underscores.
3. Provide explicit command names.

**Comment by AlexClineBB** [comment]
`pip install click==6.7 elasticsearch-curator==5.5.4` can be used as a workaround.

**Comment by untergeek** [comment]
Will try to release a quick patch release for this as soon as I can.

**Comment by bungoume** [comment]
@untergeek 
Could you release the patched version?
we need to change many install batch by this issue.

**Comment by untergeek** [comment]
The new version will be out within a week-ish.  In the meanwhile, just do the workaround:

```
pip install -U click==6.7
```
