### ISSUE TITLE
elasticsearch-curator fails to work with >=elasticsearch-py-5.5.2,<6.0.0

### ISSUE THREAD

**Issue by hydrapolic** [elastic/curator#1283]
Hello,
elasticsearch-curator-5.5.4 fails to work with elasticsearch-py-5.5.2 (albeit it should according to https://github.com/elastic/curator/blob/master/setup.py#L25):
res = ['elasticsearch>=5.5.2,!=6.0.0,<7.0.0' ]

````
$ curator
Traceback (most recent call last):
  File "/usr/lib/python-exec/python2.7/curator", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib64/python2.7/site-packages/pkg_resources/__init__.py", line 3098, in <module>
    @_call_aside
  File "/usr/lib64/python2.7/site-packages/pkg_resources/__init__.py", line 3082, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/pkg_resources/__init__.py", line 3111, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib64/python2.7/site-packages/pkg_resources/__init__.py", line 573, in _build_master
    ws.require(__requires__)
  File "/usr/lib64/python2.7/site-packages/pkg_resources/__init__.py", line 891, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib64/python2.7/site-packages/pkg_resources/__init__.py", line 777, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'elasticsearch!=6.0.0,<7.0.0,>=5.5.2' distribution was not found and is required by elasticsearch-curator
````

Since elasticsearch-py-5.5.2 the package was renamed from elasticsearch to elasticsearch5:
https://github.com/elastic/elasticsearch-py/commit/f20a73e3f36a54ba47530d8f53f5e3029fe20fcc

elasticsearch-py-6.0.0+ is named elasticsearch so it works with those versions.

Downstream issue: https://bugs.gentoo.org/667526

Thanks

**Comment by untergeek** [comment]
Are you forced to use elasticsearch5? Because the v6 version works just fine with 5x versions of Elasticsearch (at least with all Curator functionality).

**Comment by hydrapolic** [comment]
@untergeek, this is solely an issue of elasticsearch-py, not elasticsearch itself.

**Comment by untergeek** [comment]
I understood that. I was referring to Elasticsearch-py. Elasticsearch-py version 6 works with Elasticsearch versions 5.x through 6.x for all Curator functions. I was asking why you can’t use elasticsearch-py v6

**Comment by untergeek** [comment]
I can. I’d be happy if you submit the PR and I can just merge it. Otherwise it could be 2 weeks before I get to it, as I’m on a business trip.
