### ISSUE TITLE
PIP upgrade breaks curator_cli show_incides, delete_indices and other commands

### ISSUE THREAD

**Issue by salomatu** [elastic/curator#1304]
## Problem description
Upgrading elasticsearch_curator with pip may suddenly make many of the commands unusable with counter-intuitive error messages: commands that existed previously do not seem to exist with the same name, but neither does it work with the "new name" proposed by the help text.

### Quick analysis & hypothesis
In the style of pip, upgrade result in installing the latest versions of any dependency marked only with ">=". In this case it seems Click (depended to version >= 6.7) has introduced some breaking changes in their latest version (7.0), rendering the curator_cli unusable: some command names have been mangled and their respective functionalities cannot be accessed.

First indication of trouble can be seen in the help printout:
```
$ curator_cli --help
[...]
  show-indices      Show Indices
  show-snapshots    Show Snapshots
[...]
```
All underscores in the commands have been replaced with a hyphen. e.g. show_indices -> show-indices.
However, neither form will actually work.

### Expected Behavior
`$ curator_cli show_indices`
Indices are listed.

### Actual Behavior
```
$ curator_cli show_indices
Error: No such command "show_indices".
```

```
$ curator_cli show-indices
2018-10-30 09:54:53,280 CRITICAL  Action must be one of ['snapshot', 'create_index', 'index_settings', 'rollover', 'forcemerge', 'cluster_routing', 'replicas', 'delete_indices', 'allocation', 'alias', 'restore', 'close', 'delete_snapshots', 'open', 'shrink', 'reindex']
Traceback (most recent call last):
  File "/bin/curator_cli", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/site-packages/curator/curator_cli.py", line 8, in main
    cli(obj={})
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/curator/cli_singletons/show.py", line 20, in show_indices
    action = cli_action(ctx.info_name, ctx.obj['config']['client'], {}, filter_list, ignore_empty_list)
  File "/usr/lib/python2.7/site-packages/curator/cli_singletons/object_class.py", line 52, in __init__
    self.check_options(option_dict)
  File "/usr/lib/python2.7/site-packages/curator/cli_singletons/object_class.py", line 94, in check_options
    options.get_schema(self.action),
  File "/usr/lib/python2.7/site-packages/curator/validators/options.py", line 143, in get_schema
    for each in action_specific(action):
  File "/usr/lib/python2.7/site-packages/curator/validators/options.py", line 129, in action_specific
    return options[action]
KeyError: u'show-indices'
```

### Steps to Reproduce the Problem
`pip install --upgrade elasticsearch-curator`

### Specifications
  - Version:  elasticsearch-curator==5.5.4
  - Platform: Centos7 x86_64
  - Subsystem: tested with both python2.7 and python3.6

## Workaround
I was able to restore normal operation by downgrading Click:
`pip install --upgrade click==6.7`

**Comment by untergeek** [comment]
Duplicate.

This was originally reported in #1279 and fixed in #1284
