### ISSUE TITLE
Curator not working with ElasticSearch 6.4.2

### ISSUE THREAD

**Issue by 3h4x** [elastic/curator#1322]
I'm trying to rotate indexes on cloud.elastic.co ES cluster.
Curator version 5.6.0

On port 9243 it's returning:
```
2018-11-29 13:16:25,647 DEBUG                curator.cli                    run:126  action_disabled = False
2018-11-29 13:16:25,648 DEBUG                curator.cli                    run:130  continue_if_exception = False
2018-11-29 13:16:25,648 DEBUG                curator.cli                    run:132  timeout_override = None
2018-11-29 13:16:25,648 DEBUG                curator.cli                    run:134  ignore_empty_list = True
2018-11-29 13:16:25,648 DEBUG                curator.cli                    run:136  allow_ilm_indices = False
2018-11-29 13:16:25,648 INFO                 curator.cli                    run:146  Preparing Action ID: 1, "delete_indices"
2018-11-29 13:16:25,648 DEBUG              curator.utils             get_client:802  kwargs = {'hosts': ['x:9243'], 'use_ssl': True, 'ssl_no_validate': False, 'http_auth': 'auth', 'master_only': False, '>
2018-11-29 13:16:25,648 DEBUG              curator.utils             get_client:808  Attempting to verify SSL certificate.
2018-11-29 13:16:25,654 DEBUG              curator.utils             get_client:877  "requests_aws4auth" module present, but not used.
Traceback (most recent call last):
  File "/Users/x/lib/python3.6/site-packages/elasticsearch/serializer.py", line 77, in loads
    deserializer = self.serializers[mimetype]
KeyError: 'text/html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/x/lib/python3.6/site-packages/curator/utils.py", line 899, in get_client
    check_version(client)
  File "/Users/x/lib/python3.6/site-packages/curator/utils.py", line 685, in check_version
    version_number = get_version(client)
  File "/Users/x/lib/python3.6/site-packages/curator/utils.py", line 658, in get_version
    version = client.info()['version']['number']
  File "/Users/x/lib/python3.6/site-packages/elasticsearch/client/utils.py", line 76, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/Users/x/lib/python3.6/site-packages/elasticsearch/client/__init__.py", line 241, in info
    return self.transport.perform_request('GET', '/', params=params)
  File "/Users/x/lib/python3.6/site-packages/elasticsearch/transport.py", line 345, in perform_request
    data = self.deserializer.loads(data, headers_response.get('content-type'))
  File "/Users/x/lib/python3.6/site-packages/elasticsearch/serializer.py", line 79, in loads
    raise SerializationError('Unknown mimetype, unable to deserialize: %s' % mimetype)
elasticsearch.exceptions.SerializationError: Unknown mimetype, unable to deserialize: text/html
```
And on 9200 port
```
2018-11-29 13:33:09,365 DEBUG              curator.utils             get_client:808  Attempting to verify SSL certificate.
2018-11-29 13:33:09,385 DEBUG              curator.utils             get_client:877  "requests_aws4auth" module present, but not used.
Traceback (most recent call last):
  File "/Users/x/lib/python3.6/site-packages/urllib3/contrib/pyopenssl.py", line 441, in wrap_socket
    cnx.do_handshake()
  File "/Users/x/lib/python3.6/site-packages/OpenSSL/SSL.py", line 1907, in do_handshake
    self._raise_ssl_error(self._ssl, result)
  File "/Users/x/lib/python3.6/site-packages/OpenSSL/SSL.py", line 1639, in _raise_ssl_error
    _raise_current_error()
  File "/Users/x/lib/python3.6/site-packages/OpenSSL/_util.py", line 54, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.SSL.Error: [('SSL routines', 'ssl3_get_record', 'wrong version number')]
```

We also have cluster on ES 5.5.2 and everything works well with it.

**Comment by untergeek** [comment]
When you say that Curator works with a 5.5.2 cluster, is it this exact installation of Curator? Or a different one?

**Comment by 3h4x** [comment]
No, sorry for being ambiguous. 

For ES 5.5.2 cluster I use curator 5.5.2.
For ES 6.4.2 I have used most recent curator version 5.6.0.

**Comment by 3h4x** [comment]
Should `curator` 5.6.0 theoretically work with ES 6.x? is it preferred way to rotate indexes on ES6.x?
I'm missing this information from README, ES 6.x is not in compatibility matrix.

**Comment by untergeek** [comment]
It should be noted that `--dry-run` still requires a full client connection, so even though no action was taken, everything else was real.

You may want to take the approach of installing in a virtualenv too, to see if that helps.

**Comment by untergeek** [comment]
That message implies you're hitting a Kibana endpoint and not an Elasticsearch one.

**Comment by 3h4x** [comment]
Obiously. I'm such a dummy.
