### ISSUE TITLE
Unable to create client connection to Elasticsearch

### ISSUE THREAD

**Issue by thomasryck** [elastic/curator#1339]
I am building a docker image from alpine containing curator and cron but when I test it on my local ES, I got the following error : 

## Error

> C:\Users\tryck\Documents\Docker>docker run dockerfile
> crond: crond (busybox 1.26.2) started, log level 8
> crond: USER root pid  10 cmd /usr/bin/curator  --config /usr/share/curator/config/curator.yml /usr/share/curator/config/delete_log_files_curator.yml
> 2019-01-04 09:19:01,008 INFO      Preparing Action ID: 1, "delete_indices"
> Traceback (most recent call last):
>   File "/usr/bin/curator", line 11, in <module>
>     sys.exit(cli())
>   File "/usr/lib/python2.7/site-packages/click/core.py", line 722, in __call__
>     return self.main(*args, **kwargs)
>   File "/usr/lib/python2.7/site-packages/click/core.py", line 697, in main
>     rv = self.invoke(ctx)
>   File "/usr/lib/python2.7/site-packages/click/core.py", line 895, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/usr/lib/python2.7/site-packages/click/core.py", line 535, in invoke
>     return callback(*args, **kwargs)
>   File "/usr/lib/python2.7/site-packages/curator/cli.py", line 213, in cli
>     run(config, action_file, dry_run)
>   File "/usr/lib/python2.7/site-packages/curator/cli.py", line 160, in run
>     client = get_client(**client_args)
>   File "/usr/lib/python2.7/site-packages/curator/utils.py", line 906, in get_client
>     'Error: {0}'.format(e)
> elasticsearch.exceptions.ElasticsearchException: Unable to create client connection to Elasticsearch.  Error: ConnectionError(<urllib3.connection.HTTPConnection object at 0x7eff8de9e710>: Failed to establish a new connection: [Errno 111] Connection refused) caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7eff8de9e710>: Failed to establish a new connection: [Errno 111] Connection refused)

Looking at the other issues, i checked my ES and curator version and it seems ok :

  - Elasticsearch: 6.5.4
  - Curator : 5.6.0
  - Running in Docker (Linux container) 

ES is running on the default configuration 127.0.0.1:9200

This is my dockerfile:

> FROM alpine:3.6
> 
> RUN apk --update add python py-pip && \
>     pip install -U elasticsearch-curator && \
>     pip install -U requests-aws4auth && \
>      rm -rf /var/cache/apk/*
> 
> ADD entrypoint.sh /entrypoint.sh
> 
> WORKDIR /usr/share/curator
> COPY config ./config
> 
> RUN chmod +x /entrypoint.sh
> 
> #run every minute
> ENV CRON */1  *  *  * *
> ENV ES_HOST 127.0.0.1
> ENV CONFIG_FILE /usr/share/curator/config/curator.yml
> ENV COMMAND /usr/share/curator/config/delete_log_files_curator.yml
> ENV UNIT_COUNT 1
> 
> 
> ENTRYPOINT ["/entrypoint.sh"]

My curator.yml is the default one.

And my delete_log_files_curator.yml is:

> actions:
>   1:
>     action: delete_indices
>     description: >-
>       Delete indices.  Find which to delete by first limiting the list to gelf-
>       prefixed indices. Then further filter those to prevent deletion of anything
>       less than X days old.
>     options:
>       continue_if_exception: False
>       disable_action: False
>     filters:
>     - filtertype: pattern
>       kind: prefix
>       value: gelf-
>     - filtertype: age
>       source: creation_date
>       direction: older
>       unit: days
>       unit_count: ${UNIT_COUNT:1}
>

**Comment by untergeek** [comment]
How will Curator, running in a docker container with its own (virtual) ethernet interface, be able to read from a different container's 127.0.0.1 without doing some port forwarding? The reason you are getting the connection refused message is that there is no Elasticsearch running on _the Curator container's_ 127.0.0.1. The localhost/127.0.0.1 is not shared among all containers that way.

**Comment by thomasryck** [comment]
Es and Curator are not running in different containers for now, ES is running on the curator container host. I will try to investigate that.

thanks,

**Comment by untergeek** [comment]
That Dockerfile doesn't seem to indicate that Elasticsearch is also running in there. The entrypoint only seems to indicate Curator is running in that container. I wish I could draw a simple network diagram, but this is what's going on, if I am understanding correctly:

Container Host:
  - Elasticsearch on 127.0.0.1:9200
  - Docker (usually 172.x.y.z)
    - Curator Container
      - Separate 127.0.0.1
      - Can't reach parent 127.0.0.1:9200

In order for Curator to talk to Elasticsearch, you will have to:

- Make sure to make sure port 9200 is listening on the all IPs, not just localhost

or

- Configure the Curator container to read from the localhost:9200 

And then:

- Point your `ENV ES_HOST` and/or an `ENV ES_PORT` to that IP address/port combo.

**Comment by thomasryck** [comment]
You got it.

**Comment by untergeek** [comment]
Since this is no longer actually a Curator issue, please close it when you are done. I'm going to flag it as an issue that will not be fixed (because it's not something Curator can fix).
