### ISSUE TITLE
Environment variable substitution doesn't work

### ISSUE THREAD

**Issue by igajsin** [elastic/curator#1367]
Hi there. I have curator version 5.6.0 and I try to use env variables. There are my config:

---
client:
  hosts:
    - ${ES_HOST}
  port: ${ES_PORT:9200}
  ...
and my variables:
~ $ env
ES_HOST=11.22.33.44

And I expect than when running curator it substitute data to a config like

---
client:
  hosts:
    - 11.22.33.44
  port: 9200

and will work with that config. Instead, I've got:

curator --dry-run --config ./curator.yml clean.yml 
/usr/local/lib/python3.7/site-packages/curator/utils.py:53: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  return yaml.load(read_file(path))
Schema error: not a valid value for dictionary value @ data['client']['port']
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/curator/validators/schemacheck.py", line 57, in result
    return self.schema(self.config)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 267, in __call__
    return self._compiled([], data)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 589, in validate_dict
    return base_validate(path, iteritems(data), out)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 427, in validate_mapping
    raise er.MultipleInvalid(errors)
voluptuous.error.MultipleInvalid: not a valid value for dictionary value @ data['client']['port']

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/curator", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/curator/cli.py", line 213, in cli
    run(config, action_file, dry_run)
  File "/usr/local/lib/python3.7/site-packages/curator/cli.py", line 106, in run
    client_args = process_config(config)
  File "/usr/local/lib/python3.7/site-packages/curator/config_utils.py", line 37, in process_config
    config = test_config(yaml_file)
  File "/usr/local/lib/python3.7/site-packages/curator/config_utils.py", line 20, in test_config
    'Client Configuration', 'full configuration dictionary').result()
  File "/usr/local/lib/python3.7/site-packages/curator/validators/schemacheck.py", line 69, in result
    self.test_what, self.location, self.badvalue, self.error)
curator.exceptions.ConfigurationError: Configuration: Client Configuration: Location: full configuration dictionary: Bad Value: "{'hosts': ['${ES_HOST}'], 'port': '${ES_PORT:9200}', 'use_ssl': False, 'ssl_no_validate': False, 'timeout': 30, 'master_only': False}", not a valid value for dictionary value @ data['client']['port']. Check configuration file.

**Comment by untergeek** [comment]
Try encapsulating these variables inside double quotes.

**Comment by untergeek** [comment]
Also, Python 3.7 is not yet tested for Curator. It may or may not work properly. It has not been fully evaluated.

**Comment by igajsin** [comment]
I took the docker image python:3-alpine and install curator in it via `pip install elasticsearch-curator`.
Than built a new image and run it with `docker run -e VAR=VALUE` syntax. 

Also, let me try to use another version of python, maybe it helps.

**Comment by igajsin** [comment]
The same for the python 2.7 version:
[curator.log](https://github.com/elastic/curator/files/2978349/curator.log)

**Comment by untergeek** [comment]
```
Bad Value: "{'hosts': ['${ES_HOST}'], 'timeout': 30, 'use_ssl': False, 'master_only': False, 'port': '${ES_PORT:9200}', 'ssl_no_validate': False}"
```
Something about how Docker is handling this is not passing the environment variables in a way that Curator can see/extract them. It is plainly visible in the log you shared.

**Comment by igajsin** [comment]
Interesting. A shell within a Docker container shows me those variables. So it should work in theory. But when I move it out of docker it starts to actually work.

I think I can close the ticket, cause the problem is out of curator.

**Comment by igajsin** [comment]
P.S. And anyway thanks for responce.

**Comment by Stephan3555** [comment]
We are running in the same problem lately. Have you figured out the problem?

**Comment by Stephan3555** [comment]
Update:
Upgrading to newest Curator version did the trick
