### ISSUE TITLE
Unable to sign AWS requests. Failed to import a module: No module named 'html.parser'

### ISSUE THREAD

**Issue by xescab** [elastic/curator#1618]
### Expected Behavior

We want to use curator to manage our ES indices from a Kubernetes pod using IAM roles for service accounts. Right now we are using version 5.8.2 with an assumed role (not involving web identities) and it works fine.

### Actual Behavior

Versions 5.8.3 and 5.8.4 throw the following error:

```
2021-09-23 15:48:14,814 INFO                 curator.cli                    run:164  Creating client object and testing connection
2021-09-23 15:48:14,814 DEBUG              curator.utils       process_ssl_args:826  Attempting to verify SSL certificate.
2021-09-23 15:48:14,851 ERROR              curator.utils       try_boto_session:869  Unable to sign AWS requests. Failed to import a module: No module named 'html.parser'
```

However, using 5.8.2 and AWS web identities fails with:

```
2021-09-22 11:15:49,277 INFO Creating client object and testing connection
2021-09-22 11:15:52,336 WARNING Refreshing temporary credentials failed during mandatory refresh period.
Traceback (most recent call last):
File "/usr/local/lib/python3.7/xml/etree/ElementTree.py", line 1454, in __init__
File "/usr/local/lib/python3.7/xml/parsers/expat.py", line 4, in <module>
ImportError: Error loading shared library libexpat.so.1: No such file or directory (needed by /curator/lib/pyexpat.cpython-37m-x86_64-linux-gnu.so) 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/usr/local/lib/python3.7/xml/etree/ElementTree.py", line 1457, in __init__
ImportError: Error loading shared library libexpat.so.1: No such file or directory (needed by /curator/lib/pyexpat.cpython-37m-x86_64-linux-gnu.so)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/usr/local/lib/python3.7/site-packages/botocore/credentials.py", line 502, in _protected_refresh
File "/usr/local/lib/python3.7/site-packages/botocore/credentials.py", line 643, in fetch_credentials
File "/usr/local/lib/python3.7/site-packages/botocore/credentials.py", line 653, in _get_cached_credentials
File "/usr/local/lib/python3.7/site-packages/botocore/credentials.py", line 863, in _get_credentials
File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 316, in _api_call
File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 622, in _make_api_call
File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 641, in _make_request
File "/usr/local/lib/python3.7/site-packages/botocore/endpoint.py", line 102, in make_request
File "/usr/local/lib/python3.7/site-packages/botocore/endpoint.py", line 135, in _send_request
File "/usr/local/lib/python3.7/site-packages/botocore/endpoint.py", line 167, in _get_response
File "/usr/local/lib/python3.7/site-packages/botocore/endpoint.py", line 218, in _do_get_response
File "/usr/local/lib/python3.7/site-packages/botocore/parsers.py", line 246, in parse
File "/usr/local/lib/python3.7/site-packages/botocore/parsers.py", line 524, in _do_parse
File "/usr/local/lib/python3.7/site-packages/botocore/parsers.py", line 528, in _parse_body_as_xml
File "/usr/local/lib/python3.7/site-packages/botocore/parsers.py", line 451, in _parse_xml_string_to_dom
File "/usr/local/lib/python3.7/xml/etree/ElementTree.py", line 1460, in __init__
ImportError: No module named expat; use SimpleXMLTreeBuilder instead 
```

### Steps to Reproduce the Problem

We have tested both Docker versions and APT binary. Both methods fail.

You can reproduce with:

**config.yml**
```
    client:
      hosts: vpc-xxxx.eu-west-1.es.amazonaws.com
      port: 443
      url_prefix:
      use_ssl: True
      certificate:
      client_cert:
      client_key:
      http_auth:
      aws_sign_request: True
      aws_region: eu-west-1
      timeout: 30
      master_only: False

    logging:
      loglevel: DEBUG
      logfile:
      logformat: default
      blacklist: ['elasticsearch', 'urllib3']
```

**actions.yml**
```
    actions:
      1:
        action: snapshot
        description: Archive the older indices to s3
        options:
          ignore_empty_list: True
          disable_action: False
          repository: s3-logs
          name: '<cwl-apps-{now/d-7d}>'
        filters:
        - filtertype: pattern
          kind: prefix
          value: cwl-apps-
        - filtertype: age
          source: name
          direction: older
          timestring: '%Y.%m.%d'
          unit: days
          unit_count: 7
```
```
vagrant:~$ curator actions.yml --config config.yml
2021-09-23 15:48:14,802 DEBUG                curator.cli                    run:112  Client and logging options validated.
2021-09-23 15:48:14,802 DEBUG                curator.cli                    run:116  default_timeout = 30
2021-09-23 15:48:14,803 DEBUG                curator.cli                    run:120  action_file: actions.yml
[...]
2021-09-23 15:48:14,812 DEBUG     curator.validators.filters                      f:48   Filter #1: {'filtertype': 'age', 'source': 'name', 'direction': 'older', 'timestring': '%Y.%m.%d', 'unit': 'days', 'unit_count': 7, 'epoch': None, 'exclude': False, 'stats_result': 'min_value'}
2021-09-23 15:48:14,813 DEBUG                curator.cli                    run:125  Full list of actions: {1: {'action': 'snapshot', 'description': 'Archive the older indices to s3', 'options': {'ignore_empty_list': True, 'disable_action': False, 'repository': 's3-logs', 'name': '<cwl-pps-{now/d-7d}>', 'allow_ilm_indices': False, 'continue_if_exception': False, 'max_wait': -1, 'skip_repo_fs_check': False, 'wait_interval': 9, 'include_global_state': True, 'wait_for_completion': True, 'ignore_unavailable': False, 'timeout_override': 21600, 'partial': False}, 'filters': [{'filtertype': 'pattern', 'kind': 'prefix', 'value': 'cwl-apps-', 'exclude': False}, {'filtertype': 'age', 'source': 'name', 'direction': 'older', 'timestring': '%Y.%m.%d', 'unit': 'days', 'unit_count': 7, 'epoch': None, 'exclude': False, 'stats_result': 'min_value'}]}}
2021-09-23 15:48:14,813 DEBUG                curator.cli                    run:130  action_disabled = False
2021-09-23 15:48:14,813 DEBUG                curator.cli                    run:133  continue_if_exception = False
2021-09-23 15:48:14,813 DEBUG                curator.cli                    run:136  timeout_override = 21600
2021-09-23 15:48:14,813 DEBUG                curator.cli                    run:138  ignore_empty_list = True
2021-09-23 15:48:14,813 DEBUG                curator.cli                    run:140  allow_ilm_indices = False
2021-09-23 15:48:14,813 INFO                 curator.cli                    run:150  Preparing Action ID: 1, "snapshot"
2021-09-23 15:48:14,814 INFO                 curator.cli                    run:164  Creating client object and testing connection
2021-09-23 15:48:14,814 DEBUG              curator.utils       process_ssl_args:826  Attempting to verify SSL certificate.
2021-09-23 15:48:14,851 ERROR              curator.utils       try_boto_session:869  Unable to sign AWS requests. Failed to import a module: No module named 'html.parser'
```

But `html` is supposed to be in the standard library...

```
vagrant:~$ python3
Python 3.8.10 (default, Jun  2 2021, 10:49:15)
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import html
>>>
```

It only works running the latest version (master code) locally (but then we do not have network connectivity):

```
export AWS_ROLE_ARN=arn:aws:iam::0123456789:role/XXXX
export AWS_WEB_IDENTITY_TOKEN_FILE=token

python3 run_curator.py actions.yml --config config.yml
2021-09-23 10:15:40,427 DEBUG curator.cli run:112 Client and logging options validated.
2021-09-23 10:15:40,427 DEBUG curator.cli run:116 default_timeout = 30
2021-09-23 10:15:40,427 DEBUG curator.cli run:120 action_file: actions.yml
[...]
2021-09-23 10:15:40,439 INFO curator.cli run:150 Preparing Action ID: 1, "snapshot"
2021-09-23 10:15:40,439 INFO curator.cli run:164 Creating client object and testing connection
2021-09-23 10:15:40,440 DEBUG curator.utils process_ssl_args:847 Attempting to verify SSL certificate.
2021-09-23 10:15:40,574 DEBUG botocore.hooks _alias_event_name:421 Changing event name from creating-client-class.iot-data to creating-client-class.iot-data-plane
2021-09-23 10:15:40,578 DEBUG botocore.hooks _alias_event_name:421 Changing event name from before-call.apigateway to before-call.api-gateway
2021-09-23 10:15:40,579 DEBUG botocore.hooks _alias_event_name:421 Changing event name from request-created.machinelearning.Predict to request-created.machine-learning.Predict
2021-09-23 10:15:40,582 DEBUG botocore.hooks _alias_event_name:421 Changing event name from before-parameter-build.autoscaling.CreateLaunchConfiguration to before-parameter-build.auto-scaling.CreateLaunchConfiguration
2021-09-23 10:15:40,582 DEBUG botocore.hooks _alias_event_name:421 Changing event name from before-parameter-build.route53 to before-parameter-build.route-53
2021-09-23 10:15:40,583 DEBUG botocore.hooks _alias_event_name:421 Changing event name from request-created.cloudsearchdomain.Search to request-created.cloudsearch-domain.Search
2021-09-23 10:15:40,585 DEBUG botocore.hooks _alias_event_name:421 Changing event name from docs.*.autoscaling.CreateLaunchConfiguration.complete-section to docs.*.auto-scaling.CreateLaunchConfiguration.complete-section
2021-09-23 10:15:40,589 DEBUG botocore.hooks _alias_event_name:421 Changing event name from before-parameter-build.logs.CreateExportTask to before-parameter-build.cloudwatch-logs.CreateExportTask
2021-09-23 10:15:40,589 DEBUG botocore.hooks _alias_event_name:421 Changing event name from docs.*.logs.CreateExportTask.complete-section to docs.*.cloudwatch-logs.CreateExportTask.complete-section
2021-09-23 10:15:40,590 DEBUG botocore.hooks _alias_event_name:421 Changing event name from before-parameter-build.cloudsearchdomain.Search to before-parameter-build.cloudsearch-domain.Search
2021-09-23 10:15:40,590 DEBUG botocore.hooks _alias_event_name:421 Changing event name from docs.*.cloudsearchdomain.Search.complete-section to docs.*.cloudsearch-domain.Search.complete-section
2021-09-23 10:15:40,591 DEBUG botocore.session set_config_variable:311 Setting config variable for region to 'eu-west-1'
2021-09-23 10:15:40,603 DEBUG botocore.utils _select_base_url:396 IMDS ENDPOINT: http://169.254.169.254/
2021-09-23 10:15:40,606 DEBUG botocore.credentials load_credentials:1976 Looking for credentials via: env
2021-09-23 10:15:40,607 DEBUG botocore.credentials load_credentials:1976 Looking for credentials via: assume-role
2021-09-23 10:15:40,608 DEBUG botocore.credentials load_credentials:1976 Looking for credentials via: assume-role-with-web-identity
2021-09-23 10:15:40,609 DEBUG botocore.loaders load_file:175 Loading JSON file: /home/vagrant/.local/lib/python3.6/site-packages/botocore/data/endpoints.json
2021-09-23 10:15:40,621 DEBUG botocore.hooks _emit:210 Event choose-service-name: calling handler <function handle_service_name_alias at 0x7f79ca5f79d8>
2021-09-23 10:15:40,627 DEBUG botocore.loaders load_file:175 Loading JSON file: /home/vagrant/.local/lib/python3.6/site-packages/botocore/data/sts/2011-06-15/service-2.json
2021-09-23 10:15:40,629 DEBUG botocore.hooks _emit:210 Event creating-client-class.sts: calling handler <function add_generate_presigned_url at 0x7f79ca624400>
2021-09-23 10:15:40,631 DEBUG botocore.endpoint create_endpoint:292 Setting sts timeout as (60, 60)
2021-09-23 10:15:40,633 DEBUG botocore.loaders load_file:175 Loading JSON file: /home/vagrant/.local/lib/python3.6/site-packages/botocore/data/_retry.json
2021-09-23 10:15:40,634 DEBUG botocore.client _register_legacy_retries:166 Registering retry handlers for service: sts
2021-09-23 10:15:40,634 DEBUG botocore.hooks _emit:210 Event before-parameter-build.sts.AssumeRoleWithWebIdentity: calling handler <function generate_idempotent_uuid at 0x7f79ca592d90>
2021-09-23 10:15:40,635 DEBUG botocore.hooks _emit:210 Event before-call.sts.AssumeRoleWithWebIdentity: calling handler <function inject_api_version_header_if_needed at 0x7f79ca599598>
2021-09-23 10:15:40,635 DEBUG botocore.endpoint make_request:101 Making request for OperationModel(name=AssumeRoleWithWebIdentity) with params: {'url_path': '/', 'query_string': '', 'method': 'POST', 'headers': {'Content-Type': 'application/x-www-form-urlencoded; charset=utf-8', 'User-Agent': 'Boto3/1.18.46 Python/3.6.9 Linux/4.15.0-156-generic Botocore/1.21.46'}, 'body': {'Action': 'AssumeRoleWithWebIdentity', 'Version': '2011-06-15', 'RoleArn': 'arn:aws:iam::0123456789:role/XXXX', 'RoleSessionName': 'botocore-session-1632384940', 'WebIdentityToken': 'eyJhbGciOiJSUzI1NiIsI[...]6w47uAOvrOxznsmOkwr0MnX_Q\n'}, 'url': 'https://sts.amazonaws.com/', 'context': {'client_region': 'eu-west-1', 'client_config': <botocore.config.Config object at 0x7f79ca2163c8>, 'has_streaming_input': False, 'auth_type': None}}
2021-09-23 10:15:40,635 DEBUG botocore.hooks _emit:210 Event request-created.sts.AssumeRoleWithWebIdentity: calling handler <bound method RequestSigner.handler of <botocore.signers.RequestSigner object at 0x7f79ca216390>>
2021-09-23 10:15:40,636 DEBUG botocore.hooks _emit:210 Event choose-signer.sts.AssumeRoleWithWebIdentity: calling handler <function disable_signing at 0x7f79ca598268>
2021-09-23 10:15:40,637 DEBUG botocore.endpoint _do_get_response:187 Sending http request: <AWSPreparedRequest stream_output=False, method=POST, url=https://sts.amazonaws.com/, headers={'Content-Type': b'application/x-www-form-urlencoded; charset=utf-8', 'User-Agent': b'Boto3/1.18.46 Python/3.6.9 Linux/4.15.0-156-generic Botocore/1.21.46', 'Content-Length': '1204'}>
2021-09-23 10:15:40,638 DEBUG botocore.httpsession get_cert_path:51 Certificate path: /home/vagrant/.local/lib/python3.6/site-packages/certifi/cacert.pem
2021-09-23 10:15:41,215 DEBUG botocore.parsers parse:233 Response headers: {'x-amzn-RequestId': 'fd17ea80-c2f9-xxxx-xxxx-yyyy', 'Content-Type': 'text/xml', 'Content-Length': '1935', 'Date': 'Thu, 23 Sep 2021 08:15:41 GMT'}
2021-09-23 10:15:41,215 DEBUG botocore.parsers parse:234 Response body:
b'<AssumeRoleWithWebIdentityResponse xmlns="https://sts.amazonaws.com/doc/2011-06-15/">\n <AssumeRoleWithWebIdentityResult>\n <Audience>sts.amazonaws.com</Audience>\n <AssumedRoleUser>\n <AssumedRoleId>AROA2GUXXXXXTH5A:botocore-session-1632384940</AssumedRoleId>\n <Arn>arn:aws:sts::0123456789:assumed-role/XXXX/botocore-session-1632384940</Arn>\n </AssumedRoleUser>\n <Provider>arn:aws:iam::0123456789:oidc-provider/oidc.eks.eu-west-1.amazonaws.com/id/XXXX</Provider>\n <Credentials>\n <AccessKeyId>XXXX</AccessKeyId>\n <SecretAccessKey>YYYY</SecretAccessKey>\n <SessionToken>XXXXwJ44TuYVA</SessionToken>\n <Expiration>2021-09-23T09:15:41Z</Expiration>\n </Credentials>\n <SubjectFromWebIdentityToken>system:serviceaccount:jobs:curator</SubjectFromWebIdentityToken>\n </AssumeRoleWithWebIdentityResult>\n <ResponseMetadata>\n <RequestId>fd17ea80-c2f9-459c-8e3c-2546ed2c1676</RequestId>\n </ResponseMetadata>\n</AssumeRoleWithWebIdentityResponse>\n'
2021-09-23 10:15:41,220 DEBUG botocore.hooks _emit:210 Event needs-retry.sts.AssumeRoleWithWebIdentity: calling handler <botocore.retryhandler.RetryHandler object at 0x7f79ca2166d8>
2021-09-23 10:15:41,220 DEBUG botocore.retryhandler __call__:187 No retry needed.
2021-09-23 10:15:41,224 DEBUG botocore.credentials _set_from_data:583 Retrieved credentials will expire at: 2021-09-23 09:15:41+00:00
2021-09-23 10:15:41,226 DEBUG curator.utils try_aws_auth:910 Checking for AWS settings
2021-09-23 10:15:41,229 INFO curator.utils try_aws_auth:919 Configuring client to connect to AWS endpoint
2021-09-23 10:15:41,230 WARNING curator.utils process_auth_args:797 Use of "http_auth" is deprecated. Please use "username" and "password" instead.
2021-09-23 10:15:41,230 DEBUG curator.utils get_client:1046 kwargs = {'hosts': ['vpc-xxxx.eu-west-1.es.amazonaws.com'], 'port': 443, 'use_ssl': True, 'aws_sign_request': True, 'aws_region': 'eu-west-1', 'aws_token': 'XXXXwJ44TuYVA', 'client_key': None, 'http_auth': <requests_aws4auth.aws4auth.AWS4Auth object at 0x7f79cb8b3b38>, 'ssl_no_validate': False, 'client_cert': None, 'url_prefix': '', 'aws_secret_key': 'XXXX', 'aws_key': 'XXXX', 'certificate': None, 'timeout': 21600, 'connection_class': <class 'elasticsearch.connection.http_requests.RequestsHttpConnection'>, 'verify_certs': True, 'ca_certs': '/home/vagrant/.local/lib/python3.6/site-packages/certifi/cacert.pem', 'api_key': None}
2021-09-23 10:15:41,230 INFO curator.utils get_client:1051 Instantiating client object
2021-09-23 10:15:41,231 INFO curator.utils get_client:1054 Testing client connectivity
``` 

Could it be related with building the binary?

**Comment by untergeek** [comment]
Curator v8 and any Elasticsearch above 7.10.2 doesn't support AWS any more. Marking as closed as it is no longer relevant.
