### ISSUE TITLE
timeout switch not working

### ISSUE THREAD

**Issue by djal** [elastic/curator#162]
Seems that `--timeout` switch does not set any timeout. Here is log:

```
curator --timeout 1440 delete --older-than 7 --prefix corom_metric_logs-                                                                                                                            
2014-09-19 12:00:52,422 INFO      Job starting...
2014-09-19 12:00:52,425 INFO      Beginning DELETE operations...
2014-09-19 12:00:52,432 INFO      Attempting to delete index corom_metric_logs-2014.09.12.
Traceback (most recent call last):
  File "/usr/local/bin/curator", line 9, in <module>
    load_entry_point('elasticsearch-curator==1.2.2', 'console_scripts', 'curator')()
  File "/usr/local/lib/python2.6/dist-packages/curator/curator.py", line 731, in main
    arguments.func(client, **argdict)
  File "/usr/local/lib/python2.6/dist-packages/curator/curator.py", line 585, in command_loop
    skipped = op(client, index_name, **kwargs)
  File "/usr/local/lib/python2.6/dist-packages/curator/curator.py", line 434, in _delete_index
    client.indices.delete(index=index_name)
  File "/usr/local/lib/python2.6/dist-packages/elasticsearch/client/utils.py", line 68, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/local/lib/python2.6/dist-packages/elasticsearch/client/indices.py", line 157, in delete
    params=params)
  File "/usr/local/lib/python2.6/dist-packages/elasticsearch/transport.py", line 284, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/usr/local/lib/python2.6/dist-packages/elasticsearch/connection/http_urllib3.py", line 55, in perform_request
    self._raise_error(response.status, raw_data)
  File "/usr/local/lib/python2.6/dist-packages/elasticsearch/connection/base.py", line 97, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.TransportError: TransportError(503, u'ProcessClusterEventTimeoutException[failed to process cluster event (delete-index [corom_metric_logs-2014.09.12]) within 30s]')
```

**Comment by JeremyShort** [comment]
I was seeing the same issue, if I boost the timeout up to 120 seconds then it gets through...kind of odd, maybe the remote file system the snapshots are being stored on is responding slowly?
   root@elasticsearch-prod1 ~]#  curator --timeout 45 delete snapshots --repository es-dump-prod --older-than 30 --timestring %Y-%m-%d --time-unit days 
    2015-07-08 16:39:22,438 INFO      Job starting: delete snapshots
    2015-07-08 16:39:22,982 INFO      Deleting snapshot snapshot_2015-03-31
    Traceback (most recent call last):
      File "/usr/bin/curator", line 9, in <module>
        load_entry_point('elasticsearch-curator==3.2.0', 'console_scripts', 'curator')()
      File "/usr/lib/python2.6/site-packages/curator/curator.py", line 5, in main
        cli( obj={ "filters": [] } )
      File "/usr/lib/python2.6/site-packages/click/core.py", line 664, in __call__
        return self.main(*args, **kwargs)
      File "/usr/lib/python2.6/site-packages/click/core.py", line 644, in main
        rv = self.invoke(ctx)
      File "/usr/lib/python2.6/site-packages/click/core.py", line 991, in invoke
        return _process_result(sub_ctx.command.invoke(sub_ctx))
      File "/usr/lib/python2.6/site-packages/click/core.py", line 991, in invoke
        return _process_result(sub_ctx.command.invoke(sub_ctx))   
       File "/usr/lib/python2.6/site-packages/click/core.py", line 837, in invoke
        return ctx.invoke(self.callback, **ctx.params)
       File "/usr/lib/python2.6/site-packages/click/core.py", line 464, in invoke
        return callback(*args, **kwargs)
      File "/usr/lib/python2.6/site-packages/curator/cli/snapshot_selection.py", line 91, in snapshots
        retval = delete_snapshot(client, snapshot=snap, repository=repository)
      File "/usr/lib/python2.6/site-packages/curator/api/snapshot.py", line 113, in delete_snapshot
        client.snapshot.delete(repository=repository, snapshot=snapshot)
      File "/usr/lib/python2.6/site-packages/elasticsearch/client/utils.py", line 69, in _wrapped
        return func(*args, params=params, **kwargs)
      File "/usr/lib/python2.6/site-packages/elasticsearch/client/snapshot.py", line 40, in delete
        _make_path('_snapshot', repository, snapshot), params=params)
      File "/usr/lib/python2.6/site-packages/elasticsearch/transport.py", line 307, in perform_request
        status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore,     timeout=timeout)
      File "/usr/lib/python2.6/site-packages/elasticsearch/connection/http_urllib3.py", line 82, in   perform_request
        raise ConnectionTimeout('TIMEOUT', str(e), e)
     elasticsearch.exceptions.ConnectionTimeout: ConnectionTimeout caused by -     ReadTimeoutError(HTTPConnectionPool(host=u'localhost', port=9200): Read timed out. (read  timeout=45))
    [root@elasticsearch-prod1 ~]#  curator --timeout 120 delete snapshots --repository es-dump-prod --older-than 30 --timestring %Y-%m-%d --time-unit days 
    2015-07-08 16:40:47,398 INFO      Job starting: delete snapshots
    2015-07-08 16:40:47,736 INFO      Deleting snapshot snapshot_2015-04-01
    2015-07-08 16:41:40,890 INFO      Deleting snapshot snapshot_2015-04-02
    2015-07-08 16:42:46,021 INFO      Deleting snapshot snapshot_2015-04-03
