### ISSUE TITLE
Unable to build curator docker image using  docker.elastic.co/ubi8/ubi-minimal:latest

### ISSUE THREAD

**Issue by vinodhreddyg** [elastic/curator#1626]
## To submit a bug or report an issue
Unable to build  curator docker image using docker.elastic.co/ubi8/ubi-minimal:latest.

### Expected Behavior
Able to build curator docker image using  docker.elastic.co/ubi8/ubi-minimal:latest.

### Actual Behavior
Unable to build curator docker image using  docker.elastic.co/ubi8/ubi-minimal:latest.

### Steps to Reproduce the Problem
  1. Change docker base image to ubi8-minimal and add required packages.
  1. It collected all the dependencies mentioned in requirements.txt. While performing install it failed.
  1.

### Specifications

  - Version: Python 3.6.8, pip 9.0.3
  - Platform: macx, docker image : docker.elastic.co/ubi8/ubi-minimal:latest (Red Hat Enterprise Linux release 8.4 (Ootpa))
  - Subsystem: docker for mac

## Context (Environment)
GKE 1.21

## Detailed Description
```#12 10.70 Installing collected packages: voluptuous, certifi, urllib3, elasticsearch, charset-normalizer, idna, requests, six, python-dateutil, jmespath, botocore, s3transfer, boto3, requests-aws4auth, click, pyyaml
#12 10.70   Running setup.py install for voluptuous: started
#12 10.93     Running setup.py install for voluptuous: finished with status 'done'
#12 11.04 Exception:
#12 11.04 Traceback (most recent call last):
#12 11.04   File "/usr/lib/python3.6/site-packages/pip/basecommand.py", line 215, in main
#12 11.04     status = self.run(options, args)
#12 11.04   File "/usr/lib/python3.6/site-packages/pip/commands/install.py", line 365, in run
#12 11.04     strip_file_prefix=options.strip_file_prefix,
#12 11.04   File "/usr/lib/python3.6/site-packages/pip/req/req_set.py", line 789, in install
#12 11.04     **kwargs
#12 11.04   File "/usr/lib/python3.6/site-packages/pip/req/req_install.py", line 854, in install
#12 11.04     strip_file_prefix=strip_file_prefix
#12 11.04   File "/usr/lib/python3.6/site-packages/pip/req/req_install.py", line 1069, in move_wheel_files
#12 11.04     strip_file_prefix=strip_file_prefix,
#12 11.04   File "/usr/lib/python3.6/site-packages/pip/wheel.py", line 247, in move_wheel_files
#12 11.04     prefix=prefix,
#12 11.04   File "/usr/lib/python3.6/site-packages/pip/locations.py", line 141, in distutils_scheme
#12 11.04     d.parse_config_files()
#12 11.04   File "/usr/lib/python3.6/site-packages/setuptools/dist.py", line 495, in parse_config_files
#12 11.04     ignore_option_errors=ignore_option_errors)
#12 11.04   File "/usr/lib/python3.6/site-packages/setuptools/config.py", line 111, in parse_configuration
#12 11.04     meta.parse()
#12 11.04   File "/usr/lib/python3.6/site-packages/setuptools/config.py", line 397, in parse
#12 11.04     section_parser_method(section_options)
#12 11.04   File "/usr/lib/python3.6/site-packages/setuptools/config.py", line 370, in parse_section
#12 11.04     self[name] = value
#12 11.04   File "/usr/lib/python3.6/site-packages/setuptools/config.py", line 174, in __setitem__
#12 11.04     value = parser(value)
#12 11.04   File "/usr/lib/python3.6/site-packages/setuptools/config.py", line 463, in _parse_version
#12 11.04     version = self._parse_attr(value, self.package_dir)
#12 11.04   File "/usr/lib/python3.6/site-packages/setuptools/config.py", line 320, in _parse_attr
#12 11.04     module = import_module(module_name)
#12 11.04   File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
#12 11.04     return _bootstrap._gcd_import(name[level:], package, level)
#12 11.04   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
#12 11.04   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
#12 11.04   File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
#12 11.04   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
#12 11.04   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
#12 11.04   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
#12 11.04   File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
#12 11.04   File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
#12 11.04   File "<frozen importlib._bootstrap_external>", line 678, in exec_module
#12 11.04   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
#12 11.04   File "/curator/__init__.py", line 7, in <module>
#12 11.04     from curator.utils import *
#12 11.04   File "/curator/utils.py", line 10, in <module>
#12 11.04     import yaml
#12 11.04 ModuleNotFoundError: No module named 'yaml'
------
executor failed running [/bin/sh -c pip3 install -r requirements.txt]: exit code: 2```

**Comment by untergeek** [comment]
This is resolved with the most recent releases of Curator
