### ISSUE TITLE
curator fails to install due to: SyntaxError: future feature annotations is not defined

### ISSUE THREAD

**Issue by archon810** [elastic/curator#1644]
### Expected Behavior
curator installs

### Actual Behavior
Both `pip install -r requirements.txt` and `pip install elasticsearch-curator` result in:
```
Traceback (most recent call last):
  File "/usr/bin/pip", line 33, in <module>
    sys.exit(load_entry_point('pip==22.0.4', 'console_scripts', 'pip3.6')())
  File "/usr/bin/pip", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.6/site-packages/importlib_metadata/__init__.py", line 194, in load
    module = import_module(match.group('module'))
  File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/python3.6/site-packages/pip/_internal/cli/main.py", line 9, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "/usr/lib/python3.6/site-packages/pip/_internal/cli/autocompletion.py", line 10, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "/usr/lib/python3.6/site-packages/pip/_internal/cli/main_parser.py", line 8, in <module>
    from pip._internal.cli import cmdoptions
  File "/usr/lib/python3.6/site-packages/pip/_internal/cli/cmdoptions.py", line 23, in <module>
    from pip._internal.cli.parser import ConfigOptionParser
  File "/usr/lib/python3.6/site-packages/pip/_internal/cli/parser.py", line 12, in <module>
    from pip._internal.configuration import Configuration, ConfigurationError
  File "/usr/lib/python3.6/site-packages/pip/_internal/configuration.py", line 24, in <module>
    from pip._internal.utils import appdirs
  File "/usr/lib/python3.6/site-packages/pip/_internal/utils/appdirs.py", line 13, in <module>
    from pip._vendor import platformdirs as _appdirs
  File "/usr/lib/python3.6/site-packages/pip/_vendor/platformdirs/__init__.py", line 5
    from __future__ import annotations
    ^
SyntaxError: future feature annotations is not defined
```

### Specifications

  - Version: git/pip
  - Platform: OpenSUSE 15.3
  - Python 3.6

Is Python 3.6 the problem? Is there a solution for Python 3.6 users that don't have 3.7+?

**Comment by archon810** [comment]
Hmm, even pip doesn't run on my system and spits out the same error, so it's not curator's fault, but rather pip's.
I ended up installing Python 3.9, and curator installed correctly.
