### ISSUE TITLE
Add subroutine to check for running snapshots

### ISSUE THREAD

**Issue by untergeek** [elastic/curator#177]
Because nobody wants to see

```
2014-10-01 14:10:33,870 INFO      Capturing snapshots of specified indices...
Traceback (most recent call last):
  File "/usr/local/bin/curator", line 9, in <module>
    load_entry_point('elasticsearch-curator==2.0.0', 'console_scripts', 'curator')()
  File "/usr/local/lib/python2.7/dist-packages/curator/curator_script.py", line 357, in main
    arguments.func(client, **argdict)
  File "/usr/local/lib/python2.7/dist-packages/curator/curator.py", line 1108, in snapshot
    create_snapshot(client, indices=matching_indices, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/curator/curator.py", line 649, in create_snapshot
    client.snapshot.create(repository=repository, snapshot=snapshot_name, body=body, wait_for_completion=wait_for_completion)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/client/utils.py", line 68, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/client/snapshot.py", line 19, in create
    repository, snapshot), params=params, body=body)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/transport.py", line 284, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/connection/http_urllib3.py", line 55, in perform_request
    self._raise_error(response.status, raw_data)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/connection/base.py", line 97, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.TransportError: TransportError(503, u'RemoteTransportException[[log-elasticsearch-04][inet[/10.225.0.80:9300]][cluster/snapshot/create]]; nested: ProcessClusterEventTimeoutException[failed to process cluster event (create_snapshot[curator-20141001211034]) within 30s]; ')
```

when a snapshot is already running.

**Comment by priyaprabhakar777** [comment]
@untergeek does that mean 503 error happened because another curator service was already running
