### ISSUE TITLE
older-than parameter doesn't work

### ISSUE THREAD

**Issue by Grauen** [elastic/curator#234]
Hi there, I tested curator on three of my machines. In two cases curator worked great but on one machine curator won't close my indices when I use the "older-than" attribute. I was able to close indices manually so I think the problem is related with my indices timestamps.  What timestampformats does curator support?

**Comment by tdm4** [comment]
Why are the commands/switches so complex? I tried using this according to an article I read: http://www.ragingcomputer.com/2014/02/removing-old-records-for-logstash-elasticsearch-kibana

Apparently -d is no longer a switch. It's difficult to figure out the right command-line to clean up records, so you end up trying different combinations:

$ /usr/local/bin/curator delete indices --older-than 90
Parameters --older-than and --newer-than require the --time-unit parameter
$ /usr/local/bin/curator delete indices --older-than 90 --time-unit days
Parameters --older-than and --newer-than require the --timestring parameter
$ /usr/local/bin/curator delete indices --timestring 2015.05.22 --older-than 30 --time-unit days
2015-06-23 17:29:31,055 INFO      Job starting: delete indices
Traceback (most recent call last):
  File "/usr/local/bin/curator", line 9, in <module>
    load_entry_point('elasticsearch-curator==3.1.0', 'console_scripts', 'curator')()
  File "/usr/local/lib/python2.7/dist-packages/curator/curator.py", line 5, in main
    cli( obj={ "filters": [] } )
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 664, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 644, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 991, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 991, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 837, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 464, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/curator/cli/index_selection.py", line 80, in indices
    working_list = apply_filter(working_list, **f)
  File "/usr/local/lib/python2.7/dist-packages/curator/api/filter.py", line 113, in apply_filter
    p = re.compile(pattern)
  File "/usr/lib/python2.7/re.py", line 190, in compile
    return _compile(pattern, flags)
  File "/usr/lib/python2.7/re.py", line 244, in _compile
    raise error, v # invalid expression
sre_constants.error: bogus escape: '\\2'

Whoa it sure didn't like that.

What was wrong with -d ?
