### ISSUE TITLE
`curator delete` results in a connection error (update: delete by space needs the fix)

### ISSUE THREAD

**Issue by poolski** [elastic/curator#245]
When I run curator with optimize/close, it completes fine, but when I try to delete indices that are either older than X days or with a space constraint, I get the following
```bash
Traceback (most recent call last):
  File "/usr/local/bin/curator", line 9, in <module>
    load_entry_point('elasticsearch-curator==2.1.1', 'console_scripts', 'curator')()
  File "/usr/local/lib/python2.7/dist-packages/curator/curator_script.py", line 364, in main
    arguments.func(client, **argdict)
  File "/usr/local/lib/python2.7/dist-packages/curator/curator.py", line 1004, in delete
    _op_loop(client, matching_indices, op=delete_index, dry_run=dry_run, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/curator/curator.py", line 742, in _op_loop
    for item in object_list:
  File "/usr/local/lib/python2.7/dist-packages/curator/curator.py", line 434, in filter_by_space
    stats = client.indices.status(index=csv_indices)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/client/utils.py", line 68, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/client/indices.py", line 705, in status
    params=params)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/transport.py", line 306, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/connection/http_urllib3.py", line 78, in perform_request
    raise ConnectionError('N/A', str(e), e)
elasticsearch.exceptions.ConnectionError: ConnectionError(('Connection aborted.', BadStatusLine("''",))) caused by: ProtocolError(('Connection aborted.', BadStatusLine("''",)))
```

**Comment by untergeek** [comment]
Try increasing the timeout value `--timeout`.  The default 30 seconds does not appear to be enough in your use case.

**Comment by untergeek** [comment]
`optimize` would work fine because it automatically implements a `21600` second timeout (if you don't override with your own).  `close` probably works because Elasticsearch may not have to worry about shard allocation after closing.

**Comment by poolski** [comment]
I see. I'll check that and report back!

Cheers!

**Comment by untergeek** [comment]
Any report?

**Comment by poolski** [comment]
Still happening, even with a timeout value set..

```bash
me@host$ curator --dry-run --timeout 120 --host localhost --port 9200 delete --disk-space 1024
2015-01-16 16:35:31,601 INFO      Job starting...
2015-01-16 16:35:31,602 INFO      DRY RUN MODE.  No changes will be made.
2015-01-16 16:35:31,881 INFO      DRY RUN: Deleting indices...
2015-01-16 16:35:31,881 INFO      DRY RUN: Deleting by space rather than time.
Traceback (most recent call last):
  File "/usr/local/bin/curator", line 9, in <module>
    load_entry_point('elasticsearch-curator==2.1.1', 'console_scripts', 'curator')()
  File "/usr/local/lib/python2.7/dist-packages/curator/curator_script.py", line 364, in main
    arguments.func(client, **argdict)
  File "/usr/local/lib/python2.7/dist-packages/curator/curator.py", line 1004, in delete
    _op_loop(client, matching_indices, op=delete_index, dry_run=dry_run, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/curator/curator.py", line 742, in _op_loop
    for item in object_list:
  File "/usr/local/lib/python2.7/dist-packages/curator/curator.py", line 434, in filter_by_space
    stats = client.indices.status(index=csv_indices)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/client/utils.py", line 68, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/client/indices.py", line 705, in status
    params=params)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/transport.py", line 306, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/connection/http_urllib3.py", line 78, in perform_request
    raise ConnectionError('N/A', str(e), e)
elasticsearch.exceptions.ConnectionError: ConnectionError(('Connection aborted.', BadStatusLine("''",))) caused by: ProtocolError(('Connection aborted.', BadStatusLine("''",)))
```

**Comment by untergeek** [comment]
Connection aborted indicates something outside of curator (note that it's `http_urllib3`).

2 minutes (120 seconds) may yet be too short, or something else is going on here which is beyond the scope of curator itself.

**Comment by poolski** [comment]
I thought this as well, but it fails after ~10 seconds, which implies that the time out isn't being hit at all.

**Comment by untergeek** [comment]
Interesting.  Does it work if you try a delete by time? Test with the `-n` flag to prevent it from actually deleting anything.

**Comment by charlesnadeau** [comment]
I have the exact same problem:
```
charles@bigzilla:/etc/elasticsearch$ /usr/local/bin/curator --timeout 1000 --host localhost --port 9200 delete --disk-space 100
2015-01-18 18:24:27,972 INFO      Job starting...
2015-01-18 18:24:27,974 INFO      Deleting indices...
2015-01-18 18:24:27,974 INFO      Deleting by space rather than time.
Traceback (most recent call last):
  File "/usr/local/bin/curator", line 9, in <module>
    load_entry_point('elasticsearch-curator==2.1.1', 'console_scripts', 'curator')()
  File "/usr/local/lib/python2.7/dist-packages/curator/curator_script.py", line 364, in main
    arguments.func(client, **argdict)
  File "/usr/local/lib/python2.7/dist-packages/curator/curator.py", line 1025, in delete
    _op_loop(client, matching_indices, op=delete_index, dry_run=dry_run, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/curator/curator.py", line 763, in _op_loop
    for item in object_list:
  File "/usr/local/lib/python2.7/dist-packages/curator/curator.py", line 434, in filter_by_space
    stats = client.indices.status(index=csv_indices)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/client/utils.py", line 68, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/client/indices.py", line 705, in status
    params=params)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/transport.py", line 301, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/connection/http_urllib3.py", line 78, in perform_request
    raise ConnectionError('N/A', str(e), e)
elasticsearch.exceptions.ConnectionError: ConnectionError(('Connection aborted.', BadStatusLine("''",))) caused by: ProtocolError(('Connection aborted.', BadStatusLine("''",)))
```
However it does work with a delete by time:
```
charles@bigzilla:/etc/elasticsearch$ /usr/local/bin/curator --dry-run --timeout 1000 --host localhost --port 9200 delete --older-than 3
2015-01-18 18:27:40,670 INFO      Job starting...
2015-01-18 18:27:40,670 INFO      DRY RUN MODE.  No changes will be made.
2015-01-18 18:27:40,672 INFO      DRY RUN: Deleting indices...
2015-01-18 18:27:48,666 INFO      DRY RUN: of delete_index operation on logstash-2014.12.21
2015-01-18 18:27:48,666 INFO      DRY RUN: of delete_index operation on logstash-2014.12.22
2015-01-18 18:27:48,666 INFO      DRY RUN: of delete_index operation on logstash-2014.12.23
2015-01-18 18:27:48,666 INFO      DRY RUN: of delete_index operation on logstash-2014.12.24
2015-01-18 18:27:48,666 INFO      DRY RUN: of delete_index operation on logstash-2014.12.25
2015-01-18 18:27:48,666 INFO      DRY RUN: of delete_index operation on logstash-2014.12.26
2015-01-18 18:27:48,666 INFO      DRY RUN: of delete_index operation on logstash-2014.12.27
2015-01-18 18:27:48,666 INFO      DRY RUN: of delete_index operation on logstash-2014.12.28
2015-01-18 18:27:48,667 INFO      DRY RUN: of delete_index operation on logstash-2014.12.29
2015-01-18 18:27:48,667 INFO      DRY RUN: of delete_index operation on logstash-2014.12.30
2015-01-18 18:27:48,667 INFO      DRY RUN: of delete_index operation on logstash-2014.12.31
2015-01-18 18:27:48,667 INFO      DRY RUN: of delete_index operation on logstash-2015.01.01
2015-01-18 18:27:48,667 INFO      DRY RUN: of delete_index operation on logstash-2015.01.02
2015-01-18 18:27:48,667 INFO      DRY RUN: of delete_index operation on logstash-2015.01.03
2015-01-18 18:27:48,667 INFO      DRY RUN: of delete_index operation on logstash-2015.01.04
2015-01-18 18:27:48,668 INFO      DRY RUN: of delete_index operation on logstash-2015.01.05
2015-01-18 18:27:48,668 INFO      DRY RUN: of delete_index operation on logstash-2015.01.06
2015-01-18 18:27:48,668 INFO      DRY RUN: of delete_index operation on logstash-2015.01.07
2015-01-18 18:27:48,669 INFO      DRY RUN: of delete_index operation on logstash-2015.01.08
2015-01-18 18:27:48,669 INFO      DRY RUN: of delete_index operation on logstash-2015.01.09
2015-01-18 18:27:48,670 INFO      DRY RUN: of delete_index operation on logstash-2015.01.10
2015-01-18 18:27:48,670 INFO      DRY RUN: of delete_index operation on logstash-2015.01.11
2015-01-18 18:27:48,670 INFO      DRY RUN: of delete_index operation on logstash-2015.01.12
2015-01-18 18:27:48,671 INFO      DRY RUN: of delete_index operation on logstash-2015.01.13
2015-01-18 18:27:48,671 INFO      DRY RUN: of delete_index operation on logstash-2015.01.14
2015-01-18 18:27:48,671 INFO      DRY RUN: of delete_index operation on logstash-2015.01.15
2015-01-18 18:27:48,672 INFO      logstash-2015.01.16 is within the threshold period (3 days).
2015-01-18 18:27:48,673 INFO      logstash-2015.12.25 is within the threshold period (3 days).
2015-01-18 18:27:48,673 INFO      logstash-2015.12.27 is within the threshold period (3 days).
2015-01-18 18:27:48,673 INFO      logstash-2015.12.29 is within the threshold period (3 days).
2015-01-18 18:27:48,673 INFO      logstash-2015.12.30 is within the threshold period (3 days).
2015-01-18 18:27:48,673 INFO      logstash-2015.12.31 is within the threshold period (3 days).
2015-01-18 18:27:48,673 INFO      DRY RUN: Specified indices deleted.
2015-01-18 18:27:48,674 INFO      Done in 0:00:08.018128.
```

**Comment by poolski** [comment]
Yes, likewise... 

Odd.

**Comment by poolski** [comment]
#252 seems to be reporting something similar.

**Comment by untergeek** [comment]
#252 is an import error and is unrelated to this.

**Comment by mfyorp** [comment]
I have the same error messsage. --timeout has no effect, as the error appears almost instantly. Deleting by time does not give me that error. Anything other info I could provide or any other tests I could do?

**Comment by untergeek** [comment]
Please retry this with v3.

**Comment by mfyorp** [comment]
Works with v3.
In the mean time, the problem seems to be solved for me with 2.1.2 as well, strangely enough. Except for the regular debian updates, the only thing that changed is the amount of indices I have. Anyway, problem solved for me.

**Comment by untergeek** [comment]
Going to close this for now.  If issues persist, please feel free to re-open.

**Comment by djs52** [comment]
I believe this is the same issue, so I'm reopening. Seeing this with both 3 and 2.1.2 -- with debug, I eventually see the failed requests in the log:
```
2015-03-09 18:27:07,683 INFO      urllib3.connectionpool              _new_conn:203  Starting new HTTP connection (3): rockall-nfs
2015-03-09 18:27:07,686 WARNING            elasticsearch       log_request_fail:81   GET http://rockall-nfs:9200/logstash-2013.01.01,logstash-2013.01.02,logstash-2013.01.03,logstash-2013.01.04,logstash-2013.01.05,logstash-2013.01.06,logstash-2013.01.07,logstash-2013.08.13,logstash-2013.08.14,logstash-2013.08.15,logstash-2013.08.16,logstash-2013.08.17,logstash-2013.08.18,logstash-2013.08.19,logstash-2013.08.20,logstash-2013.08.21,logstash-2013.08.22,...
```
The request turns out to be about 6kb, which exceeds the `http.max_initial_line_length` setting in Elasticsearch (see http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/modules-http.html). Increasing this setting seems to allow curator to work.

**Comment by untergeek** [comment]
Your workaround is valid.  You have a huge number of indices.

Because this is coming from Elasticsearch, I have no way of addressing this directly.  @HonzaKral may know something about this I do not, as it comes from the elasticsearch-py module.

**Comment by HonzaKral** [comment]
I am afraid this is an issue with elasticsearch not allowing such long urls. The fix would be to use wildcards if possible or issue several requests in curator to make sure each one fits in the default limit.

**Comment by untergeek** [comment]
I may write in a way to check the length of the index list before acting, then.

**Comment by AlexeyKupershtokh** [comment]
I've seen this issue with curator 3.0.3.
The workaround with `http.max_initial_line_length: 16kb` fixed it.

**Comment by untergeek** [comment]
@AlexeyKupershtokh please share the conditions which led to this.  It should not be possible in 3.0.3 because of [line 112](https://github.com/elastic/curator/blob/master/curator/cli/index_selection.py#L112), which reads:

```python
if len(to_csv(working_list)) > 3072 and not ctx.parent.info_name == 'snapshot':
```

If it's bigger than 3072 bytes, it calls the [chunk_index](https://github.com/elastic/curator/blob/master/curator/cli/utils.py#L188-L208) method.  I chose this number because it seemed implausible to hit 4k with nearly 1k of room to breathe.  

What kind of call did this?  Did you have some extra URL parameters?  A really long url or extension?  Are your index names just huge? If I have to reduce this number further, I can.  I'd like some hard data to back it up, though.

**Comment by AlexeyKupershtokh** [comment]
So let's begin.
This is common system information:
```
wicked@f2p-logs:~$ cat /etc/issue
Ubuntu 12.04.3 LTS \n \l

wicked@f2p-logs:~$ /usr/local/bin/curator --version
curator, version 3.0.3

wicked@f2p-logs:~$ aptitude show elasticsearch
Package: elasticsearch                   
New: yes
State: installed
Automatically installed: no
Version: 1.5.0
Priority: optional
Section: web
Maintainer: Elasticsearch Team <info@elasticsearch.com>
Architecture: all
Uncompressed Size: 31,0 M
Depends: libc6, adduser
Description: Open Source, Distributed, RESTful Search Engine
...
```
And these are outputs:
Workaround enabled:
https://gist.github.com/AlexeyKupershtokh/b8c74b395a16c115f2e0#file-with-the-workaround-enabled

Workaround disabled:
https://gist.github.com/AlexeyKupershtokh/b8c74b395a16c115f2e0#file-without-the-workaround
And the corresponding elasticsearch log: https://gist.github.com/AlexeyKupershtokh/b8c74b395a16c115f2e0#file-errors-from-the-elasticsearch-log

**Comment by untergeek** [comment]
You're using the `--disk-space` flag. That's why this is getting triggered.  You have too many indices for the query for the delete by space, and I did not apply the logic to prevent over-sized lists of indices to that method.

Here's the offending line:

https://github.com/elastic/curator/blob/master/curator/api/filter.py#L337

It will need to be updated to batch the results in smaller chunks, then re-assemble them into a single array again.  I don't like having to add this (but I will to keep it from breaking) because it suggests a massive-scale usage of delete by space, which is NotGood™, for a variety of reasons, including the ones quoted below.  Please see: http://www.elastic.co/guide/en/elasticsearch/client/curator/current/delete.html#_deleting_indices_by_space

>**Deleting Indices By Space**
>
>This option is for those who want to retain indices based on disk consumption, rather than by a set number of days. There are some important caveats surrounding this choice.
>
>**Caveats**
>
>* Elasticsearch cannot calculate the size of closed indices. Elasticsearch does not keep tabs on how much disk-space closed indices consume. If you close indices, your space calculations will be inaccurate.
>* Indices consume resources just by existing. You could run into performance and/or operational snags in Elasticsearch as the count of indices climbs.
>* You need to manually calculate how much space across all nodes. The total you give will be the sum of all space consumed across all nodes in your cluster. If you use shard allocation to put more shards or indices on a single node, it will not affect the total space reported by the cluster, but you may still run out of space on that node.
>
>These are only a few of the caveats. This is still a valid use-case, especially for those running a single-node test box, however, so we include this option for your convenience.

Even if you change your shard allocation per node to be by space, you have no idea which indices will keep what shards on what nodes.  Deleting the "oldest" indices could free up space on 2 nodes, but leave several others completely full, which could result in a lot of extra shard reallocation just to balance the cluster.  

It is much wiser to use monitoring software to see what size _n_ days worth of indices can accommodate and then keep that many indices by time, rather than by space.

You also are feeding a list of both your `stage` and `production` indices to be acted on.  Delete by space will simply feed the indices alphabetically (or reverse, if that flag is chosen), as it comes after the other filters.  This means you could potentially delete entire indices you don't want to delete, and not free the space you actually care about.

While I will fix this, because I don't like the potential of this bug to keep coming up, the fact that you are hitting it is indicative of a potentially dangerous approach to index management.

**Comment by AlexeyKupershtokh** [comment]
Thank you for the thorough explanation. I've been using this approach just to make sure my single node won't fill. I don't like the situations when it stops writing, start losing newest data and require additional ops to recover from this state. So this is sensible choice: "hey, elasticsearch. just make sure you always have some space". The other caveats you listed seems acceptable in my case.

But I should probably change it to another approach that would delete the oldest indexes only:
```
n = 100;
while (free space < 1 gb and n > 0) {
    curator delete indices --older-than $n --time-unit days --timesting "%Y.%m.%d"
    n--;
}
```

Though I wonder what else approaches could be used to automatically free space in cluster environments with many index series (like stage and prod multiplied by different projects writing logs) ?

**Comment by untergeek** [comment]
> I don't like situations when it stops writing, start losing newest data and require additional ops to recover from this state.

This actually results more often from having too many shards per node, rather than too much data on the server.  See https://github.com/elastic/curator/pull/201#issuecomment-59767589

> I can't tell you exactly when that will be with your data and usage pattern, but I will point out that by default, an ES data node will set aside 10% of the heap for indexing (caching, operations, etc.). Each active shard will want no less than 250M of that space. Each inactive shard will want no less than 4MB of that space. Elasticsearch will still force the division to result in values lower than those numbers in the event that this heap space becomes more crowded. If it pushes too far, you will be unable to index. The only way out when this happens is to delete or close indices and usually a node restart. If you need indices to persist beyond this, your options are one or more of the following: a) bigger heap [not to exceed 31G per node], b) closing infrequently accessed indices, c) adding more nodes to the system to rebalance shard count per node.

You have one node.  If you are using the default number of shards per index, which is 5, you have 5 shards multiplied by a rather large number of indices.  You are likely putting a great deal of pressure on that 10% of the heap, perhaps even to the point that it will, as mentioned, stop indexing altogether, until Elasticsearch is restarted.  Any production, time-series use of Elasticsearch should be prepared to be extended horizontally by adding more nodes as needed.  This is the other reason why delete by space is NotGood™, because Elasticsearch should be spread across multiple nodes.

**Comment by untergeek** [comment]
> Though I wonder what else approaches could be used to automatically free space in cluster environments with many index series (like stage and prod multiplied by different projects writing logs) ?

This is why deleting by time and filtering by prefix is available in Curator.  You can easily keep _n_ days of staging indices, and _x_ days of production indices in this way.
