### ISSUE TITLE
Optimize on an index with unallocated primaries causes stacktrace 

### ISSUE THREAD

**Issue by jjfalling** [elastic/curator#332]
Curator (3.0.3) tried to optimize an index with no active primary shards and got the following:

 
	2015-03-30 05:43:22,543 DEBUG         urllib3.util.retry               from_int:155  Converted retries value: False -> Retry(total=False, connect=None, read=None, redirect=0)
	2015-03-30 05:43:22,545 DEBUG     urllib3.connectionpool          _make_request:383  "GET /logstash-2015.03.21/_segments HTTP/1.1" 200 62
	2015-03-30 05:43:22,545 INFO               elasticsearch    log_request_success:62   GET http://localhost:9200/logstash-2015.03.21/_segments [status:200 request:0.002s]
	2015-03-30 05:43:22,546 DEBUG              elasticsearch    log_request_success:64   > None
	2015-03-30 05:43:22,546 DEBUG              elasticsearch    log_request_success:65   < {"_shards":{"total":3,"successful":0,"failed":0},"indices":{}}
	2015-03-30 05:43:22,546 INFO         elasticsearch.trace    log_request_success:72   curl -XGET 'http://localhost:9200/logstash-2015.03.21/_segments?pretty' -d ''
	2015-03-30 05:43:22,547 DEBUG        elasticsearch.trace    log_request_success:75   #[200] (0.002s)
	#{
	#  "_shards": {
	#    "failed": 0,
	#    "successful": 0,
	#    "total": 3
	#  },
	#  "indices": {}
	#}
	Traceback (most recent call last):
	  File "/usr/bin/curator", line 9, in <module>
		load_entry_point('elasticsearch-curator==3.0.3', 'console_scripts', 'curator')()
	  File "/usr/lib/python2.7/site-packages/curator/curator.py", line 5, in main
		cli( obj={ "filters": [] } )
	  File "/usr/lib/python2.7/site-packages/click/core.py", line 610, in __call__
		return self.main(*args, **kwargs)
	  File "/usr/lib/python2.7/site-packages/click/core.py", line 590, in main
		rv = self.invoke(ctx)
	  File "/usr/lib/python2.7/site-packages/click/core.py", line 936, in invoke
		return _process_result(sub_ctx.command.invoke(sub_ctx))
	  File "/usr/lib/python2.7/site-packages/click/core.py", line 936, in invoke
		return _process_result(sub_ctx.command.invoke(sub_ctx))
	  File "/usr/lib/python2.7/site-packages/click/core.py", line 782, in invoke
		return  ctx.invoke(self.callback, **ctx.params)
	  File "/usr/lib/python2.7/site-packages/click/core.py", line 416, in invoke
		return callback(*args, **kwargs)
	  File "/usr/lib/python2.7/site-packages/curator/cli/index_selection.py", line 122, in indices
		retval = do_command(client, ctx.parent.info_name, working_list, ctx.parent.params)
	  File "/usr/lib/python2.7/site-packages/curator/cli/utils.py", line 228, in do_command
		delay=params['delay'], request_timeout=params['request_timeout']
	  File "/usr/lib/python2.7/site-packages/curator/api/optimize.py", line 50, in optimize
		request_timeout=request_timeout
	  File "/usr/lib/python2.7/site-packages/curator/api/optimize.py", line 19, in optimize_index
		if optimized(client, index_name, max_num_segments):
	  File "/usr/lib/python2.7/site-packages/curator/api/utils.py", line 133, in optimized
		shards, segmentcount = get_segmentcount(client, index_name)
	  File "/usr/lib/python2.7/site-packages/curator/api/utils.py", line 106, in get_segmentcount
		shards = client.indices.segments(index=index_name)['indices'][index_name]['shards']
	KeyError: u'logstash-2015.03.21'

**Comment by untergeek** [comment]
Interesting.  This is obviously an edge case.  An index with no active primary shards is not something the every-day user is likely to encounter.

What kind of resolution would you like to see?

**Comment by untergeek** [comment]
This is a severe edge case.  @jjfalling and I discussed this in the Elastic HipChat privately.  While catching this _can_ be done, it is perhaps worthwhile to leave the full stack trace to show what's going on.

If the scenario which has the index with no active primaries is limited to that one index, Curator now provides a way to re-run the command and exclude that index:

`--exclude logstash-2015.03.21`

Again, this is an extremely uncommon situation.  The verbose stack-trace log is appropriate here, so no changes will be made at this time.
