### ISSUE TITLE
possibly erroneous handling of timestrings without year (Curator 2.1.1)

### ISSUE THREAD

**Issue by hronecviktor** [elastic/curator#347]
I believe I might have found a bug related to timestring handling. Ran this command with a belief that only indices older than 4 days would be deleted, and it started deleting all of them up to the point of execution. I really should have made a `dry-run`.
The year being in `prefix` rather than the `timestring` seems to be the problem as this worked without any issues

    curator delete --older-than 4 --prefix "jmsgw-" --timestring "%Y-%m-%d-%H"

Transcript:

	root@zabbix3:/var/log/nxlog# curator delete --older-than 4 --prefix "jmsgw-2015-" --timestring "%m-%d-%H"
	2015-04-14 11:08:35,414 INFO      Job starting...
	2015-04-14 11:08:35,417 INFO      Deleting indices...
	2015-04-14 11:08:35,470 INFO      delete_index operation succeeded on jmsgw-2015-04-11-00
	2015-04-14 11:08:35,573 INFO      delete_index operation succeeded on jmsgw-2015-04-13-09
	2015-04-14 11:08:35,706 INFO      delete_index operation succeeded on jmsgw-2015-04-13-10
	2015-04-14 11:08:35,789 INFO      delete_index operation succeeded on jmsgw-2015-04-13-11
	2015-04-14 11:08:35,885 INFO      delete_index operation succeeded on jmsgw-2015-04-13-12
	2015-04-14 11:08:35,958 INFO      delete_index operation succeeded on jmsgw-2015-04-13-13
	2015-04-14 11:08:36,097 INFO      delete_index operation succeeded on jmsgw-2015-04-13-14
	2015-04-14 11:08:36,209 INFO      delete_index operation succeeded on jmsgw-2015-04-13-15
	2015-04-14 11:08:36,313 INFO      delete_index operation succeeded on jmsgw-2015-04-13-16
	2015-04-14 11:08:36,350 INFO      delete_index operation succeeded on jmsgw-2015-04-13-17
	2015-04-14 11:08:36,374 INFO      delete_index operation succeeded on jmsgw-2015-04-13-18
	2015-04-14 11:08:36,394 INFO      delete_index operation succeeded on jmsgw-2015-04-13-19
	2015-04-14 11:08:36,414 INFO      delete_index operation succeeded on jmsgw-2015-04-13-20
	2015-04-14 11:08:36,434 INFO      delete_index operation succeeded on jmsgw-2015-04-13-21
	2015-04-14 11:08:36,512 INFO      delete_index operation succeeded on jmsgw-2015-04-13-22
	2015-04-14 11:08:36,573 INFO      delete_index operation succeeded on jmsgw-2015-04-13-23
	2015-04-14 11:08:36,702 INFO      delete_index operation succeeded on jmsgw-2015-04-14-00
	2015-04-14 11:08:36,771 INFO      delete_index operation succeeded on jmsgw-2015-04-14-01
	2015-04-14 11:08:36,787 INFO      delete_index operation succeeded on jmsgw-2015-04-14-02
	2015-04-14 11:08:36,805 INFO      delete_index operation succeeded on jmsgw-2015-04-14-03
	2015-04-14 11:08:36,945 INFO      delete_index operation succeeded on jmsgw-2015-04-14-04
	2015-04-14 11:08:37,023 INFO      delete_index operation succeeded on jmsgw-2015-04-14-05
	2015-04-14 11:08:37,126 INFO      delete_index operation succeeded on jmsgw-2015-04-14-06
	2015-04-14 11:08:37,205 INFO      delete_index operation succeeded on jmsgw-2015-04-14-07
	2015-04-14 11:08:37,268 INFO      delete_index operation succeeded on jmsgw-2015-04-14-08
	2015-04-14 11:08:37,333 INFO      delete_index operation succeeded on jmsgw-2015-04-14-09
	2015-04-14 11:08:37,417 INFO      delete_index operation succeeded on jmsgw-2015-04-14-10
	^CTraceback (most recent call last):
	  File "/usr/local/bin/curator", line 9, in <module>
	    load_entry_point('elasticsearch-curator==2.1.1', 'console_scripts', 'curator')()
	  File "/usr/local/lib/python2.7/dist-packages/elasticsearch_curator-2.1.1-py2.7.egg/curator/curator_script.py", line 364, in main
	    arguments.func(client, **argdict)
	  File "/usr/local/lib/python2.7/dist-packages/elasticsearch_curator-2.1.1-py2.7.egg/curator/curator.py", line 1004, in delete
	    _op_loop(client, matching_indices, op=delete_index, dry_run=dry_run, **kwargs)
	  File "/usr/local/lib/python2.7/dist-packages/elasticsearch_curator-2.1.1-py2.7.egg/curator/curator.py", line 746, in _op_loop
	    skipped = op(client, item, **kwargs)
	  File "/usr/local/lib/python2.7/dist-packages/elasticsearch_curator-2.1.1-py2.7.egg/curator/curator.py", line 589, in delete_index
	    client.indices.delete(index=index_name)
	  File "/usr/local/lib/python2.7/dist-packages/elasticsearch-1.4.0.dev-py2.7.egg/elasticsearch/client/utils.py", line 68, in _wrapped
	    return func(*args, params=params, **kwargs)
	  File "/usr/local/lib/python2.7/dist-packages/elasticsearch-1.4.0.dev-py2.7.egg/elasticsearch/client/indices.py", line 188, in delete
	    params=params)
	  File "/usr/local/lib/python2.7/dist-packages/elasticsearch-1.4.0.dev-py2.7.egg/elasticsearch/transport.py", line 307, in perform_request
	    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
	  File "/usr/local/lib/python2.7/dist-packages/elasticsearch-1.4.0.dev-py2.7.egg/elasticsearch/connection/http_urllib3.py", line 67, in perform_request
	    response = self.pool.urlopen(method, url, body, retries=False, headers=self.headers, **kw)
	  File "/usr/local/lib/python2.7/dist-packages/urllib3-1.8.3-py2.7.egg/urllib3/connectionpool.py", line 496, in urlopen
	    body=body, headers=headers)
	  File "/usr/local/lib/python2.7/dist-packages/urllib3-1.8.3-py2.7.egg/urllib3/connectionpool.py", line 322, in _make_request
	    httplib_response = conn.getresponse(buffering=True)
	  File "/usr/lib/python2.7/httplib.py", line 1034, in getresponse
	    response.begin()
	  File "/usr/lib/python2.7/httplib.py", line 407, in begin
	    version, status, reason = self._read_status()
	  File "/usr/lib/python2.7/httplib.py", line 365, in _read_status
	    line = self.fp.readline()
	  File "/usr/lib/python2.7/socket.py", line 447, in readline
	    data = self._sock.recv(self._rbufsize)
	KeyboardInterrupt 
	root@zabbix3:/var/log/nxlog# date
	Tue Apr 14 11:09:00 CEST 2015
	root@zabbix3:/var/log/nxlog# curator --version
	curator 2.1.1
	root@zabbix3:/var/log/nxlog# curl localhost:9200
	{
	  "status" : 200,
	  "name" : "Kaluu",
	  "cluster_name" : "elasticsearch",
	  "version" : {
	    "number" : "1.4.1",
	    "build_hash" : "89d3241d670db65f994242c8e8383b169779e2d4",
	    "build_timestamp" : "2014-11-26T15:49:29Z",
	    "build_snapshot" : false,
	    "lucene_version" : "4.10.2"
	  },
	  "tagline" : "You Know, for Search"
	}
	root@zabbix3:/var/log/nxlog# uname -a
	Linux zabbix3 3.2.0-4-amd64 #1 SMP Debian 3.2.51-1 x86_64 GNU/Linux

**Comment by untergeek** [comment]
Curator v3 likely fixes this as the `--prefix` is no longer forced to be "everything leading up to the date" portion of an index name.  In fact, v3 can support any number of different index naming styles now, not just time-series indices.  v3 is also much more thoroughly tested to prevent this sort of thing from happening, including command-line level integration testing of various options.

The fix is to upgrade to v3.  Bear in mind that the command-line syntax is different from v2.  Be sure to read the [documentation](http://www.elastic.co/guide/en/elasticsearch/client/curator/current/index.html)

I will keep this open for another day or two to allow you to upgrade and test, but re-do the title to indicate the problem is with Curator v2.

**Comment by hronecviktor** [comment]
Alright, after some minor confusion with the subcommands in v3 we successfuly migrated. Thanks ^^
