### ISSUE TITLE
curator unable to find snapshots causing stack trace

### ISSUE THREAD

**Issue by teknogeek0** [elastic/curator#374]
Hi there,
  Long story, but I recently found that using S3 lifecycle policies to rotate data to Glacier was breaking curator's ability to upload snapshots to S3. In trying to rectify this I upgraded to 3.0.3, deleted my snapshot repository in elasticsearch, and recreated it. Now when I try and run the snapshot command, I am getting the following stack trace:

````
/usr/local/bin/curator --timeout 21600 snapshot --ignore_unavailable --repository <repo> --prefix snapshot-curator- indices --time-unit days --older-than 2 --timestring '%Y.%m.%d'
2015-05-20 17:08:24,677 INFO      Job starting: snapshot indices
2015-05-20 17:08:26,081 INFO      Snapshot name: snapshot-curator-20150520170826
2015-05-20 17:08:26,170 ERROR     Unable to find all snapshots in repository: <repo>
Traceback (most recent call last):
  File "/usr/local/bin/curator", line 9, in <module>
    load_entry_point('elasticsearch-curator==3.0.3', 'console_scripts', 'curator')()
  File "/usr/local/lib/python2.7/dist-packages/curator/curator.py", line 5, in main
    cli( obj={ "filters": [] } )
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 664, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 644, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 991, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 991, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 837, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 464, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/curator/cli/index_selection.py", line 122, in indices
    retval = do_command(client, ctx.parent.info_name, working_list, ctx.parent.params)
  File "/usr/local/lib/python2.7/dist-packages/curator/cli/utils.py", line 240, in do_command
    request_timeout=params['request_timeout'],
  File "/usr/local/lib/python2.7/dist-packages/curator/api/snapshot.py", line 57, in create_snapshot
    if name in all_snaps:
TypeError: argument of type 'bool' is not iterable
````

Why would curator's not finding old snapshots matter in this case? Attempting to display current snapshots results in lovely red text telling me that I have none:
````
curator show snapshots --repository <repo> --all-snapshots
2015-05-20 17:14:06,912 INFO      Job starting: show snapshots
2015-05-20 17:14:07,215 ERROR     Unable to find all snapshots in repository: <repo>
(RED)ERROR. No snapshots found in Elasticsearch.(RED)
````

Trying to see if there is any way to get past this, as well as to make my old snapshots visible again to the cluster.

Thanks.

**Comment by untergeek** [comment]
Some kind of metadata seems to have been lost.  Could you re-run both commands with the `--debug` flag?  The results will reveal more.

**Comment by untergeek** [comment]
By way of explanation, Curator must check for existing snapshots so it is certain to not try to create a snapshot with the same name as an existing snapshot.  The fact that Curator cannot find the snapshots indicates not that there are no snapshots present (which it would detect and then happily create snapshots), but that it cannot get snapshots for some reason.  This is why I suggest that some metadata may have been deleted, corrupted or otherwise munged.

**Comment by teknogeek0** [comment]
Thanks untergeek, will give that try. Just curious, where might this metadata live? Is it in ElasticSearch now, or is it data that might be in my S3 bucket already? I'm happy to just wack both and re-snapshot as the cluster is new-ish and contains all its data still.

Thanks for the quick reply btw!
- Chris

**Comment by untergeek** [comment]
That's actually a tricky question.  It will be in the data path of your elasticsearch cluster on each of your nodes.  I cannot think of a clean way to delete/purge it without deleting all of your data.  That might be a good question to ask in the https://discuss.elastic.co forums.

**Comment by teknogeek0** [comment]
Great, thanks again!

**Comment by teknogeek0** [comment]
About 10 days after I posted this I ended up rebuilding my cluster, and while I didn't completely tear down old indexes or data(more of an in-place host exchange), moving to new independent ElasticSearch masters seemed to, somehow, make this work again(or maybe its unrelated). Closing for now as I can't recreate at the moment.
