### ISSUE TITLE
'Error deleting one or more indices' - but no reason given

### ISSUE THREAD

**Issue by derjohn** [elastic/curator#387]
Hello,
deleting indexes by time throws me an error. I can maually delete the indexes with e.g. kopf web-GUI. Even with debug level I don't see why it's happening.

```
usr/local/bin/curator --logfile /tmp/cura --loglevel debug delete indices --older-than 3 --timestring '%Y.%m.%d' --time-unit days --prefix XXXXXX
```
.....
2015-05-22 09:35:58,682 INFO      ---deleting index XXXXXXX-2015.05.08
2015-05-22 09:36:28,714 ERROR     Error deleting one or more indices.  Check logs for more information.
2015-05-22 09:36:28,714 WARNING   Job did not complete successfully.
(END)

```
/usr/local/bin/curator --version
curator, version 3.1.0
```

**Comment by untergeek** [comment]
`--loglevel debug` should be replaced with `--debug` to get all of the upstream messages from the Elasticsearch module.  Not sure why `--loglevel debug` is not showing more, but there should be tons and tons of logs spewing.

Also, you should look at your Elasticsearch logs to see if errors are in there.

**Comment by derjohn** [comment]
Hi,
I had to wait until the error is back. Now it is :)

The is the (shortened) output of the curator with --debug. 

2015-05-26 09:12:32,614 DEBUG     curator.cli.index_selection                indices:79   Filter: {'pattern': '^XXXXX.*debug.*$'}
2015-05-26 09:12:32,615 INFO      curator.cli.index_selection                indices:83   Pruning Kibana-related indices to prevent accidental deletion.
2015-05-26 09:12:32,615 DEBUG     curator.cli.index_selection                indices:110  ACTION: delete. INDICES: [u'XXXXX-cassandra-debug-2015.05.20', (many indexes).......
2015-05-26 09:12:32,615 INFO          curator.api.delete         delete_indices:17   Deleting indices as a batch operation:
2015-05-26 09:12:32,615 INFO          curator.api.delete         delete_indices:19   ---deleting index XXXXX-cassandra-debug-2015.05.20
[...]
2015-05-26 09:12:32,626 DEBUG         urllib3.util.retry               from_int:155  Converted retries value: False -> Retry(total=False, connect=None, read=None, redirect=0)
2015-05-26 09:13:02,654 WARNING            elasticsearch       log_request_fail:82   DELETE http://localhost:9200/XXXXX-cassandra-debug-2015.05.20,............(many indexes)....[status:N/A request:30.028s]

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/connection/http_urllib3.py", line 74, in perform_request
    response = self.pool.urlopen(method, url, body, retries=False, headers=self.headers, **kw)
  File "/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 597, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python2.7/dist-packages/urllib3/util/retry.py", line 222, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 544, in urlopen
    body=body, headers=headers)
  File "/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 376, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 304, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
ReadTimeoutError: HTTPConnectionPool(host=u'localhost', port=9200): Read timed out. (read timeout=30)
2015-05-26 09:13:02,660 DEBUG              elasticsearch       log_request_fail:90   > None
2015-05-26 09:13:02,660 ERROR         curator.api.delete         delete_indices:23   Error deleting one or more indices.  Check logs for more information.
2015-05-26 09:13:02,660 WARNING        curator.cli.utils               exit_msg:69   Job did not complete successfully.

"Read timed out" ==> ? Might this be caused by an out of threads or such in ES ? I'll ty to  raise --timeout. 

But: It would be nice, if curator tells by default the cause of the error, if the cause is an timeout.

rgds,
j

**Comment by untergeek** [comment]
This kind of timeout can happen when ES is heavily overburdened.  In this case, it appears you're trying to delete many indices at once (could you elaborate? provide an approximate count?), which may contribute to that overburdening.  An increased timeout value will likely help with this.  Reducing the number of indices being deleted simultaneously might also help.  This could be accomplished by reducing the time window (`--older-than X`, and slowly reduce X until it is the desired number).

If you hardly have any indices (seeing that you're deleting older than 3), this might also indicate an overburdened cluster (or single node).

As far as reporting the error goes, I made a deliberate choice not to complicate the code here.  Trying to capture one of multiple potential errors here, and responding correctly to each kind, is a lot of extra code for each method making calls–especially when trying to make both Python 2.x and 3.x play nice with the same code base.  Since `--debug` output will show the actual error, I leave it to the end user to use `--debug` when they hit errors.

**Comment by untergeek** [comment]
I will make an issue to suggest using the `--debug` flag in these error messages.

**Comment by derjohn** [comment]
Hello,
yes, I do have a lot of indexes, currently more than ~200 indexes:
  elkelastic-1:~# curl -s 'localhost:9200/_cat/indices' | wc -l ==> 217

I run the curator cleanup each night, that should delete ~ 7-14 Indexes each day.

This is not on single node, but a cluster consisting of 7 ES nodes with 30 GB RAM and SSD only, about 1.5TB indexes (3TB with replicas). The clusterstate is green, we have sometimes slow average query times, but not that slow, still expressable in low numbers of unit ms :)

And again: The strange thing is, that I was able to delete the indexes one by one with e.g. the kopf plugin without any problems.

I played with the timeout a littlebit and it looks like with more than 60 secs it works. Could that have to to with the fact that we use "index.refresh_interval": "60s" ? Might there we somekind of delay "I give you an ack only after the refresh was done" ?

rgds,
j

**Comment by untergeek** [comment]
Deleting one by one would not be a problem.  If it is it _really_ indicates something wrong with your cluster.

Deleting _en masse_ is what's enabled by default now, as doing it one by one actually can cause more headache for the cluster, as it needs to figure out how to rebalance shards.  If it takes more time for you to get a sane cluster state, then a higher timeout should be the solution.  

This _may_ have to do with your refresh interval.  This interval is actually counter-productive.  On of our top Lucene committers did some performance tests and found that refresh intervals longer than 10s did not help, and actually slowed things down.  The sweet spot is between 1s and 10s in nearly every scenario he created, at high and low indexing volumes.  I recommend going back to at least 10s, if not the 5s that Logstash defaults to.

**Comment by derjohn** [comment]
I'll wait for Recommend re-running with --debug on errors #390.
