### ISSUE TITLE
Updated to curator 3.2 and closing indices gives me the following error

### ISSUE THREAD

**Issue by Rumbles** [elastic/curator#429]
I've just updated curator and tried to close some indices with it to test it's functionality (because of the new command syntax from the old version I was on) and I get the following error:

```
# curator close indices --time-unit days --older-than 10 --timestring %Y.%m.%d --prefix logstash
2015-07-10 11:59:24,479 INFO      Job starting: close indices
2015-07-10 11:59:24,703 INFO      Skipping index logstash-2015.06.26: Closed.
2015-07-10 11:59:24,857 INFO      Skipping index logstash-2015.06.27: Closed.
2015-07-10 11:59:25,021 INFO      Skipping index logstash-2015.06.28: Closed.
2015-07-10 11:59:25,181 INFO      Skipping index logstash-2015.06.29: Closed.
2015-07-10 11:59:25,342 INFO      Skipping index logstash-2015.06.30: Closed.
2015-07-10 11:59:25,346 WARNING   Non-fatal error encountered.
Traceback (most recent call last):
  File "/usr/bin/curator", line 9, in <module>
    load_entry_point('elasticsearch-curator==3.2.0', 'console_scripts', 'curator')()
  File "/usr/lib/python2.6/site-packages/curator/curator.py", line 5, in main
    cli( obj={ "filters": [] } )
  File "/usr/lib/python2.6/site-packages/click/core.py", line 664, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/click/core.py", line 644, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.6/site-packages/click/core.py", line 991, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.6/site-packages/click/core.py", line 991, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.6/site-packages/click/core.py", line 837, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.6/site-packages/click/core.py", line 464, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/curator/cli/index_selection.py", line 132, in indices
    retval = do_command(client, ctx.parent.info_name, working_list, ctx.parent.params)
  File "/usr/lib/python2.6/site-packages/curator/cli/utils.py", line 217, in do_command
    return close(client, indices)
  File "/usr/lib/python2.6/site-packages/curator/api/close.py", line 38, in close
    return close_indices(client, indices)
  File "/usr/lib/python2.6/site-packages/curator/api/close.py", line 19, in close_indices
    seal_indices(client, indices)
  File "/usr/lib/python2.6/site-packages/curator/api/seal.py", line 27, in seal_indices
    logger.debug('Error: {0}.  Message: {1}'.format(e.status_code, e.error))
AttributeError: 'exceptions.AttributeError' object has no attribute 'status_code'
```

I believe all the indices should have already been closed by a cron job and the old curator last night, so I guess that could be partly responsible? I'm hoping you guys will be able t give me some more info! If you need any more information from my side please let me know!

I'm running the following version of ES on CentOS 6 (from the ES repo):

elasticsearch-1.6.0-1.noarch

**Comment by untergeek** [comment]
This is a bug.  You've encountered an error I have not anticipated.

The flow here is that when you send a command to close indices, and you are using Elasticsearch 1.6+, it will try to seal (synced flush) open indices before closing them.  

What's happened is that, in trying to seal an index, Curator got an AttributeError exception, where I only ever anticipated TransportError exceptions.  I cannot explain why you received an AttributeError exception, however.  That sounds like something else is going on.  Better error-type capturing will allow me to display the results of the AttributeError.

Are _all_ nodes in your cluster running 1.6.0?  Are your logstash instances using the node protocol, or the http protocol?  If node, it means that not all of your cluster is running ES 1.6+ (as Logstash's client node is still probably ES 1.5-ish, depending on what version of Logstash you're using.  That's my current stab in the dark.

**Comment by Rumbles** [comment]
It's a single node cluster, my ES output uses the http protocol

Also I am using logstash-1.5.1-1 in case it's important!

**Comment by untergeek** [comment]
Curator 3.2.1 was just released, and it should at least show a better error for this case.  Please test it and let me know what you find.

**Comment by Rumbles** [comment]
As discussed in IRC, I ran in to the following issue when running the update http://pastebin.centos.org/30266/

**Comment by untergeek** [comment]
That issue has nothing to do with the one raised.  A recent change to the `pbr` python module has broken `mock`, and this has caused a chain of failures.  I will investigate changing the dependencies to get around this, at least until it's resolved.

**Comment by untergeek** [comment]
Actually, it's not the `pbr` module that's causing problems.  It's `mock` itself: They officially dropped support for Python 2.6 https://github.com/testing-cabal/mock/commit/8a2e8709502c30e2dd0838125bc5c34fec35f451

As a significant number of Curator users are on RHEL/CentOS versions which are stuck on 2.6, this presents a problem.  I will pin mock to 1.0.1 as a result.

**Comment by Rumbles** [comment]
Hi,

I have installed curator from the repo provided here:

https://www.elastic.co/guide/en/elasticsearch/client/curator/current/installation.html#yum-repository

I now have 3.2.2 installed and it appears to be working perfectly.

If I have any further troubles I will raise a fresh issue, thanks for the help!

**Comment by untergeek** [comment]
I'd love to see what error came out, if you got an Exception with closing indices during the seal operation (supposed to be non-fatal with seal/synced flush).  Thanks for the update that all is working for you.

**Comment by romale** [comment]
# curator --version
curator, version 3.2.3

# curator close indices --time-unit days --older-than 30 --timestring %Y.%m.%d --prefix logstash-netflow5-
2015-07-17 15:10:53,069 INFO      Job starting: close indices
2015-07-17 15:11:27,084 WARNING   Non-fatal error encountered.
Traceback (most recent call last):
  File "/usr/bin/curator", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/site-packages/curator/curator.py", line 5, in main
    cli( obj={ "filters": [] } )
  File "/usr/lib/python2.7/site-packages/click/core.py", line 664, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 644, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 991, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/site-packages/click/core.py", line 991, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/site-packages/click/core.py", line 837, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 464, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/curator/cli/index_selection.py", line 148, in indices
    retval = do_command(client, ctx.parent.info_name, working_list, ctx.parent.params, master_timeout)
  File "/usr/lib/python2.7/site-packages/curator/cli/utils.py", line 217, in do_command
    return close(client, indices)
  File "/usr/lib/python2.7/site-packages/curator/api/close.py", line 38, in close
    return close_indices(client, indices)
  File "/usr/lib/python2.7/site-packages/curator/api/close.py", line 19, in close_indices
    seal_indices(client, indices)
  File "/usr/lib/python2.7/site-packages/curator/api/seal.py", line 37, in seal_indices
    fails = [ i for i in sorted(results) if results[i]['failed'] > 0 ]
TypeError: sequence index must be integer, not 'str'

With 'show' it's Ok:
# curator show indices --time-unit days --older-than 30 --timestring %Y.%m.%d --prefix logstash-netflow5-
2015-07-17 15:13:22,586 INFO      Job starting: show indices
2015-07-17 15:13:23,681 INFO      Matching indices:
logstash-netflow5-2015.05.19
logstash-netflow5-2015.05.20
logstash-netflow5-2015.05.21
logstash-netflow5-2015.05.22
logstash-netflow5-2015.05.23
logstash-netflow5-2015.05.24
logstash-netflow5-2015.05.25
logstash-netflow5-2015.05.26
logstash-netflow5-2015.05.27
logstash-netflow5-2015.05.28
logstash-netflow5-2015.05.29
logstash-netflow5-2015.05.30
logstash-netflow5-2015.05.31
logstash-netflow5-2015.06.01
logstash-netflow5-2015.06.02
logstash-netflow5-2015.06.03
logstash-netflow5-2015.06.04
logstash-netflow5-2015.06.06
logstash-netflow5-2015.06.07
logstash-netflow5-2015.06.08
logstash-netflow5-2015.06.09
logstash-netflow5-2015.06.10
logstash-netflow5-2015.06.11
logstash-netflow5-2015.06.12
logstash-netflow5-2015.06.13
logstash-netflow5-2015.06.14
logstash-netflow5-2015.06.15
logstash-netflow5-2015.06.16
logstash-netflow5-2015.06.17

# rpm -qi elasticsearch
Name        : elasticsearch
Version     : 1.6.0
Release     : 1
Architecture: noarch
Install Date: Thu 11 Jun 2015 03:42:33 PM MSK
Group       : Application/Internet
Size        : 31223901
License     : (c) 2009
Signature   : RSA/SHA1, Tue 09 Jun 2015 04:41:31 PM MSK, Key ID d27d666cd88e42b4
Source RPM  : elasticsearch-1.6.0-1.src.rpm
Build Date  : Tue 09 Jun 2015 04:41:28 PM MSK
Build Host  : ip-10-249-14-148.us-west-2.compute.internal
Relocations : /usr 
Packager    : Elasticsearch
Summary     : elasticsearch
Description :
Elasticsearch - Open Source, Distributed, RESTful Search Engine

**Comment by untergeek** [comment]
Is every node in your cluster running Elasticsearch 1.6 or higher?

The error:
```
fails = [ i for i in sorted(results) if results[i]['failed'] > 0 ]
TypeError: sequence index must be integer, not 'str'
```
Means that `results[i]` is not a dictionary object, but a list, for some reason.  I'd like to know why.

Please run `curator --debug close indices --time-unit days --older-than 30 --timestring %Y.%m.%d --prefix logstash-netflow5-` and attach the results.

**Comment by romale** [comment]
i've two nodes, and yes both is 1.6 versions.
I will try your command after sync finishing. Now, it's in progress)

**Comment by romale** [comment]
p.s. With this commands it was worked:
curator close indices --time-unit days --older-than 30 --newer-than 43 --timestring %Y.%m.%d --prefix logstash-netflow5-
curator close indices --time-unit days --older-than 42 --newer-than 61 --timestring %Y.%m.%d --prefix logstash-netflow5-

**Comment by untergeek** [comment]
@romale, because the error you are getting is different from the one in this closed issue, please open a new issue.

And I think I know what is happening, as you were taking a huge chunk of indices, but it worked with a smaller one.  It looks like I'll need to add the `master_timeout` flag to the `seal` command.
