### ISSUE TITLE
sre_constants.error: bogus escape: '\\2'

### ISSUE THREAD

**Issue by gzcf** [elastic/curator#435]
run

```
curator --port 9700 show indices --prefix logstash --time-unit days --timestring "2015.07.14" --older-than 3
```

It printed error:

```
2015-07-14 15:45:49,600 INFO      Job starting: show indices
Traceback (most recent call last):
  File "/opt/pyenv.quant/bin/curator", line 11, in <module>
    sys.exit(main())
  File "/opt/pyenv.quant/local/lib/python2.7/site-packages/curator/curator.py", line 5, in main
    cli( obj={ "filters": [] } )
  File "/opt/pyenv.quant/local/lib/python2.7/site-packages/click/core.py", line 664, in __call__
    return self.main(*args, **kwargs)
  File "/opt/pyenv.quant/local/lib/python2.7/site-packages/click/core.py", line 644, in main
    rv = self.invoke(ctx)
  File "/opt/pyenv.quant/local/lib/python2.7/site-packages/click/core.py", line 991, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/pyenv.quant/local/lib/python2.7/site-packages/click/core.py", line 991, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/pyenv.quant/local/lib/python2.7/site-packages/click/core.py", line 837, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/pyenv.quant/local/lib/python2.7/site-packages/click/core.py", line 464, in invoke
    return callback(*args, **kwargs)
  File "/opt/pyenv.quant/local/lib/python2.7/site-packages/curator/cli/index_selection.py", line 80, in indices
    working_list = apply_filter(working_list, **f)
  File "/opt/pyenv.quant/local/lib/python2.7/site-packages/curator/api/filter.py", line 114, in apply_filter
    p = re.compile(pattern)
  File "/opt/pyenv.quant/lib/python2.7/re.py", line 190, in compile
    return _compile(pattern, flags)
  File "/opt/pyenv.quant/lib/python2.7/re.py", line 244, in _compile
    raise error, v # invalid expression
sre_constants.error: bogus escape: '\\2'
```

when I removed `--older-than 3`, it worked well.

curator, version 3.2.2
OS: Ubuntu 14.04.1 LTS (GNU/Linux 3.13.0-27-generic x86_64)

**Comment by untergeek** [comment]
Your timestring is improperly formatted.  It's supposed to be a python strftime string, not an actual date.

Please see the [`--timestring` documentation](https://www.elastic.co/guide/en/elasticsearch/client/curator/current/timestring.html) for more information.

**Comment by gzcf** [comment]
@untergeek I misunderstood `--timestring`. Thank you for help!

**Comment by untergeek** [comment]
Closing...
