### ISSUE TITLE
Curator throws TransportError before it reaches timeout and finishes taking snapshot within the timeout

### ISSUE THREAD

**Issue by rhealitycheck** [elastic/curator#457]
Hi so I'm on curator 3.2.3 which I believe is the most current. And I'm facing an issue where it raises a TransportError but it eventually finishes taking the snapshot within the requested timeout period. So why is this being raised before the timeout and how can I actually look at the more granular errors being thrown?

`curator --host <myservername> snapshot --repository my_s3_repository --name indices-2015.08.04 --request_timeout 7200 indices --older-than 13 --time-unit days --timestring %Y.%m.%d --exclude foo`
2015-08-17 11:12:04,114 INFO      Job starting: snapshot indices
2015-08-17 11:12:04,115 WARNING   Overriding default connection timeout.  New timeout: 21600
2015-08-17 11:12:06,338 INFO      Snapshot name: indices-2015.08.04
**2015-08-17 11:16:08,389 ERROR     Client raised a TransportError.**
2015-08-17 11:16:08,390 WARNING   Job did not complete successfully.

**Comment by untergeek** [comment]
You could add the `--debug` flag to see more.

7200 seconds is extremely short for a snapshot.  I do not recommend using the `--request_timeout` flag as it is most commonly used in conjunction with—but opposition to—the `--timeout` flag.  `--timeout` is for the client timeout (the connection to Elasticsearch), where `--request_timeout` should be less than the `--timeout` flag.  `--request_timeout` is used to force Elasticsearch to return in the event a request is long running.  It's not for managing a client-level timeout.

Those things said, it looks like you have almost exactly 4 minutes between creating the client and the timeout, which is less than the client timeout of 21600 _and_ the request_timeout of 7200.  Chances are you're hitting a gateway timeout (504) error, [described in this FAQ](https://www.elastic.co/guide/en/elasticsearch/client/curator/current/_q_snapshots_seem_to_be_working_why_am_i_getting_literal_snapshotmissingexception_literal_messages.html).  You can see for sure if you use the `--debug` flag.

**Comment by rhealitycheck** [comment]
Ok, so I just ran one with the `--request_timeout` taken out and `--debug` on. and this is the error message that i get:

`2015-08-17 12:06:25,441 DEBUG         urllib3.util.retry               from_int:155  Converted retries value: False -> Retry(total=False, connect=None, read=None, redirect=0)
2015-08-17 12:07:25,443 WARNING            elasticsearch       log_request_fail:82   PUT http://haproxystaging:9200/_snapshot/my_s3_repository/mdp-2015.08.04?wait_for_completion=true [status:N/A request:60.002s]
Traceback (most recent call last):
  File "/Users/rhea/dev/venv/lib/python2.7/site-packages/elasticsearch/connection/http_urllib3.py", line 74, in perform_request
    response = self.pool.urlopen(method, url, body, retries=False, headers=self.headers, **kw)
  File "/Users/rhea/dev/venv/lib/python2.7/site-packages/urllib3/connectionpool.py", line 607, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/Users/rhea/dev/venv/lib/python2.7/site-packages/urllib3/util/retry.py", line 222, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/Users/rhea/dev/venv/lib/python2.7/site-packages/urllib3/connectionpool.py", line 557, in urlopen
    body=body, headers=headers)
  File "/Users/rhea/dev/venv/lib/python2.7/site-packages/urllib3/connectionpool.py", line 374, in _make_request
    httplib_response = conn.getresponse(buffering=True)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1045, in getresponse
    response.begin()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 409, in begin
    version, status, reason = self._read_status()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 373, in _read_status
    raise BadStatusLine(line)
**ProtocolError: ('Connection aborted.', BadStatusLine("''",))**
2015-08-17 12:07:25,450 DEBUG              elasticsearch       log_request_fail:90   > {"indices": "mdp-2015.08.04", "partial": false, "ignore_unavailable": false, "include_global_state": true}
2015-08-17 12:07:25,450 DEBUG         urllib3.util.retry               from_int:155  Converted retries value: False -> Retry(total=False, connect=None, read=None, redirect=0)
2015-08-17 12:07:25,451 INFO      urllib3.connectionpool              _new_conn:205  Starting new HTTP connection (2): haproxystaging
2015-08-17 12:07:25,528 DEBUG     urllib3.connectionpool          _make_request:385  "PUT /_snapshot/my_s3_repository/mdp-2015.08.04?wait_for_completion=true HTTP/1.1" 503 233
2015-08-17 12:07:25,528 WARNING            elasticsearch       log_request_fail:82   PUT /_snapshot/my_s3_repository/mdp-2015.08.04?wait_for_completion=true [status:503 request:0.077s]
2015-08-17 12:07:25,528 DEBUG              elasticsearch       log_request_fail:90   > {"indices": "mdp-2015.08.04", "partial": false, "ignore_unavailable": false, "include_global_state": true}
2015-08-17 12:07:25,528 DEBUG         urllib3.util.retry               from_int:155  Converted retries value: False -> Retry(total=False, connect=None, read=None, redirect=0)
2015-08-17 12:07:25,536 DEBUG     urllib3.connectionpool          _make_request:385  "PUT /_snapshot/my_s3_repository/mdp-2015.08.04?wait_for_completion=true HTTP/1.1" 503 233
2015-08-17 12:07:25,537 WARNING            elasticsearch       log_request_fail:82   PUT /_snapshot/my_s3_repository/mdp-2015.08.04?wait_for_completion=true [status:503 request:0.008s]
2015-08-17 12:07:25,537 DEBUG              elasticsearch       log_request_fail:90   > {"indices": "mdp-2015.08.04", "partial": false, "ignore_unavailable": false, "include_global_state": true}
2015-08-17 12:07:25,537 DEBUG         urllib3.util.retry               from_int:155  Converted retries value: False -> Retry(total=False, connect=None, read=None, redirect=0)
2015-08-17 12:07:25,544 DEBUG     urllib3.connectionpool          _make_request:385  "PUT /_snapshot/my_s3_repository/mdp-2015.08.04?wait_for_completion=true HTTP/1.1" 503 233
2015-08-17 12:07:25,544 WARNING            elasticsearch       log_request_fail:82   PUT /_snapshot/my_s3_repository/mdp-2015.08.04?wait_for_completion=true [status:503 request:0.007s]
2015-08-17 12:07:25,544 DEBUG              elasticsearch       log_request_fail:90   > {"indices": "mdp-2015.08.04", "partial": false, "ignore_unavailable": false, "include_global_state": true}
2015-08-17 12:07:25,544 ERROR       curator.api.snapshot        create_snapshot:91   Client raised a TransportError.
2015-08-17 12:07:25,544 WARNING        curator.cli.utils               exit_msg:69   Job did not complete successfully.`

and I'm confused where the bad status line is coming from given that before that it returned a giant list of all the snapshots I currently have in my repo.

**Comment by untergeek** [comment]
Well, it's not a 504, but you are getting several 503 errors, which are "Service unavailable" errors.

```
2015-08-17 12:07:25,544 WARNING            elasticsearch       log_request_fail:82   PUT /_snapshot/my_s3_repository/mdp-2015.08.04?wait_for_completion=true [status:503 request:0.007s]
```

You're also seeing a 60 second timeout:

```
2015-08-17 12:07:25,443 WARNING            elasticsearch       log_request_fail:82   PUT http://haproxystaging:9200/_snapshot/my_s3_repository/mdp-2015.08.04?wait_for_completion=true [status:N/A request:60.002s]
```

This timeout is what the `**ProtocolError: ('Connection aborted.'` part is reporting.

Just from the hostname, `haproxystaging`, I presume you have your Elasticsearch clients behind some kind of proxy gateway.  This is why you're timing out.  Your HAProxy is forcing the client connection to timeout at 60 seconds, just like in the FAQ I referenced in my last comment.

Your options include:

1. Don't connect to the HAProxy for snapshot operations, but instead have a direct client connection.
2. Use `--wait_for_completion False` (it will run in the background, and you'll have to use some other tool to check for completion).
3. Increase the HAProxy timeout to a ludicrous number somehow (not recommended unless it can be limited to this use case).
4. Something else I haven't thought of...

**Comment by rhealitycheck** [comment]
Ah yes, I see where the connection is having issues with the proxy now but connecting directly to a client node seems to be working out as expected -- we just changed our setup to have client nodes in front of the data nodes, so I had initially been connecting to those but when we stopped allowing connections to the data nodes I defaulted to the proxy but this makes more sense. I've tried using the `--wait_for_completion False` and have had mixed results with that which is why I finally asked how I could fix this because we'd really like reliable snapshots.

**Comment by untergeek** [comment]
Glad that ironed it out for you.  We definitely recommend using client nodes where possible, instead of connecting directly to data nodes.

**Comment by rhealitycheck** [comment]
Yeah, we knew that going in we just didn't have the hardware to support that initially but thankfully we do now and then transitioning to it changed things up a bit so we're still working through all of it. Thanks for the help!
