### ISSUE TITLE
Deleting S3 snapshots succeeds, but ConnectionTimeout is still raised

### ISSUE THREAD

**Issue by rodriguezsergio** [elastic/curator#478]
I'm currently testing out curator so we have an automated way of purging old snapshots on S3, but I'm confused as to why it exits with a status code of 1 when the snapshot is successfully removed.

```
$ curator  --timeout 120  delete snapshots --older-than 57 --time-unit days  --repository $S3bucket --timestring "%Y_%m_%d"        
2015-09-10 16:47:42,399 INFO      Job starting: delete snapshots
2015-09-10 16:47:42,798 INFO      Deleting snapshot 2015_07_15



Traceback (most recent call last):
  File "/usr/local/bin/curator", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.6/site-packages/curator/curator.py", line 5, in main
    cli( obj={ "filters": [] } )
  File "/usr/local/lib/python2.6/site-packages/click/core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.6/site-packages/click/core.py", line 680, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.6/site-packages/click/core.py", line 1027, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.6/site-packages/click/core.py", line 1027, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.6/site-packages/click/core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.6/site-packages/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.6/site-packages/click/decorators.py", line 16, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.6/site-packages/curator/cli/snapshot_selection.py", line 91, in snapshots
    retval = delete_snapshot(client, snapshot=snap, repository=repository)
  File "/usr/local/lib/python2.6/site-packages/curator/api/snapshot.py", line 113, in delete_snapshot
    client.snapshot.delete(repository=repository, snapshot=snapshot)
  File "/usr/local/lib/python2.6/site-packages/elasticsearch/client/utils.py", line 69, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/local/lib/python2.6/site-packages/elasticsearch/client/snapshot.py", line 40, in delete
    _make_path('_snapshot', repository, snapshot), params=params)
  File "/usr/local/lib/python2.6/site-packages/elasticsearch/transport.py", line 307, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/usr/local/lib/python2.6/site-packages/elasticsearch/connection/http_urllib3.py", line 82, in perform_request
    raise ConnectionTimeout('TIMEOUT', str(e), e)
elasticsearch.exceptions.ConnectionTimeout: ConnectionTimeout caused by - ReadTimeoutError(HTTPConnectionPool(host=u'localhost', port=9200): Read timed out. (read timeout=120))
```

Prior to this, I ran this command without the higher timeout and experienced the same issue. As soon as I provided the 2 minute timeout, the command went 2 minutes with no output and then failed immediately afterwards.

**Comment by untergeek** [comment]
That timeout could need to be much higher.  You can see more in the output if you run it with the `--debug` flag.  S3 can particularly be an issue with insufficiently high timeout values.  If you want a zero exit code, you should perhaps give a timeout of at least 300 seconds, perhaps more.

Another issue to consider is in the FAQ, here: https://www.elastic.co/guide/en/elasticsearch/client/curator/current/_q_snapshots_seem_to_be_working_why_am_i_getting_literal_snapshotmissingexception_literal_messages.html

**Comment by rodriguezsergio** [comment]
Looks like that did it. Thanks. :+1: 

```
$ time curator --timeout 300 delete snapshots --older-than 57 --time-unit days --repository $S3bucket --timestring "%Y_%m_%d"
2015-09-11 15:17:07,607 INFO      Job starting: delete snapshots
2015-09-11 15:17:07,880 INFO      Deleting snapshot 2015_07_16
2015-09-11 15:19:43,612 INFO      Job completed successfully.

real	2m36.367s
user	0m0.188s
sys	0m0.088s
```
