### ISSUE TITLE
failures optimizing index

### ISSUE THREAD

**Issue by allenmchan** [elastic/curator#482]
I just noticed this in the curator logs. I am already running with --debug but it is not saying much.
$ rpm -qa | grep -i curator
python-elasticsearch-curator-3.2.3-1.noarch

Running against Elasticsearch 1.7.2

*2015-10-02 06:00:03,844 WARNING            elasticsearch       log_request_fail:82   POST http://localhost:9200/logstash-2015.10.01/_optimize?max_num_segments=1 [status:N/A request:21600.056s]
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/elasticsearch/connection/http_urllib3.py", line 74, in perform_request
    response = self.pool.urlopen(method, url, body, retries=False, headers=self.headers, **kw)
  File "/usr/lib/python2.6/site-packages/urllib3/connectionpool.py", line 597, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python2.6/site-packages/urllib3/util/retry.py", line 222, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/lib/python2.6/site-packages/urllib3/connectionpool.py", line 544, in urlopen
    body=body, headers=headers)
  File "/usr/lib/python2.6/site-packages/urllib3/connectionpool.py", line 376, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/lib/python2.6/site-packages/urllib3/connectionpool.py", line 304, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
ReadTimeoutError: HTTPConnectionPool(host='localhost', port=9200): Read timed out. (read timeout=21600)
2015-10-02 06:00:03,845 DEBUG              elasticsearch       log_request_fail:90   > None
2015-10-02 06:00:03,845 ERROR       curator.api.optimize         optimize_index:31   Error optimizing index logstash-2015.10.01.  Run with --debug flag and/or check Elasticsearch logs for more information.
2015-10-02 06:00:03,845 WARNING        curator.cli.utils               exit_msg:69   Job did not complete successfully.*

**Comment by allenmchan** [comment]
Actually the weird thing is that even though the log says the optimize call failed, running 
'GET logstash-2015.10.02/_segments' in Marvel shows only one segment per shard. So it looks like the log is giving a false error.

**Comment by untergeek** [comment]
The very first line explains what happened:

```
2015-10-02 06:00:03,844 WARNING elasticsearch log_request_fail:82 POST http://localhost:9200/logstash-2015.10.01/_optimize?max_num_segments=1 [status:N/A request:21600.056s]
```

`request 21600.056s` means that it timed out, which is evident from several other indicators in the logs, e.g. `ReadTimeoutError` and `Read timed out. (read timeout=21600)`.  See [the optimize command documentation regarding timeouts](https://www.elastic.co/guide/en/elasticsearch/client/curator/current/optimize.html#_a_word_about_timeouts) for more information.


This all means that that one, single optimize call took over 6 hours to return, _**but the job continued in the background and completed in spite of the client timeout.**_  

Why was it unable to succeed in the 6 hour default timeout?  This could be for several reasons, including:

1. Indexing is heavy
2. Too few nodes to handle the write load
3. Using slow spinning disks instead of SSDs
4. ???

Options include adding nodes, switching to SSDs, or the cheaper fix of increasing the `--timeout` and `--request_timeout` options _both_ to something larger even than 6 hours (6 x 3600 seconds = 21600).  If your indices are very large, consider optimizing to a larger number segments per shard rather than 1, or the default of 2.

**Comment by allenmchan** [comment]
Thank you for the explanation. I will close this as it seems to be my performance issue and not curator
