### ISSUE TITLE
Node gets kicked out on Index Deletion

### ISSUE THREAD

**Issue by rhealitycheck** [elastic/curator#484]
I'm having a strange issue where sometimes upon index deletion a node will get kicked out of my cluster, and it's typically the primary node so then there will be an election and the node that got kicked out won't be able to rejoin. However I don't see anything in my logs that show any issues with the cluster. I've deleted indexes during prod hours using curator and had no issues so I'm just curious if anyone else has seen this or if there's any explanation for this behavior or what I can do to troubleshoot given that I can't find any pattern to why this is happening.

I'm using curator 3.2.3 and elasticsearch 1.8 -- this happens both on my staging cluster which is on VMWare vms and just happened on my prod cluster in AWS.

**Comment by untergeek** [comment]
Curator only uses Elasticsearch API calls.  Chances are very good that you'd see the same node dropping behavior if you made the same API call that Curator uses.

Have you looked through the Elasticsearch logs?  Particularly the client that Curator hits, and the elected master node's logs.  Evidence of what is transpiring may be found there.

How many shards per node do you have?  This may sound like a strange question, but the answer may have some bearing on what's going on.

**Comment by rhealitycheck** [comment]
So we run the script at 4am when basically nothing is happening. And yes I've looked through the master's logs and haven't found anything -- there's some noise in the logs from some Kibana graphs where facets have broken since our upgrade, but those seem to be consistent throughout the day and essentially have no effect on the cluster. I don't always know which client the API is connection to though because we have a load balancer in front of our cluster, I suppose I could turn up the curator logs to debug that may help. I'll see if I can find the most recent client that it was calling and see if there's anything in there. 

I guess what's most strange to me is that I literally don't see anything in the master's logs until I see it saying that it's lost connection to the cluster and then it revives itself and rejects the master that the cluster has elected, which is where we need to go in and manually restart elasticsearch so it can rejoin the cluster. 

We have 3-5 shards per node and 9 shards per index.

**Comment by untergeek** [comment]
I have no idea which operations you're using Curator to complete, but I highly discourage the use of load-balancers between Curator and client node(s).  Several operations can take a long time to process (particularly optimize and snapshot), which has caused many user much grief.  Your problem seems to be with delete operations, which is a different story, though.

I have seen delete operations take a toll on master nodes, but usually only when the cluster state is huge, and updating the cluster state takes enough time to cause issues.

> We have 3-5 shards per node and 9 shards per index.

If I interpret this correctly, it seems like you meant "we have 3-5 indices per node, and 9 shards per index."  If not so, this seems to indicate that you have 3 or 4 nodes per primary shard (to say nothing of replica shards), to spread them around that far.

If you meant 3-5 indices per node, and 9 shards per index, that would mean something different.  Either way, it doesn't seem like you have over 300 shards per node.  This is the point at which I would expect deletes to potentially begin affecting the cluster state.

I can't see Curator as an influencing factor in your problem here with the information you've shared.

**Comment by rhealitycheck** [comment]
Ah apologies on the shard question, I was confused. We have 120 indexes with somewhere between 3-5 shards per node at a total of 9 shards per index. So on a single node we'll have ~ 360 shards or more. But since we're only deleting 4 indexes of those 120 indexes I didn't think this would be an issue.

Also, I was mistaken I am not connection to the proxy but actually directly to a client node (I'd asked this before and changed it on your recommendation and forgotten that I made that change). And these are the logs I see from the client -- but I really don't see anything in this other than the master data node leaving. And as far as I can tell nothing is happening on the cluster other than one Kibana graph that's having trouble rendering:

     [2015-10-04 03:58:14,850][INFO ][discovery.ec2            ] [AWSDATANODE01] master_left [[AWSLXPROD005][KuYwb4ULT2GKcHqDQHZgkA][AWSLXPROD005][inet[/xxx.xxx.xxx.xxxx:9300]]{aws_availability_zone=us-east-1a}], reason [transport disconnected]
     [2015-10-04 03:58:14,850][WARN ][discovery.ec2            ] [AWSDATANODE01] master left (reason = transport disconnected), current nodes: {[AWSLXPROD006][X7eklovjRISRnQD6i7vDfg][AWSDATANODE02][inet[/xx.xxx.xxx.xxxx:9300]]{aws_availability_zone=us-east-1a},[AWSDATANODE03][XzdCC3FQTGaGh3Q2bqeR9A][AWSDATANODE05][inet[/xx.xxx.xxxx.xx:9300]]{aws_availability_zone=us-east-1d},[AWSDATANODE04][sO_0Fk4BQjyw8UhCs0WXVQ][AWSLXPROD008][inet[/xxx.xxx.xxx.xxxx:9300]]{aws_availability_zone=us-east-1b},[AWSDATANODE06][PB1wSO1DTgO7NYZkumEUtA][AWSDATANODE02][inet[/xx.xxx.xx.xxxx:9300]]{aws_availability_zone=us-east-1b},[AWSDATANODE01][cBU0J9LnQGKmgsF_0y0Ihw][AWSDATANODE01][inet[/xxx.xxx.xx.xxx:9300]]{aws_availability_zone=us-east-1a, data=false, master=false},[AWSDATANODE07][nGdqrIb9TlieBtkIrai_Zw][AWSDATANODE07][inet[/xx.xxx.xxx.xxx:9300]]{aws_availability_zone=us-east-1a},[AWSDATANODE09][d6RtyZhISiWexxsShS4mhw][AWSLXPROD015][inet[/xx.xx.xxxx.xxx:9300]]{aws_availability_zone=us-east-1d, data=false, master=false},[AWSDATANODE010][A9pKJWQETAWq_ZT6bzDYbQ][AWSDATANODE010][inet[/xx.xxx.xxx.xxx:9300]]{aws_availability_zone=us-east-1b, data=false, master=false},[AWSLXPROD010][fMPQz1_ySaqXHGvLfA0PeQ][AWSLXPROD010][inet[/xxx.xxx.xxx.xxx:9300]]{aws_availability_zone=us-east-1d},}
     [2015-10-04 03:58:14,851][INFO ][cluster.service          ] [AWSDATANODE01] removed {[AWSDATANODE02][KuYwb4ULT2GKcHqDQHZgkA][AWSLXPROD005][inet[/xxx.xxx.xxx.xxxx:9300]]{aws_availability_zone=us-east-1a},}, reason: zen-disco-master_failed ([AWSDATANODE02][KuYwb4ULT2GKcHqDQHZgkA][AWSLXPROD005][inet[/xxx.xx.xx.xxx:9300]]{aws_availability_zone=us-east-1a})
     [2015-10-04 03:58:14,853][DEBUG][action.admin.indices.delete] [AWSDATANODE01] connection exception while trying to forward request to master node [[AWSDATANODE02][KuYwb4ULT2GKcHqDQHZgkA][AWSDATANODE02][inet[/xx.xxxx.xxx.xxx:9300]]{aws_availability_zone=us-east-1a}], scheduling a retry. Error: [org.elasticsearch.transport.NodeDisconnectedException: [AWSDATANODE02][inet[/172.16.1.237:9300]][indices:admin/delete] disconnected]
     [2015-10-04 03:58:14,857][DEBUG][action.admin.indices.delete] [AWSDATANODE01] no known master node, scheduling a retry
     [2015-10-04 03:58:20,697][INFO ][cluster.service          ] [AWSDATANODE01] detected_master [AWSLXPROD009][PB1wSO1DTgO7NYZkumEUtA][AWSLXPROD009][inet[/xxx.x.xx.xxx:9300]]{aws_availability_zone=us-east-1b}, reason: zen-disco-receive(from master [[AWSDATANODE03][PB1wSO1DTgO7NYZkumEUtA][AWSDATANODE03][inet[/xx.xxx.xxx.xxx:9300]]{aws_availability_zone=us-east-1b}])
     [2015-10-04 03:58:34,385][DEBUG][action.search.type       ] [AWSDATANODE01] [logstash-2015.10.04][1], node[XzdCC3FQTGaGh3Q2bqeR9A], [P], s[STARTED]: Failed to execute [org.elasticsearch.action.search.SearchRequest@5dd64e] lastShard [true]

**Comment by untergeek** [comment]
These logs are helpful, but it'd be much better to see what, if anything came before that.  I see `master_left`, and then the resulting failure to forward the delete request to the master:

```
… connection exception while trying to forward request to master node …
```

But I do not see the actual delete command come in, or what transpired in the moments before Curator made the delete call.  Clearly something is prodding a network or node failure (with the master), but I can't tell what.  What do the master node logs say?

When I send a delete through Curator, the elected master node log reports this:

```
[2015-10-04 02:30:01,278][INFO ][cluster.metadata         ] [Elasticbox] [logstash-2015.09.19] deleting index
```

Do you see `deleting index` messages in your elected master node logs?  Those would be helpful to track down.

**Comment by rhealitycheck** [comment]
So the client node logs are a little tough to read because before that I primarily see some version of this error because of a misconfigured kibana graph -- I just went through with my team to get rid of this, it's been in there for a while but aside from this noise I really don't see anything referring to the master or a delete operation and I've searched the logs:

```
[2015-10-04 03:58:05,224][DEBUG][action.search.type       ] [AWSDATANODE01] All shards failed for phase: [query]
org.elasticsearch.transport.RemoteTransportException: [AWSDATANODE02][inet[/xxx.xxx.xxx.xxx:9300]][indices:data/read/search[phase/query]]
Caused by: org.elasticsearch.search.SearchParseException: [logstash-2015.10.04][5]: from[-1],size[-1]: Parse Failure [Failed to parse source [{"facets":{"2":{"date_histogram":{"key_field":"@timestamp","value_field":"band","interval":"1m"},"global":true,"facet_filter":{"fquery":{"query":{"filtered":{"query":{"query_string":{"query":"symbol.raw:WMB"}},"filter":{"bool":{"must":[{"range":{"@timestamp":{"from":1443938402147,"to":1443949202147}}},{"fquery":{"query":{"query_string":{"query":"type.raw:hegemon_Production"}},"_cache":true}}]}}}}}}}},"size":0}]]
        at org.elasticsearch.search.SearchService.parseSource(SearchService.java:747)
        at org.elasticsearch.search.SearchService.createContext(SearchService.java:572)
        at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:544)
        at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:306)
        at org.elasticsearch.search.action.SearchServiceTransportAction$SearchQueryTransportHandler.messageReceived(SearchServiceTransportAction.java:776)
        at org.elasticsearch.search.action.SearchServiceTransportAction$SearchQueryTransportHandler.messageReceived(SearchServiceTransportAction.java:767)
        at org.elasticsearch.transport.netty.MessageChannelHandler$RequestHandler.doRun(MessageChannelHandler.java:279)
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:36)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: org.elasticsearch.search.facet.FacetPhaseExecutionException: Facet [2]: (value) field [band] not found
        at org.elasticsearch.search.facet.datehistogram.DateHistogramFacetParser.parse(DateHistogramFacetParser.java:198)
        at org.elasticsearch.search.facet.FacetParseElement.parse(FacetParseElement.java:93)
        at org.elasticsearch.search.SearchService.parseSource(SearchService.java:731)
        ... 10 more
```

On the elected master this is what I see from when it receives the delete index request to when it's initializing again:
```
[2015-10-04 00:01:01,774][INFO ][snapshots                ] [AWSDATANODE01] snapshot      [my_s3_repository:dashboards-2015.10.03] is done
[2015-10-04 01:03:00,556][INFO ][cluster.metadata         ] [AWSDATANODE01] [logstash-2015.10.04] update_mapping [syslog-Production] (dynamic)
[2015-10-04 01:31:27,839][INFO ][snapshots                ] [AWSDATANODE01] snapshot [my_s3_repository:mdp-2015.08.24] is done
[2015-10-04 01:46:53,752][INFO ][snapshots                ] [AWSDATANODE01] snapshot [my_s3_repository:indices-2015.08.24] is done
[2015-10-04 02:50:12,154][INFO ][cluster.metadata         ] [AWSDATANODE01] [logstash-2015.10.04] update_mapping [index_Production] (dynamic)
[2015-10-04 02:51:47,066][INFO ][cluster.metadata         ] [AWSDATANODE01] [logstash-2015.10.04] update_mapping [index_Production] (dynamic)
[2015-10-04 03:01:32,323][INFO ][cluster.metadata         ] [AWSDATANODE01] [logstash-2015.10.04] update_mapping [salt_UAT] (dynamic)
[2015-10-04 03:02:33,739][INFO ][cluster.metadata         ] [AWSDATANODE01] [logstash-2015.10.04] update_mapping [salt_UAT] (dynamic)
[2015-10-04 03:05:21,298][INFO ][cluster.metadata         ] [AWSDATANODE01] [logstash-2015.10.04] update_mapping [index_Production] (dynamic)
[2015-10-04 03:07:58,083][INFO ][cluster.metadata         ] [AWSDATANODE01] [logstash-2015.10.04] update_mapping [monitoring_Production] (dynamic)
[2015-10-04 03:07:59,268][INFO ][cluster.metadata         ] [AWSDATANODE01] [logstash-2015.10.04] update_mapping [monitoring_Production] (dynamic)
[2015-10-04 03:10:46,884][INFO ][cluster.metadata         ] [AWSDATANODE01] [logstash-2015.10.04] update_mapping [logstash_agent_UAT] (dynamic)
[2015-10-04 04:00:59,757][INFO ][cluster.metadata         ] [AWSDATANODE01] [logstash-1970.01.02] deleting index
[2015-10-04 04:01:00,905][INFO ][cluster.metadata         ] [AWSDATANODE01] [logstash-2015.08.24] deleting index
[2015-10-04 16:46:15,985][INFO ][node                     ] [AWSDATANODE01] version[1.7.0], pid[11074], build[929b973/2015-07-16T14:31:07Z]
[2015-10-04 16:46:15,986][INFO ][node                     ] [AWSDATANODE01] initializing ...
```

**Comment by untergeek** [comment]
Strange.  It seems you do not have DEBUG mode on the master node, so we're left with only INFO.

The bit that interests me is that you do not see the delete request, only the node re-initializing.

Also that you're on 1.7.0.  There were a few bugs with 1.7.0 which may or may not have anything to do with what you're seeing.  It can't hurt to upgrade to 1.7.2, though.

**Comment by rhealitycheck** [comment]
Yeah I saw that too. I'll give upgrading a try. It can't hurt.

Also I'm confused how I can have DEBUG on one node but INFO on another... I thought those were cluster-wide settings, right?

**Comment by untergeek** [comment]
Log settings are in the logging.yml file in the config directory.  If they can be set by API (which I'm not sure they can), that would only be per node, rather than cluster-wide.

**Comment by rhealitycheck** [comment]
Ah, ok. I had set it via the API but assumed it was cluster-wide not per node. I'll just update the logging.yml instead and do a restart. And I'll re-open this thread if after the update I still see it pop up and and hopefully debug will give some more information on it.
