### ISSUE TITLE
Curator snapshot --prefix should catch invalid snapshot names

### ISSUE THREAD

**Issue by seang-es** [elastic/curator#562]
Elasticsearch will not accept any snapshot name containing capital letters.  ES will reject these if Curator attempts to create one, but the returned error in the Curator logs does not make obvious what the problem is.  Curator should catch capital letters in the --prefix and warn the user.

**Comment by rhorii** [comment]
default name is not available :scream: 

```
$ curator snapshot --repository s3_repository indices --all-indices
Traceback (most recent call last):
  File "/usr/bin/curator", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/dist-packages/curator/curator.py", line 5, in main
    cli( obj={ "filters": [] } )
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 1057, in invoke
    Command.invoke(self, ctx)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/curator/cli/snapshot.py", line 46, in snapshot
    if any(c.isupper() for c in name):
TypeError: 'NoneType' object is not utterable
```
