### ISSUE TITLE
Snapshots to S3: Unable to find all snapshots in repository

### ISSUE THREAD

**Issue by pnayak** [elastic/curator#572]
Hi:

We're running into a peculiar problem with Curator

Curator version: 2.4.1
ElasticSearch version: 1.3.4
AWS Cloud Plugin version: 2.3.0

This is a single node ElasticSearch cluster

Steps:

1. Create a S3 repository called "backups" (using es_repo_mgr)
2. Try to create a snapshot using the S3 repository

```
>> curator  --host localhost --port 9200 snapshot --repository backups  indices --prefix <a-prefix>
```

**Output:**

2016-02-27 16:30:34,814 INFO      Job starting: snapshot indices
2016-02-27 16:30:34,814 WARNING   Overriding default connection timeout.  New timeout: 21600
2016-02-27 16:30:34,823 INFO      Action snapshot will be performed on the following indices: < list-of-indices-redacted >
2016-02-27 16:30:34,841 INFO      Snapshot name: curator-20160227213034
**2016-02-27 16:30:35,562 ERROR     Unable to find all snapshots in repository: backups
2016-02-27 16:30:35,562 ERROR     Unable to find all snapshots in repository**
2016-02-27 16:30:35,562 WARNING   Job did not complete successfully.

Its bizarre that this is happening.  

At this stage, even trying to show snapshots is returning a similar error

```
>> curator show snapshots --repository backups --all-snapshots     
```

**Output:**

2016-02-27 16:32:30,680 INFO Job starting: show snapshots
**2016-02-27 16:32:31,701 ERROR     Unable to find all snapshots in repository: backups
2016-02-27 16:32:31,701 ERROR     No snapshots found in Elasticsearch.**
No snapshots found in Elasticsearch.

Nothing of note in the Elasticsearch logs... 

Found a similar issue https://github.com/elastic/curator/issues/374  but that one did not have a clear resolution either.

Definitely appreciate any input/guidance this forum might provide.

Thanks!

**Comment by untergeek** [comment]
I presume you meant 3.4.1 as the Curator version. 

I'd run it again with the --debug flag to see more of the error.

**Comment by mpuchol-netquest** [comment]
Same problem here.

Found the following error executing with `--debug`:
```
2016-02-28 09:14:36,396 DEBUG     urllib3.connectionpool          _make_request:383  "GET /_snapshot/s3_repository/_all HTTP/1.1" 500 439
2016-02-28 09:14:36,396 WARNING            elasticsearch       log_request_fail:82   GET /_snapshot/s3_repository/_all [status:500 request:0.323s]
```

ElasticSearch is returning a 500. ES logs show:
```
[2016-02-28 09:14:36,395][INFO ][rest.suppressed          ] /_snapshot/s3_repository/_all Params: {repository=s3_repository, snapshot=_all}
com.amazonaws.services.s3.model.AmazonS3Exception: The operation is not valid for the object's storage class (Service: Amazon S3; Status Code: 403; Error Code: InvalidObjectState; Request ID: 196D6A8F3DD3A2DA), S3 Extended Request ID: qJTKmYTIZ3yTWejeAA2ZJ4Sm2PRulS4BqsIRnGtV76ukrzanq3ngswVLhBKJukTbcf3/ZyGB8Ps=
        at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:1239)
        at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:823)
        at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:506)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:318)
        at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:3595)
        at com.amazonaws.services.s3.AmazonS3Client.getObject(AmazonS3Client.java:1116)
        at com.amazonaws.services.s3.AmazonS3Client.getObject(AmazonS3Client.java:1005)
        at org.elasticsearch.cloud.aws.blobstore.S3BlobContainer.openInput(S3BlobContainer.java:83)
        at org.elasticsearch.common.blobstore.support.AbstractLegacyBlobContainer.readBlob(AbstractLegacyBlobContainer.java:62)
        at org.elasticsearch.repositories.blobstore.LegacyBlobStoreFormat.readBlob(LegacyBlobStoreFormat.java:55)
        at org.elasticsearch.repositories.blobstore.BlobStoreFormat.read(BlobStoreFormat.java:85)
        at org.elasticsearch.repositories.blobstore.BlobStoreRepository.readSnapshot(BlobStoreRepository.java:444)
        at org.elasticsearch.snapshots.SnapshotsService.snapshots(SnapshotsService.java:150)
        at org.elasticsearch.action.admin.cluster.snapshots.get.TransportGetSnapshotsAction.masterOperation(TransportGetSnapshotsAction.java:77)
        at org.elasticsearch.action.admin.cluster.snapshots.get.TransportGetSnapshotsAction.masterOperation(TransportGetSnapshotsAction.java:46)
        at org.elasticsearch.action.support.master.TransportMasterNodeAction$3.doRun(TransportMasterNodeAction.java:130)
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by mpuchol-netquest** [comment]
Glacier objects seems to be the problem (according to https://discuss.elastic.co/t/s3-input-plugin-choking-on-glacier-files/28119).

**Comment by untergeek** [comment]
> `The operation is not valid for the object's storage class`

If you are trying to snapshot to Glacier, this is not supported by Elasticsearch.  Only to a regular S3 file store.   You could theoretically move the files from _there_ to a Glacier storage, but not directly.

**Comment by mpuchol-netquest** [comment]
Yes, you're right.

It's because snapshot metadata is stored on S3 and this metadata is needed by `GET http://localhost:9200/_snapshot/s3_repository/_all`. If your lifecycle moves these metadata files to Glacier, the problem appears.

To fix it, I just moved all metadata files from Glacier to S3 and forced the lifecycle to just move to Glacier on path `indices`.

It seems to work.

**Comment by untergeek** [comment]
Thanks for the report.  Closing this now.
