### ISSUE TITLE
3.4.1 timeouts with 1.7.5

### ISSUE THREAD

**Issue by niemyjski** [elastic/curator#582]
We recently updated curator within the past month and cleaning up snapshots has been really unreliable and causing them to not even work at all.

https://github.com/exceptionless/Exceptionless/wiki/Elasticsearch-setup-guide#create-the-backup-and-cleanup-scripts

```sh
/mnt/data# sh cleanup_snapshots
2016-03-16 19:13:14,387 INFO      Job starting: delete snapshots
2016-03-16 19:15:14,490 ERROR     Unable to find all snapshots in repository: ex_events
2016-03-16 19:15:14,491 ERROR     No snapshots found in Elasticsearch.
No snapshots found in Elasticsearch.
2016-03-16 19:15:14,677 INFO      Job starting: delete snapshots
2016-03-16 19:17:03,061 INFO      Deleting snapshot 2016-03-05-13-20
Traceback (most recent call last):
  File "/usr/local/bin/curator", line 9, in <module>
    load_entry_point('elasticsearch-curator==3.4.1', 'console_scripts', 'curator')()
  File "/usr/local/lib/python2.7/dist-packages/curator/curator.py", line 5, in main
    cli( obj={ "filters": [] } )
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/curator/cli/snapshot_selection.py", line 93, in snapshots
    retval = delete_snapshot(client, snapshot=snap, repository=repository)
  File "/usr/local/lib/python2.7/dist-packages/curator/api/snapshot.py", line 123, in delete_snapshot
    client.snapshot.delete(repository=repository, snapshot=snapshot)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/client/utils.py", line 69, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/client/snapshot.py", line 40, in delete
    _make_path('_snapshot', repository, snapshot), params=params)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/transport.py", line 329, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/connection/http_urllib3.py", line 99, in perform_request
    raise ConnectionTimeout('TIMEOUT', str(e), e)
elasticsearch.exceptions.ConnectionTimeout: ConnectionTimeout caused by - ReadTimeoutError(HTTPConnectionPool(host=u'localhost', port=9200): Read timed out. (read timeout=120))
2016-03-16 19:19:03,368 INFO      Job starting: delete snapshots
2016-03-16 19:21:03,470 ERROR     Unable to find all snapshots in repository: ex_organizations
2016-03-16 19:21:03,471 ERROR     No snapshots found in Elasticsearch.
No snapshots found in Elasticsearch.
```

**Comment by corey-hammerton** [comment]
What versions of Elasticsearch and Curator are you using? It's not completely clear from your description.

**Comment by untergeek** [comment]
@niemyjski I'm sorry to hear your experience has been less than stellar.

Before I looked at the link you provided, I saw this in the log data you pasted:

```
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/connection/http_urllib3.py", line 99, in perform_request
    raise ConnectionTimeout('TIMEOUT', str(e), e)
elasticsearch.exceptions.ConnectionTimeout: ConnectionTimeout caused by - ReadTimeoutError(HTTPConnectionPool(host=u'localhost', port=9200): Read timed out. (read timeout=120))
```
A timeout, such as this one, means that Curator is not able to get the data or response it expects from Elasticsearch in the given time.  In this case, it's 120 seconds.  This differs from what you have in that wiki link, which says 600 seconds.

Having perused the contents of that wiki entry, I see that you're using Azure for your snapshot repository.  Remote repositories can take a lot longer to respond,  I suggest at least a 600 second timeout, if not 900.  The reality is that Curator isn't a special client tool.  It just does API calls to Elasticsearch and reports the results.  If Curator timed out at 120 seconds, chances are very good that a curl call of the same would suffer similarly.

Some questions to help troubleshoot this further would be to ascertain how many snapshots are in these repositories, and other related questions, like, "how often are they captured?"  One reason for timeout issues could be the large volume of segments having to be tracked and accounted for.  You're deleting snapshots after 7 days, but are you only capturing one every day, or more frequently?  How many indices are there in a given snapshot?

**Comment by niemyjski** [comment]
We are using curator 3.41 and elastic 1.7.5 with azure elastic 2.8.2. We never had a problem with a 30 second timeout in the past ever until about a month ago. Then it seems to time out.. As per our wiki we run backups hourly and every 12 hours depending on the indexes (big ones get it done every 12 hours).

Right now there are quite a few as they are backed up.. but even the ones with like 14 snapshots (12 hour ones) take forever and fail.

**Comment by untergeek** [comment]
That's kind of what I expected.  Hourly (and 12 hourly) snapshots on a cluster with time-series data can result in a _lot_ of segments that need to be kept.  Lots of segment checks is the subject of [this Elasticsearch issue](https://github.com/elastic/elasticsearch/issues/8958), which was corrected in [this merge](https://github.com/elastic/elasticsearch/pull/8969).

I do not believe the fix made it into the 1.7.x branch of Elasticsearch, but is only available in Elasticsearch 2+.  I looked through all of the release notes for all 1.7.x versions and could not find this issue, though I may still be wrong and they figured out how to back-port it.

I invite you to try snapshots from the command-line with curl and see if the same delay/timeout occurs.  I'm confident that the duration of time required for snapshots will be equally visible using this method.  Users of AWS and Azure have experienced these kinds of delays, especially associated with frequent snapshots, seemingly tied to the I/O latency associated with the remote filesystem, at least until the fix listed above was merged into the 2.x branch.

Related, informative bits:
https://github.com/elastic/elasticsearch-cloud-aws/issues/150
https://github.com/elastic/curator/issues/174#issuecomment-57056621 (Specifically the Thought Experiment and "No such thing as duplicates").

**Comment by niemyjski** [comment]
But we keep them in separate containers/folders in azure so it shouldn't be that bad. I've tried directly from sense and they do take a while to delete but getting the list is pretty quick. but is kinda slow when doing it from curator. We are still a few months away from upgrading to 2/3x.

**Comment by niemyjski** [comment]
I increased the timeout to 1200 seconds and it seems to help.. I just wonder if its blocking snapshot backups from running.

**Comment by niemyjski** [comment]
Looks like it's taking 11 minutes to delete a small snapshot (like really 400k docs on one index)

```sh
2016-03-18 15:57:18,914 INFO      Job starting: delete snapshots
2016-03-18 15:57:38,036 INFO      Deleting snapshot 2016-03-07-07-40
2016-03-18 16:08:03,681 INFO      Deleting snapshot 2016-03-07-08-40
```

**Comment by untergeek** [comment]
I can only point to the issues mentioned.  I don't know that separate containers/folders matters much.  It's the count of segments in a given _repository_ that matters.  The more there are, the longer things take, as in the previously linked issue, [Snapshot deletion and creation slow down as number of snapshots in repository grows](https://github.com/elastic/elasticsearch/issues/8958)

The fix is in Elasticsearch 2.0+.  

>I've tried directly from sense and they do take a while to delete but getting the list is pretty quick. but is kinda slow when doing it from curator.

The slowness of Curator pulling the list is something that can be improved, but is not the real issue here.  Look for improvements in the forthcoming Curator 4.0.  Unfortunately, it will not fix the slow delete issue described in this ticket.

**Comment by niemyjski** [comment]
Yeah, I get that, the thing is running commands from curator should be just as fast as curl. I really wish there was a way to time the delete of the same snapshot in both so I could see if there is any extra time spent.. Do you have a way to do a dry run of the delete?

**Comment by niemyjski** [comment]
I really appreciate your help!

**Comment by untergeek** [comment]
The `--dry-run` flag will only show what would be deleted, but you're welcome to give that a try.

**Comment by niemyjski** [comment]
I'll try that out.. I just noticed that I'm getting this exception now:

```sh
2016-03-18 21:34:33,685 INFO      Deleting snapshot 2016-03-06-16-30
Traceback (most recent call last):
  File "/usr/local/bin/curator", line 9, in <module>
    load_entry_point('elasticsearch-curator==3.4.1', 'console_scripts', 'curator')()
  File "/usr/local/lib/python2.7/dist-packages/curator/curator.py", line 5, in main
    cli( obj={ "filters": [] } )
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/curator/cli/snapshot_selection.py", line 93, in snapshots
    retval = delete_snapshot(client, snapshot=snap, repository=repository)
  File "/usr/local/lib/python2.7/dist-packages/curator/api/snapshot.py", line 123, in delete_snapshot
    client.snapshot.delete(repository=repository, snapshot=snapshot)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/client/utils.py", line 69, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/client/snapshot.py", line 40, in delete
    _make_path('_snapshot', repository, snapshot), params=params)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/transport.py", line 329, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/connection/http_urllib3.py", line 106, in perform_request
    self._raise_error(response.status, raw_data)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/connection/base.py", line 105, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.TransportError
```

**Comment by niemyjski** [comment]
Wonder if this is caused by any shapshots that are currently in the process of being deleted and curator is calling delete on them.

**Comment by untergeek** [comment]
Hmmm.  There could be more information available from the `TransportError`, but it's not showing what it is because the exception isn't being fully logged.

A `TransportError` is likely to imply a 400 or 500 HTTP response, though.  Something upstream telling this request thread that it cannot proceed.  It _could_ be simultaneously running snapshots causing a collision, but it's hard to say without the error code.

**Comment by niemyjski** [comment]
Could we add more logging to this in a 3.4.2? I'd do a pull request but I haven't done Python in over a decade

Sent from Outlook Mobile




On Fri, Mar 18, 2016 at 3:12 PM -0700, "Aaron Mildenstein" <notifications@github.com> wrote:












Hmmm.  There could be more information available from the TransportError, but it's not showing what it is because the exception isn't being fully logged.



A TransportError is likely to imply a 400 or 500 HTTP response, though.  Something upstream telling this request thread that it cannot proceed.  It could be simultaneously running snapshots causing a collision, but it's hard to say without the error code.

**Comment by untergeek** [comment]
I can try.  There's another bug or two I need to address to release 3.5.1, and I _may_ get to it as early as Monday, if I'm lucky.

**Comment by niemyjski** [comment]
Thanks for the patch, I'll try it out!

**Comment by niemyjski** [comment]
After updating I just ran into this issue:

```
No snapshots matched provided args.
2016-03-22 13:09:27,831 INFO      Job starting: delete snapshots
2016-03-22 13:09:56,698 INFO      Deleting snapshot 2016-03-08-11-30
2016-03-22 13:26:57,826 INFO      Deleting snapshot 2016-03-08-12-30
2016-03-22 13:43:07,548 INFO      Deleting snapshot 2016-03-08-13-30
Traceback (most recent call last):
  File "/usr/local/bin/curator", line 9, in <module>
    load_entry_point('elasticsearch-curator==3.5.1', 'console_scripts', 'curator')()
  File "/usr/local/lib/python2.7/dist-packages/curator/curator.py", line 5, in main
    cli( obj={ "filters": [] } )
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/curator/cli/snapshot_selection.py", line 93, in snapshots
    retval = delete_snapshot(client, snapshot=snap, repository=repository)
  File "/usr/local/lib/python2.7/dist-packages/curator/api/snapshot.py", line 126, in delete_snapshot
    logger.error("Unable to delete snapshot {0} from repository {1}. Error message: {2}.   Run with --debug flag and/or check Elasticsearch logs for more information.".format(snapshot, repository, e))
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/exceptions.py", line 55, in __str__
    cause = ', %r' % self.info['error']['root_cause'][0]['reason']
TypeError: string indices must be integers
```

**Comment by untergeek** [comment]
You are definitely hitting something strange.  I'm not even attempting to pull an indexed item.  Line 126 of snapshot.py looks like this:

```
logger.error("Unable to delete snapshot {0} from repository {1}. Error message: {2}.   Run with --debug flag and/or check Elasticsearch logs for more information.".format(snapshot, repository, e))
```

What this means is that the _elasticsearch_ python module is having a hard time parsing the response, as it received something it did not expect.

**Comment by untergeek** [comment]
Do you see any errors logged in Elasticsearch (particularly the elected master node, and/or the client that Curator connected to) at the time this ran?

I'm wondering if any plugins/modules you have extended Elasticsearch with may have changed responses, and it's breaking the elasticsearch python module's rules, since it is not what Elasticsearch should be sending back.  What plugins/modules have you added to Elasticsearch (besides Azure)?

**Comment by niemyjski** [comment]
I narrowed it down with the debug flag:

```
2016-03-22 14:50:11,964 DEBUG         urllib3.util.retry               from_int:156  Converted retries value: False -> Retry(total=False, connect=None, read=None, redirect=0)
2016-03-22 14:50:11,965 DEBUG     urllib3.connectionpool          _make_request:386  "DELETE /_snapshot/ex_organizations/2016-03-08-17-30 HTTP/1.1" 503 150
2016-03-22 14:50:11,966 WARNING            elasticsearch       log_request_fail:82   DELETE /_snapshot/ex_organizations/2016-03-08-17-30 [status:503 request:0.002s]
2016-03-22 14:50:11,966 DEBUG              elasticsearch       log_request_fail:90   > None
2016-03-22 14:50:11,966 DEBUG              elasticsearch       log_request_fail:93   < {"error":"ConcurrentSnapshotExecutionException[[ex_organizations:2016-03-08-17-30] another snapshot is currently running cannot delete]","status":503}
Traceback (most recent call last):
  File "/usr/local/bin/curator", line 9, in <module>
    load_entry_point('elasticsearch-curator==3.5.1', 'console_scripts', 'curator')()
  File "/usr/local/lib/python2.7/dist-packages/curator/curator.py", line 5, in main
    cli( obj={ "filters": [] } )
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/curator/cli/snapshot_selection.py", line 93, in snapshots
    retval = delete_snapshot(client, snapshot=snap, repository=repository)
  File "/usr/local/lib/python2.7/dist-packages/curator/api/snapshot.py", line 126, in delete_snapshot
    logger.error("Unable to delete snapshot {0} from repository {1}. Error message: {2}.   Run with --debug flag and/or check Elasticsearch logs for more information.".format(snapshot, repository, e))
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/exceptions.py", line 55, in __str__
    cause = ', %r' % self.info['error']['root_cause'][0]['reason']
TypeError: string indices must be integers
```

**Comment by niemyjski** [comment]
We don't have any other plugins other then hq, sense, and azure. I think from the log right before this happened. We get the bad response when a snapshot is running from another process / machine and it can't delete it. Should this snapshot be skipped and we continue deleting and we boil this message up to the end user?

**Comment by niemyjski** [comment]
Or do snapshots need to be deleted in sequence so it knows what files to cleanup?

**Comment by untergeek** [comment]
I just spoke with the developer/maintainer of the elasticsearch python module.  He says this is a minor reverse incompatibility issue between es-py module 2.x when using a 1.x version of Elasticsearch.  As you can see, Curator does everything it can to be fully reverse compatible, but this is a limitation specifically with this release of Curator, which _depends_ on es-py 2.3.0.  We won't be able to see what's really going on until you're on Elasticsearch 2.x

As far as this goes, I can put checks in to see if a snapshot is in progress before attempting a delete, but this feature will not go into Curator 3.x.  The 3.x branch is bug fixes only now, and I'm working on a 4.0 release.  4.0 will not have guaranteed reverse compatibility with all 1.x versions of ES, but will hopefully work with 1.7 still.  When Curator 5.0 comes out, it will be version-tied to Elasticsearch 5.0, and all subsequent releases will be major-version-bound.

In the meanwhile, you could do some shell scripting to see if a snapshot is in progress using curl calls (or something like it) before running Curator to achieve the same effect.

**Comment by niemyjski** [comment]
that check would be good, We are telling curator to delete the last 7 days so it might be hard to add an if check to our scripts.

**Comment by untergeek** [comment]
4.0 is a few weeks away, at least, so I recommend finding some way to handle this in the meanwhile.
