### ISSUE TITLE
Timeout during sealing indices leading to TypeError

### ISSUE THREAD

**Issue by ferki** [elastic/curator#583]
While using curator-3.4.1 we can see this error while trying to do a synced flush:
```
~ # /usr/bin/curator --master-only --logfile /var/log/curator.log seal indices --prefix REDACTED --timestring \%Y.\%m.\%d.\%H --time-unit hours --older-than 24
Traceback (most recent call last):
  File "/usr/lib/python-exec/python2.7/curator", line 9, in <module>
    load_entry_point('elasticsearch-curator==3.4.1', 'console_scripts', 'curator')()
  File "/usr/lib64/python2.7/site-packages/curator/curator.py", line 5, in main
    cli( obj={ "filters": [] } )
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/curator/cli/index_selection.py", line 166, in indices
    retval = do_command(client, ctx.parent.info_name, l, ctx.parent.params, master_timeout)
  File "/usr/lib64/python2.7/site-packages/curator/cli/utils.py", line 240, in do_command
    return seal(client, indices)
  File "/usr/lib64/python2.7/site-packages/curator/api/seal.py", line 63, in seal
    return seal_indices(client, indices)
  File "/usr/lib64/python2.7/site-packages/curator/api/seal.py", line 37, in seal_indices
    fails = [ i for i in sorted(results) if results[i]['failed'] > 0 ]
TypeError: sequence index must be integer, not 'str'
```

Increasing the number of indices it should touch also increases the likelyhood of this error (~~I guess because it is just more likely to have one of the indices return failure if there are more indices~~ because it's more likely that one of the requests will time out).

Update with debug output:
```
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/elasticsearch/connection/http_urllib3.py", line 78, in perform_request
    response = self.pool.urlopen(method, url, body, retries=False, headers=self.headers, **kw)
  File "/usr/lib64/python2.7/site-packages/urllib3/connectionpool.py", line 609, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib64/python2.7/site-packages/urllib3/util/retry.py", line 222, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/lib64/python2.7/site-packages/urllib3/connectionpool.py", line 559, in urlopen
    body=body, headers=headers)
  File "/usr/lib64/python2.7/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/lib64/python2.7/site-packages/urllib3/connectionpool.py", line 308, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
ReadTimeoutError: HTTPConnectionPool(host=u'localhost', port=9200): Read timed out. (read timeout=30)
2016-03-17 12:46:24,326 DEBUG              elasticsearch       log_request_fail:90   > None
2016-03-17 12:46:24,327 WARNING         curator.api.seal           seal_indices:30   Non-fatal error encountered.
2016-03-17 12:46:24,327 DEBUG           curator.api.seal           seal_indices:32   Error: TIMEOUT.  Message: HTTPConnectionPool(host=u'localhost', port=9200): Read timed out. (read timeout=30)
```

Might be related to and/or duplicate of #441.

**Comment by untergeek** [comment]
Thanks for reporting this.  It is quite likely that there needs to be a higher timeout for this operation.  Have you tried running with a higher timeout value than the default of 30 seconds?

**Comment by ferki** [comment]
> Have you tried running with a higher timeout value than the default of 30 seconds?

No, but I can reproduce it on pretty much every run by decreasing `--timeout`. So I guess increasing it is an easy solution, but I cannot test it as now my indices are sync flushed, it finishes quickly :)

I think trying to make the error message a bit more friendly would be enough (e.g. if it's a timeout problem, I'd prefer a message about timing out, not TypeError :), but increasing the default timeout for seal operations might also be useful.

**Comment by ferki** [comment]
@untergeek: thank you!

**Comment by untergeek** [comment]
@ferki 3.5.1 is now in PyPI and the official elasticsearch repositories (CentOS and Debian-styles).  The Windows binaries are also updated, but the links will not show up in the documentation until the next doc-build cycle (could be an hour or so).
