### ISSUE TITLE
default name is not available

### ISSUE THREAD

**Issue by rhorii** [elastic/curator#584]
default name is not available :scream: 

```
$ curator snapshot --repository s3_repository indices --all-indices
Traceback (most recent call last):
  File "/usr/bin/curator", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/dist-packages/curator/curator.py", line 5, in main
    cli( obj={ "filters": [] } )
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 1057, in invoke
    Command.invoke(self, ctx)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/curator/cli/snapshot.py", line 46, in snapshot
    if any(c.isupper() for c in name):
TypeError: 'NoneType' object is not utterable
```

**Comment by rhorii** [comment]
@untergeek Thank you!

**Comment by untergeek** [comment]
@rhorii Thanks for reporting it.  3.5.1 is released now, so please download and make use of it.
