### ISSUE TITLE
Connection Failure - Windows Binary

### ISSUE THREAD

**Issue by Jakauppila** [elastic/curator#599]
Using Curator 3.5.1 with the Windows binary, I'm getting a connection failure trying to just connect and show indices prior to making my delete commands.

We are running ES 2.3.1 with Shield and configured with SSL. Below is the command ran with the debug output. 

The thing that sticks out to me is the failed request getting logged is http rather than https even though I'm specifying `--use_ssl`

`2016-04-22 15:26:42,408 WARNING            elasticsearch       log_request_fail:82   GET http://elasticsearch.contoso.com:9200/ [status:N/A request:0.006s]`

```
C:\Curator\curator-3.5.1-win32>curator.exe --use_ssl --host elasticsearch.contoso.com --port 9200 --http_auth USERNAME:PASSWORD --debugshow indices --timestring '%Y.%m.%d'
2016-04-22 15:26:41,648 DEBUG         curator.api.filter         get_date_regex:157  regex = \'\d{4}\.\d{2}\.\d{2}\'
2016-04-22 15:26:41,650 INFO      curator.cli.index_selection                indices:62   Job starting: show indices
2016-04-22 15:26:41,651 DEBUG     curator.cli.index_selection                indices:65   Params: {'url_prefix': u'', 'http_auth': u'USERNAME:PASSWORD', 'dry_run': False, 'certificate': None, 'loglevel': u'INFO', 'logformat': u'default', 'client_cert': None, 'host': u'elasticsearch.contoso.com', 'quiet': False, 'timeout': 30, 'debug': True, 'use_ssl': True, 'logfile': None, 'master_only': False, 'port': 9200, 'ssl_no_validate': False, 'client_key': None}
2016-04-22 15:26:41,654 DEBUG          curator.cli.utils             get_client:114  kwargs = {'url_prefix': u'', 'http_auth': u'USERNAME:PASSWORD', 'dry_run': False, 'certificate': None, 'loglevel': u'INFO', 'host': u'elasticsearch.contoso.com', 'quiet': False, 'port': 9200, 'logformat': u'default', 'timeout': 30, 'debug': True, 'use_ssl': True, 'logfile': None, 'master_only': False, 'client_cert': None, 'ssl_no_validate': False, 'client_key': None}
2016-04-22 15:26:41,657 INFO           curator.cli.utils             get_client:120  Attempting to verify SSL certificate.
2016-04-22 15:26:41,658 DEBUG         urllib3.util.retry               from_int:156  Converted retries value: False -> Retry(total=False, connect=None, read=None, redirect=0)
2016-04-22 15:26:41,660 INFO      urllib3.connectionpool              _new_conn:757  Starting new HTTPS connection (1): elasticsearch.contoso.com
2016-04-22 15:26:42,361 WARNING            elasticsearch       log_request_fail:82   GET http://elasticsearch.contoso.com:9200/ [status:N/A request:0.702s]
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\elasticsearch\connection\http_urllib3.py", line 78, in perform_request
  File "C:\Python27\lib\site-packages\urllib3\connectionpool.py", line 558, in urlopen
  File "C:\Python27\lib\site-packages\urllib3\connectionpool.py", line 345, in _make_request
  File "C:\Python27\lib\site-packages\urllib3\connectionpool.py", line 783, in _validate_conn
  File "C:\Python27\lib\site-packages\urllib3\connection.py", line 252, in connect
  File "C:\Python27\lib\site-packages\urllib3\util\ssl_.py", line 295, in ssl_wrap_socket
SSLError: [Errno 2] No such file or directory
2016-04-22 15:26:42,368 DEBUG              elasticsearch       log_request_fail:90   > None
2016-04-22 15:26:42,369 DEBUG         urllib3.util.retry               from_int:156  Converted retries value: False -> Retry(total=False, connect=None, read=None, redirect=0)
2016-04-22 15:26:42,371 INFO      urllib3.connectionpool              _new_conn:757  Starting new HTTPS connection (2): elasticsearch.contoso.com
2016-04-22 15:26:42,377 WARNING            elasticsearch       log_request_fail:82   GET http://elasticsearch.contoso.com:9200/ [status:N/A request:0.007s]
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\elasticsearch\connection\http_urllib3.py", line 78, in perform_request
  File "C:\Python27\lib\site-packages\urllib3\connectionpool.py", line 558, in urlopen
  File "C:\Python27\lib\site-packages\urllib3\connectionpool.py", line 345, in _make_request
  File "C:\Python27\lib\site-packages\urllib3\connectionpool.py", line 783, in _validate_conn
  File "C:\Python27\lib\site-packages\urllib3\connection.py", line 252, in connect
  File "C:\Python27\lib\site-packages\urllib3\util\ssl_.py", line 295, in ssl_wrap_socket
SSLError: [Errno 2] No such file or directory
2016-04-22 15:26:42,384 DEBUG              elasticsearch       log_request_fail:90   > None
2016-04-22 15:26:42,387 DEBUG         urllib3.util.retry               from_int:156  Converted retries value: False -> Retry(total=False, connect=None, read=None, redirect=0)
2016-04-22 15:26:42,388 INFO      urllib3.connectionpool              _new_conn:757  Starting new HTTPS connection (3): elasticsearch.contoso.com
2016-04-22 15:26:42,394 WARNING            elasticsearch       log_request_fail:82   GET http://elasticsearch.contoso.com:9200/ [status:N/A request:0.007s]
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\elasticsearch\connection\http_urllib3.py", line 78, in perform_request
  File "C:\Python27\lib\site-packages\urllib3\connectionpool.py", line 558, in urlopen
  File "C:\Python27\lib\site-packages\urllib3\connectionpool.py", line 345, in _make_request
  File "C:\Python27\lib\site-packages\urllib3\connectionpool.py", line 783, in _validate_conn
  File "C:\Python27\lib\site-packages\urllib3\connection.py", line 252, in connect
  File "C:\Python27\lib\site-packages\urllib3\util\ssl_.py", line 295, in ssl_wrap_socket
SSLError: [Errno 2] No such file or directory
2016-04-22 15:26:42,401 DEBUG              elasticsearch       log_request_fail:90   > None
2016-04-22 15:26:42,403 DEBUG         urllib3.util.retry               from_int:156  Converted retries value: False -> Retry(total=False, connect=None, read=None, redirect=0)
2016-04-22 15:26:42,404 INFO      urllib3.connectionpool              _new_conn:757  Starting new HTTPS connection (4): elasticsearch.contoso.com
2016-04-22 15:26:42,408 WARNING            elasticsearch       log_request_fail:82   GET http://elasticsearch.contoso.com:9200/ [status:N/A request:0.006s]
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\elasticsearch\connection\http_urllib3.py", line 78, in perform_request
  File "C:\Python27\lib\site-packages\urllib3\connectionpool.py", line 558, in urlopen
  File "C:\Python27\lib\site-packages\urllib3\connectionpool.py", line 345, in _make_request
  File "C:\Python27\lib\site-packages\urllib3\connectionpool.py", line 783, in _validate_conn
  File "C:\Python27\lib\site-packages\urllib3\connection.py", line 252, in connect
  File "C:\Python27\lib\site-packages\urllib3\util\ssl_.py", line 295, in ssl_wrap_socket
SSLError: [Errno 2] No such file or directory
2016-04-22 15:26:42,417 DEBUG              elasticsearch       log_request_fail:90   > None
2016-04-22 15:26:42,417 ERROR          curator.cli.utils             get_client:140  Connection failure.
```

**Comment by untergeek** [comment]
Can you share your whole command line?

**Comment by Jakauppila** [comment]
`curator.exe --use_ssl --host elasticsearch.contoso.com --port 9200 --http_auth USERNAME:PASSWORD --debugshow indices --timestring '%Y.%m.%d'`

**Comment by untergeek** [comment]
This debug output seems to be missing something.  Could you paste the first part, where the client gets built?

**Comment by Jakauppila** [comment]
I wrote the output to a file instead, still only seeing the same info as above:

https://gist.github.com/Jakauppila/113a4d6aee761e6934e5b89bc5e5ef79

**Comment by Jakauppila** [comment]
So I pulled down the dependencies and used Curator via Python and that worked correctly, so I'm assuming it may just be a problem with the built binary?

**Comment by untergeek** [comment]
That's actually somewhat of a relief.  I'll investigate my build system and see what I can find.  I may share test binaries with you once I've built them.  It won't be before next week, though.

**Comment by Jakauppila** [comment]
Sounds good. Thanks.

I'd also be interested in testing out the v4 alphas, any chance the binary could be built for those releases?

**Comment by untergeek** [comment]
They should be out on Monday, though they may suffer from the same SSL issue as I haven't updated my build computer yet.

**Comment by untergeek** [comment]
I've updated the Windows downloads for Curator 3.5.1.  I tested them against Shield so they should work for you.

Wait until about 20 minutes from now and the links for Curator 4.0.0a7 should be available at the bottom of the page: https://www.elastic.co/guide/en/elasticsearch/client/curator/4.0/installation.html

If they still say 4.0.0a2, then it hasn't updated yet.

**Comment by untergeek** [comment]
Since I've pushed the fixed binaries, I'm closing this.

**Comment by Jakauppila** [comment]
Did you test them with Shield and SSL? Looks like I'm getting the same error on the updated 3.5.1 binaries:

https://gist.github.com/Jakauppila/fed762c773f2a14d7a1c9e61261c3785

Interestingly enough, it looks like it's working with the 4.0.0.a8 binary with the following command `curator.exe --config "config\config.txt" "config\action.txt"` and the below config files:

https://gist.github.com/Jakauppila/19beb387c9d4346389f097993d094165

**Comment by untergeek** [comment]
Yes.  This is what I tried with my test Shield + SSL setup with the fixed win32 binary.  It most certainly connects over SSL because that's all it allows.  Note that it still says it's using http.  This is not the case.  I'm not sure why it still says SSL, but it's not.  If I try to curl this host with http it fails with an empty response, but with an https it does connect.

Here's the output from mine:
```
C:\Users\Admin User\Downloads\curator-3.5.1-win32>curator.exe --debug --host steiny --use_ssl --ssl-no-validate --http_auth buh:changemenow show indices --all-indices
2016-04-26 18:12:54,523 INFO      curator.cli.index_selection                indices:62   Job starting: show indices
2016-04-26 18:12:54,539 DEBUG     curator.cli.index_selection                indices:65   Params: {'url_prefix': u'', 'http_auth': u'buh:changemenow', 'dry_run': False, 'certificate': None, 'loglevel': u'INFO', 'logformat': u'default', 'client_cert': None, 'host': u'steiny', 'quiet': False, 'timeout': 30, 'debug': True, 'use_ssl': True, 'logfile': None, 'master_only': False, 'port': 9200, 'ssl_no_validate': True, 'client_key': None}
2016-04-26 18:12:54,571 DEBUG          curator.cli.utils             get_client:114  kwargs = {'url_prefix': u'', 'http_auth': u'buh:changemenow', 'dry_run': False, 'certificate': None, 'loglevel': u'INFO', 'host': u'steiny', 'quiet': False, 'port': 9200, 'logformat': u'default', 'timeout': 30, 'debug': True, 'use_ssl': True, 'logfile': None, 'master_only': False, 'client_cert': None, 'ssl_no_validate': True, 'client_key': None}
C:\Users\Admin User\Downloads\curator-3.5.1-win32\library.zip\elasticsearch\connection\http_urllib3.py:70: UserWarning: Connecting to steiny using SSL with verify_certs=False is insecure.
2016-04-26 18:12:54,632 DEBUG         urllib3.util.retry               from_int:164  Converted retries value: False -> Retry(total=False, connect=None, read=None, redirect=0)
2016-04-26 18:12:54,648 INFO      urllib3.connectionpool              _new_conn:788  Starting new HTTPS connection (1): steiny
C:\Users\Admin User\Downloads\curator-3.5.1-win32\library.zip\urllib3\connectionpool.py:821: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
2016-04-26 18:12:55,648 DEBUG     urllib3.connectionpool          _make_request:395  "GET / HTTP/1.1" 200 333
2016-04-26 18:12:55,664 INFO               elasticsearch    log_request_success:63   GET http://steiny:9200/ [status:200 request:1.031s]
2016-04-26 18:12:55,680 DEBUG              elasticsearch    log_request_success:65   > None
2016-04-26 18:12:55,680 DEBUG              elasticsearch    log_request_success:66   < {
  "name" : "Gammenon the Gatherer",
  "cluster_name" : "untergeek-shield",
  "version" : {
    "number" : "2.3.1",
    "build_hash" : "bd980929010aef404e7cb0843e61d0665269fc39",
    "build_timestamp" : "2016-04-04T12:25:05Z",
    "build_snapshot" : false,
    "lucene_version" : "5.5.0"
  },
  "tagline" : "You Know, for Search"
}

2016-04-26 18:12:55,710 DEBUG          curator.cli.utils          check_version:90   Detected Elasticsearch version 2.3.1
2016-04-26 18:12:55,726 DEBUG         urllib3.util.retry               from_int:164  Converted retries value: False -> Retry(total=False, connect=None, read=None, redirect=0)
C:\Users\Admin User\Downloads\curator-3.5.1-win32\library.zip\urllib3\connectionpool.py:821: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
2016-04-26 18:12:55,773 DEBUG     urllib3.connectionpool          _make_request:395  "GET /_all/_settings?expand_wildcards=open%2Cclosed HTTP/1.1" 200 180
2016-04-26 18:12:55,789 INFO               elasticsearch    log_request_success:63   GET http://steiny:9200/_all/_settings?expand_wildcards=open%2Cclosed [status:200 request:0.062s]
2016-04-26 18:12:55,805 DEBUG              elasticsearch    log_request_success:65   > None
2016-04-26 18:12:55,821 DEBUG              elasticsearch    log_request_success:66   < {"myindex":{"settings":{"index":{"creation_date":"1461626021151","number_of_shards":"1","number_of_replicas":"0","uuid":"eeFVMuijT46W_m7PR8MGkQ","version":{"created":"2030199"}}}}}
2016-04-26 18:12:55,851 DEBUG          curator.api.utils            get_indices:29   All indices: [u'myindex']
2016-04-26 18:12:55,851 DEBUG     curator.cli.index_selection                indices:81   Full list of indices: [u'myindex']
2016-04-26 18:12:55,868 INFO      curator.cli.index_selection                indices:101  Matching all indices. Ignoring flags other than --exclude.
2016-04-26 18:12:55,882 DEBUG     curator.cli.index_selection                indices:103  All filters: []
2016-04-26 18:12:55,882 INFO      curator.cli.index_selection                indices:149  Action show will be performed on the following indices: [u'myindex']
2016-04-26 18:12:55,898 INFO      curator.cli.index_selection                indices:153  Matching indices:
2016-04-26 18:12:55,914 DEBUG         urllib3.util.retry               from_int:164  Converted retries value: False -> Retry(total=False, connect=None, read=None, redirect=0)
C:\Users\Admin User\Downloads\curator-3.5.1-win32\library.zip\urllib3\connectionpool.py:821: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
2016-04-26 18:12:55,976 DEBUG     urllib3.connectionpool          _make_request:395  "GET /_cluster/state/metadata/myindex HTTP/1.1" 200 318
2016-04-26 18:12:55,993 INFO               elasticsearch    log_request_success:63   GET http://steiny:9200/_cluster/state/metadata/myindex [status:200 request:0.079s]
2016-04-26 18:12:55,993 DEBUG              elasticsearch    log_request_success:65   > None
2016-04-26 18:12:56,007 DEBUG              elasticsearch    log_request_success:66   < {"cluster_name":"untergeek-shield","metadata":{"cluster_uuid":"_na_","templates":{},"indices":{"myindex":{"state":"open","settings":{"index":{"creation_date":"1461626021151","number_of_shards":"1","number_of_replicas":"0","uuid":"eeFVMuijT46W_m7PR8MGkQ","version":{"created":"2030199"}}},"mappings":{},"aliases":[]}}}}
myindex

C:\Users\Admin User\Downloads\curator-3.5.1-win32>
```

**Comment by Jakauppila** [comment]
Looking back at the commands I supplied above, it looks like I wasn't supplying the cert or `--ssl-no-validate`

**Comment by untergeek** [comment]
Also, if you note the logs, it says, `Starting new HTTPS connection (1): elasticsearch.contoso.com`, so it _was_ trying to start an HTTPS connection.

**Comment by Jakauppila** [comment]
Yep, It looks like the actual error was just obscured in the debug messaging.

`curator.exe --host elasticsearch.contoso.com --use_ssl --port 9200 --http_auth USERNAME:PASSWORD show indices --timestring '%Y.%m.%d'`

Output without debug:
```
2016-04-27 09:25:32,713 INFO      Job starting: show indices
2016-04-27 09:25:32,713 INFO      Attempting to verify SSL certificate.
2016-04-27 09:25:33,365 ERROR     Connection failure.
```
Sorry for wasting your time.
