### ISSUE TITLE
Error deleting indices

### ISSUE THREAD

**Issue by reqless** [elastic/curator#638]
Command :: 

sudo curator --master-only --logfile /var/log/deletelog.log delete indices --time-unit days --older-then 30 --timestring %Y.%m.%d

It takes a while and then finishes. It does not delete any indices.

The log file says the following ::

2016-05-25 19:54:23,658 ERROR     Error deleting one or more indices.  Run with --debug flag and/or check Elasticsearch logs for more information.
2016-05-25 19:54:23,658 ERROR     Got a TIMEOUT response from Elasticsearch.  Error message: HTTPConnectionPool(host=u'localhost', port=9200): Read timed out. (read timeout=30)

Some Elasticsearch Logs ::

[2016-05-25 20:10:41,498][DEBUG][action.admin.indices.delete] [Prod1] [ad-mssql-2016.03.27] failed to delete index
ProcessClusterEventTimeoutException[failed to process cluster event (delete-index [ad-mssql-2016.03.27]) within 30s]
        at org.elasticsearch.cluster.service.InternalClusterService$2$1.run(InternalClusterService.java:290)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
[2016-05-25 20:10:41,498][DEBUG][action.admin.indices.delete] [Prod1] [ad-app-sharepoint-2016.04.04] failed to delete index
ProcessClusterEventTimeoutException[failed to process cluster event (delete-index [ad-app-sharepoint-2016.04.04]) within 30s]
        at org.elasticsearch.cluster.service.InternalClusterService$2$1.run(InternalClusterService.java:290)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
[2016-05-25 20:10:41,498][DEBUG][action.admin.indices.delete] [Prod1] [ad-iis-2016.04.23] failed to delete index
ProcessClusterEventTimeoutException[failed to process cluster event (delete-index [ad-iis-2016.04.23]) within 30s]
        at org.elasticsearch.cluster.service.InternalClusterService$2$1.run(InternalClusterService.java:290)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

Any ideas?

**Comment by iainlbc** [comment]
Relevant: https://discuss.elastic.co/t/timeouts-while-deleting/24564/24

-- 
Iain Wright

This email message is confidential, intended only for the recipient(s)
named above and may contain information that is privileged, exempt from
disclosure under applicable law. If you are not the intended recipient, do
not disclose or disseminate the message to anyone except the intended
recipient. If you have received this message in error, or are not the named
recipient(s), please immediately notify the sender by return email, and
delete all copies of this message.

**Comment by untergeek** [comment]
Indeed, as @iainlbc pointed out.  You should increase your `--timeout` setting.
