### ISSUE TITLE
Error when signing AWS requests

### ISSUE THREAD

**Issue by shavo007** [elastic/curator#679]
Hey mate,

Follow on from my tweet post  [tweet!](https://twitter.com/shavo27/status/747277806023761921) to create a docker image on curator 4, i decided to try and add in signing aws requests.

I have updated the docker file to install the module requests-aws4auth.

You can find the github project here: [dockerFile](https://github.com/shavo007/docker-es-curator-cron).

Curator version is 4.0.1
I have free tier account with aws and created an es cluster (btw version of aws es is 1.5.2)

Endpoint for example is search-sl-es-cluster-xyz.ap-southeast-2.es.amazonaws.com

I then downloaded the credentials for IAM user. I configured my aws client locally and i can run the command below successfully:
```
aws es list-domain-names

```

I have configured the values in curator.yml .

Example is below:

```
---
# Remember, leave a key empty if there is no value.  None will be a string,
# not a Python "NoneType"
client:
  hosts:
    - "search-sl-es-cluster-xyz.ap-southeast-2.es.amazonaws.com:9200"
  port: 9200
  url_prefix:
  use_ssl: False
  certificate:
  client_cert:
  client_key:
  aws_key: "XYZ"
  aws_secret_key: "XYZAQ"
  aws_region: "ap-southeast-2"
  ssl_no_validate: False
  http_auth:
  timeout: 30
  master_only: False

logging:
  loglevel: INFO
  logfile:  /usr/share/curator/curator.log
  logformat: default

```

When I try and run a curator action, I get the following error:

```
curator --config config/curator.yml config/create_location_index_curator.yml

```

```
Traceback (most recent call last):
  File "/usr/bin/curator", line 9, in <module>
    load_entry_point('elasticsearch-curator==4.0.1', 'console_scripts', 'curator')()
  File "/usr/lib/python2.7/site-packages/curator/curator.py", line 5, in main
    cli()
  File "/usr/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/curator/cli.py", line 215, in cli
    client = get_client(**client_args)
  File "/usr/lib/python2.7/site-packages/curator/utils.py", line 537, in get_client
    kwargs['region'], 'es')
  File "/usr/lib/python2.7/site-packages/requests_aws4auth/aws4auth.py", line 247, in __init__
    self.regenerate_signing_key(secret_key=secret_key)
  File "/usr/lib/python2.7/site-packages/requests_aws4auth/aws4auth.py", line 302, in regenerate_signing_key
    store_secret_key)
  File "/usr/lib/python2.7/site-packages/requests_aws4auth/aws4signingkey.py", line 97, in __init__
    self.service, self.date)
  File "/usr/lib/python2.7/site-packages/requests_aws4auth/aws4signingkey.py", line 116, in generate_key
    region_key = cls.sign_sha256(date_key, region)
  File "/usr/lib/python2.7/site-packages/requests_aws4auth/aws4signingkey.py", line 136, in sign_sha256
    return hmac.new(key, msg, hashlib.sha256).digest()
  File "/usr/lib/python2.7/hmac.py", line 136, in new
    return HMAC(key, msg, digestmod)
  File "/usr/lib/python2.7/hmac.py", line 78, in __init__
    self.update(msg)
  File "/usr/lib/python2.7/hmac.py", line 86, in update
    self.inner.update(msg)
TypeError: update() argument 1 must be string or buffer, not bool
```

Any clue!?

Thanks,
Shane.

**Comment by untergeek** [comment]
Thanks for reporting.  The feature is experimental, as it was listed as such in the 4.0.0 release notes.

Can you please run with the `loglevel` set to `DEBUG` and attach the file here?

One thing I noticed is that you have `use_ssl` set to `False`, but if I recall correctly, it must be set to `True`, as the AWS signing is SSL.

**Comment by untergeek** [comment]
Also, see: https://www.elastic.co/guide/en/elasticsearch/client/curator/current/configfile.html#aws_key

> You must set your hosts to the proper hostname _with_ port. It may not work setting port and hosts to only a host name due to the different connection module used.

This means your configuration file should look like:

> ```---
# Remember, leave a key empty if there is no value.  None will be a string,
# not a Python "NoneType"
client:
  hosts:
    - "search-sl-es-cluster-xyz.ap-southeast-2.es.amazonaws.com:9200"
  port:
```

Note that `port` is empty.

**Comment by shavo007** [comment]
Thanks for the reply mate. So i changed the config to be like so:



```
---
# Remember, leave a key empty if there is no value.  None will be a string,
# not a Python "NoneType"
client:
  hosts:
    - "search-sl-es-cluster-xyz.ap-southeast-2.es.amazonaws.com:9200"
  port:
  url_prefix:
  use_ssl: False
  certificate:
  client_cert:
  client_key:
  aws_key: "xyz"
  aws_secret_key: "xyz"
  aws_region: "ap-southeast-2"
  ssl_no_validate: False
  http_auth:
  timeout: 30
  master_only: False

logging:
  loglevel: DEBUG
  logfile:  /usr/share/curator/curator.log
  logformat: default


```

I removed the port.

I run the command 
```
curator --config config/curator.yml config/create
_location_index_curator.yml
```

The logs are:

```
2016-07-04 12:06:40,999 DEBUG                curator.cli                    cli:165  default_timeout = 30
2016-07-04 12:06:41,005 DEBUG                curator.cli                    cli:170  Full list of actions: {1: {'action': 'create_index', 'description': 'Create the index as named, with the specified extra settings.', 'options': {'continue_if_exception': False, 'extra_settings': {'mappings': {'type1': {'properties': {'field1': {'index': 'not_analyzed', 'type': 'string'}}}}, 'settings': {'number_of_replicas': 1, 'number_of_shards': 1}}, 'timeout_override': None, 'name': 'locations', 'disable_action': False}}}
2016-07-04 12:06:41,005 INFO                 curator.cli                    cli:177  Action #1: create_index
2016-07-04 12:06:41,005 DEBUG                curator.cli                    cli:190  continue_if_exception = False
2016-07-04 12:06:41,005 DEBUG                curator.cli                    cli:191  timeout_override = None
2016-07-04 12:06:41,006 DEBUG              curator.utils             get_client:497  kwargs = {'aws_secret_key': 'xyz', 'url_prefix': '', 'http_auth': None, 'certificate': None, 'aws_key': 'xyz', 'aws_region': 'ap-southeast-2', 'client_cert': None, 'hosts': ['search-sl-es-cluster-xyz.ap-southeast-2.es.amazonaws.com:9200'], 'timeout': 30, 'use_ssl': False, 'master_only': False, 'port': 9200, 'ssl_no_validate': False, 'client_key': None}



```

Console error is:

```
Traceback (most recent call last):
  File "/usr/bin/curator", line 9, in <module>
    load_entry_point('elasticsearch-curator==4.0.1', 'console_scripts', 'curator')()
  File "/usr/lib/python2.7/site-packages/curator/curator.py", line 5, in main
    cli()
  File "/usr/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/curator/cli.py", line 215, in cli
    client = get_client(**client_args)
  File "/usr/lib/python2.7/site-packages/curator/utils.py", line 537, in get_client
    kwargs['region'], 'es')
  File "/usr/lib/python2.7/site-packages/requests_aws4auth/aws4auth.py", line 247, in __init__
    self.regenerate_signing_key(secret_key=secret_key)
  File "/usr/lib/python2.7/site-packages/requests_aws4auth/aws4auth.py", line 302, in regenerate_signing_key
    store_secret_key)
  File "/usr/lib/python2.7/site-packages/requests_aws4auth/aws4signingkey.py", line 97, in __init__
    self.service, self.date)
  File "/usr/lib/python2.7/site-packages/requests_aws4auth/aws4signingkey.py", line 116, in generate_key
    region_key = cls.sign_sha256(date_key, region)
  File "/usr/lib/python2.7/site-packages/requests_aws4auth/aws4signingkey.py", line 136, in sign_sha256
    return hmac.new(key, msg, hashlib.sha256).digest()
  File "/usr/lib/python2.7/hmac.py", line 136, in new
    return HMAC(key, msg, digestmod)
  File "/usr/lib/python2.7/hmac.py", line 78, in __init__
    self.update(msg)
  File "/usr/lib/python2.7/hmac.py", line 86, in update
    self.inner.update(msg)
TypeError: update() argument 1 must be string or buffer, not bool

```

Any clue!?

Thanks,
Shane.

**Comment by untergeek** [comment]
The [original issue](https://github.com/elastic/curator/issues/566) that lead to this feature says that [the port needs to be `443`](https://github.com/servomac/curator/blob/aws/curator/cli/utils.py#L147).  It also appears that [I did not get the `host` and `port` formatting correct](https://github.com/servomac/curator/blob/aws/curator/cli/utils.py#L146).

This suggests that the `hosts` entry in the config needs to be a single host, with no port assigned, the `port` entry needs to be `443`, and `kwargs['hosts'] = [{'host': kwargs['host'], 'port': 443}]` needs to be inserted [after line 530](https://github.com/elastic/curator/blob/master/curator/utils.py#L530) in `utils.py` in the source.

This is one of the parts of the code I could not test properly, as I do not have access to AWS instances for Curator, hence it was marked `Experimental`.  I appreciate you helping to track it down.

If this doesn't work, then it suggests to me that I need more debug log collection because the `TypeError: update()` message seems to indicate that 
```
File "/usr/lib/python2.7/site-packages/curator/utils.py", line 537, in get_client
    kwargs['region'], 'es')
```

is not getting the entire configuration line for some reason (though it's perfectly valid python):

```
            kwargs['http_auth'] = (
                AWS4Auth(
                    kwargs['aws_key'], kwargs['aws_secret_key'],
                    kwargs['region'], 'es')
            )
```

It may only be getting `kwargs['region'], 'es')` according to the error.  I am on holiday right now, and can only offer this much in a short break before heading back to the festivities.  I'll be back full time on Thursday, but may take more looks as time permits.

Thanks again!

**Comment by shavo007** [comment]
no problem at all!

It is not important. Enjoy your holiday. I just wanted to test it out with my docker image...

I did try below but still get the same error FYI:

```
hosts:
    - "search-sl-es-cluster-xyz.ap-southeast-2.es.amazonaws.com"
  port: 443

```

Speak again when you get back.

**Comment by untergeek** [comment]
It will still need the code modifications I suggested.  I will try to get you a patched version of `utils.py` when I get back so you can test it.

**Comment by shavo007** [comment]
No rush!

**Comment by porto88** [comment]
+1, running into this same issue.
Curator version 4.0.1, python 2.7

**Comment by kuttor** [comment]
Also having an issue with this... 

rator-actions.yml
2016-07-13 00:49:03,907 INFO      Action #1: snapshot
Traceback (most recent call last):
  File "/usr/local/bin/curator", line 9, in <module>
    load_entry_point('elasticsearch-curator==4.0.1', 'console_scripts', 'curator')()
  File "/usr/local/lib/python2.7/dist-packages/curator/curator.py", line 5, in main
    cli()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/curator/cli.py", line 215, in cli
    client = get_client(**client_args)
  File "/usr/local/lib/python2.7/dist-packages/curator/utils.py", line 537, in get_client
    kwargs['region'], 'es')
  File "/usr/local/lib/python2.7/dist-packages/requests_aws4auth/aws4auth.py", line 247, in __init__
    self.regenerate_signing_key(secret_key=secret_key)
  File "/usr/local/lib/python2.7/dist-packages/requests_aws4auth/aws4auth.py", line 302, in regenerate_signing_key
    store_secret_key)
  File "/usr/local/lib/python2.7/dist-packages/requests_aws4auth/aws4signingkey.py", line 97, in __init__
    self.service, self.date)
  File "/usr/local/lib/python2.7/dist-packages/requests_aws4auth/aws4signingkey.py", line 116, in generate_key
    region_key = cls.sign_sha256(date_key, region)
  File "/usr/local/lib/python2.7/dist-packages/requests_aws4auth/aws4signingkey.py", line 136, in sign_sha256
    return hmac.new(key, msg, hashlib.sha256).digest()
  File "/usr/lib/python2.7/hmac.py", line 133, in new
    return HMAC(key, msg, digestmod)
  File "/usr/lib/python2.7/hmac.py", line 75, in __init__
    self.update(msg)
  File "/usr/lib/python2.7/hmac.py", line 83, in update
    self.inner.update(msg)
TypeError: must be string or buffer, not bool

**Comment by untergeek** [comment]
Sorry to keep everyone waiting.  I'm at OpenWest the rest of this week.  I've been putting together a whopping 4 presentations for it, which has kept me completely busy. 

In the meanwhile, if someone wants to attempt some of the changes I outlined and submit a PR, or at least a branch to try, that would be terrific.

**Comment by kuttor** [comment]
I definitely will... Currently in my stack now tasked on getting this to function. 

Define the changes.

**Comment by kuttor** [comment]
"This suggests that the hosts entry in the config needs to be a single host, with no port assigned, the port entry needs to be 443, and kwargs['hosts'] = [{'host': kwargs['host'], 'port': 443}] needs to be inserted after line 530 in utils.py in the source."

**Comment by kuttor** [comment]
Already started.

**Comment by untergeek** [comment]
What's in [this comment](https://github.com/elastic/curator/issues/679#issuecomment-230288735)

And thanks!

**Comment by kuttor** [comment]
The line "kwargs['hosts'] = [{'host': kwargs['host'], 'port': 443}]" produced:

```
  File "/tmp/curator/curator/utils.py", line 531, in get_client
    kwargs['hosts'] = [{'host': kwargs['host'], 'port': 443}]
KeyError: 'host'
```
changed kwargs['host'] to kwargs['hosts'] which produced: 

> TypeError: must be string or buffer, not bool

Snip of code insert:


`          # Override these kwargs
            kwargs['hosts'] = [{'host': kwargs['hosts'], 'port': 443}]
            kwargs['use_ssl'] = True
            kwargs['verify_certs'] = True
            kwargs['connection_class'] = elasticsearch.RequestsHttpConnection
            kwargs['http_auth'] = (
                AWS4Auth(
                    kwargs['aws_key'], kwargs['aws_secret_key'],
                    kwargs['region'], 'es')
            )`

**Comment by untergeek** [comment]
Try changing:

```
kwargs['http_auth'] = (
            AWS4Auth(
                kwargs['aws_key'], kwargs['aws_secret_key'],
                kwargs['region'], 'es')
        )
```

to:

```
kwargs['http_auth'] = (AWS4Auth(kwargs['aws_key'], kwargs['aws_secret_key'],kwargs['region'], 'es'))
```

It appeared that one error was showing an incomplete line.

**Comment by untergeek** [comment]
er, make that:

```
kwargs['http_auth'] = AWS4Auth(kwargs['aws_key'], kwargs['aws_secret_key'],kwargs['region'], 'es')
```

**Comment by kuttor** [comment]
Traceback Snip: 
>    File "/tmp/curator/curator/utils.py", line 535, in get_client
>     kwargs['http_auth'] = AWS4Auth(kwargs['aws_key'], kwargs['aws_secret_key'],kwargs['region'], 'es')

Code Snip: 
>             # Override these kwargs
>             kwargs['hosts'] = [{'host': kwargs['hosts'], 'port': 443}]
>             kwargs['use_ssl'] = True
>             kwargs['verify_certs'] = True
>             kwargs['connection_class'] = elasticsearch.RequestsHttpConnection
>             kwargs['http_auth'] = AWS4Auth(kwargs['aws_key'], kwargs['aws_secret_key'],kwargs['region'], 'es')

**Comment by untergeek** [comment]
What's the rest of the error?

**Comment by kuttor** [comment]
> Traceback (most recent call last):
>   File "./run_curator.py", line 8, in <module>
>     main()
>   File "/tmp/curator/curator/curator.py", line 5, in main
>     cli()
>   File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 716, in __call__
>     return self.main(*args, **kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 696, in main
>     rv = self.invoke(ctx)
>   File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 889, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 534, in invoke
>     return callback(*args, **kwargs)
>   File "/tmp/curator/curator/cli.py", line 215, in cli
>     client = get_client(**client_args)
>   File "/tmp/curator/curator/utils.py", line 535, in get_client
>     kwargs['http_auth'] = AWS4Auth(kwargs['aws_key'], kwargs['aws_secret_key'],kwargs['region'], 'es')
>   File "/usr/local/lib/python2.7/dist-packages/requests_aws4auth/aws4auth.py", line 247, in __init__
>     self.regenerate_signing_key(secret_key=secret_key)
>   File "/usr/local/lib/python2.7/dist-packages/requests_aws4auth/aws4auth.py", line 302, in regenerate_signing_key
>     store_secret_key)
>   File "/usr/local/lib/python2.7/dist-packages/requests_aws4auth/aws4signingkey.py", line 97, in __init__
>     self.service, self.date)
>   File "/usr/local/lib/python2.7/dist-packages/requests_aws4auth/aws4signingkey.py", line 116, in generate_key
>     region_key = cls.sign_sha256(date_key, region)
>   File "/usr/local/lib/python2.7/dist-packages/requests_aws4auth/aws4signingkey.py", line 136, in sign_sha256
>     return hmac.new(key, msg, hashlib.sha256).digest()
>   File "/usr/lib/python2.7/hmac.py", line 133, in new
>     return HMAC(key, msg, digestmod)
>   File "/usr/lib/python2.7/hmac.py", line 75, in __init__
>     self.update(msg)
>   File "/usr/lib/python2.7/hmac.py", line 83, in update
>     self.inner.update(msg)
> TypeError: must be string or buffer, not bool

**Comment by untergeek** [comment]
Hmmm.  If you open a python console, would you please try:

```
from requests_aws4auth import AWS4Auth
AWS4Auth(kwargs['aws_key'], kwargs['aws_secret_key'],kwargs['region'], 'es')
```

But substitute _your_ values where the kwargs go.  Please respond with sanitized output (I don't want you to put your sensitive keys here).  I'm curious what the output is.

**Comment by untergeek** [comment]
Looking at the `requests_aws4auth` PyPI page, it may be that the requests module needs to be imported:

```
import requests
```
_above_ the `from requests_aws4auth import AWS4Auth` section

**Comment by kuttor** [comment]
Ah, before executing the console will quickly import requests.

**Comment by kuttor** [comment]
```
In [2]: AWS4Auth('key', 'secret', 'us-west-2', 'es')
Out[2]: <requests_aws4auth.aws4auth.AWS4Auth at 0x7f5baac049d0>
```

**Comment by untergeek** [comment]
Now, in `utils.py`, add `import requests` above `from requests_aws4auth import AWS4Auth` and see if it's any different.

**Comment by kuttor** [comment]
Dang, negative. 

> from datetime import timedelta, datetime, date
> import requests
> from requests_aws4auth import AWS4Auth
> import elasticsearch
> import copy
> import time
> import re
> import sys
> import logging
> import yaml

```
...
...
  File "/usr/local/lib/python2.7/dist-packages/requests_aws4auth/aws4signingkey.py", line 116, in generate_key
    region_key = cls.sign_sha256(date_key, region)
  File "/usr/local/lib/python2.7/dist-packages/requests_aws4auth/aws4signingkey.py", line 136, in sign_sha256
    return hmac.new(key, msg, hashlib.sha256).digest()
  File "/usr/lib/python2.7/hmac.py", line 133, in new
    return HMAC(key, msg, digestmod)
  File "/usr/lib/python2.7/hmac.py", line 75, in __init__
    self.update(msg)
  File "/usr/lib/python2.7/hmac.py", line 83, in update
    self.inner.update(msg)
```

**Comment by kuttor** [comment]
Yea, I been working on getting this implement for almost two days now. Have a fairly large ELK stack environment and would rather implement curator than some data node auto-scaling and/or cron data exporting to S3 solution.

**Comment by untergeek** [comment]
This implies that the fault is upstream. Either I'm lacking some data that needs to be sent, or something is off in the requests area. I'll do more digging as I get time. 

Can you use Curator on the inside of your AWS cluster, rather than from remote?

**Comment by kuttor** [comment]
Ah, I see -- Yeah, absolutely.

**Comment by kuttor** [comment]
Within the AWS enviro (Even directly in the Master cluster) would that affect the configuration -- figured it would be the same...

**Comment by untergeek** [comment]
That's correct. The AWS option is for connecting from outside of AWS. An internal instance of Curator will work by connecting directly to ES.

**Comment by untergeek** [comment]
But you don't need an instance of Curator per node.   If you do that, be sure to set master_only to True, so it only runs on the elected master node. Otherwise it only needs a single client connection to manage the whole cluster

**Comment by kuttor** [comment]
Rock on. So, let's say I have a standard three ES Master / three ES Data cluster in the same VPC...  would Curator need to live locally within one of the master nodes or just be within that VPC?

**Comment by untergeek** [comment]
It only needs access to the client port, so within the VPC is fine

**Comment by kuttor** [comment]
Thanks much.

**Comment by basex** [comment]
I'm having exactly the same problem as above with the same traceback. I'm unable to sign the request. Is there a solution for this?

curator, version 4.0.4

**Comment by untergeek** [comment]
No, it seems there is something fundamentally missing or wrong with this _experimental_ feature.  I will be trying to get it to work still, but I don't yet have the cycles to fully troubleshoot it.

**Comment by untergeek** [comment]
Fixed by #722, presumably.

**Comment by shavo007** [comment]
@untergeek is there a new release to verify this?

**Comment by shavo007** [comment]
I can confirm that this works with version 4.0.5. Verified against aws managed es service 2.3
