### ISSUE TITLE
curator fresh install error

### ISSUE THREAD

**Issue by email2liyang** [elastic/curator#77]
I install curator by sudo pip install elasticsearch-curator in aws ec2 instance, after installation complete, I call command "curator --help", and got error below:

anything wrong with my setting?

Traceback (most recent call last):
  File "/usr/bin/curator", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 2655, in <module>
    working_set.require(**requires**)
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 648, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 546, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: elasticsearch>=1.0.0,<2.0.0

**Comment by alex-leonhardt** [comment]
had the same issue on latest version, but was running python from centos *6.4* -- I needed `python-pip` installed in order to make the `/usr/bin/curator` working (no other changes, all packages were installed via yum, not pip) -- centos 6.5 works without having `python-pip` installed ... strange days.
