### ISSUE TITLE
"SSLError([Errno 20] Not a directory" when connecting to SSL-enabled ES cluster

### ISSUE THREAD

**Issue by FlorinAndrei** [elastic/curator#810]
Ubuntu 16.04. Curator installed from the APT repo per instructions here:

https://www.elastic.co/guide/en/elasticsearch/client/curator/current/apt-repository.html

```
# curator --version
curator, version 4.2.1
```

Trying to connect to an ES cluster in cloud.elastic.co

```
# curator_cli --host XXXXXXXXXXXXXX.aws.found.io --port XXXX --use_ssl --http_auth 'XXXXXXX:XXXXXXX' show_indices --filter_list '{"filtertype":"none"}'
Traceback (most recent call last):
  File "/home/vagrant/.local/lib/python3.5/site-packages/urllib3/util/ssl_.py", line 308, in ssl_wrap_socket
NotADirectoryError: [Errno 20] Not a directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vagrant/.local/lib/python3.5/site-packages/elasticsearch/connection/http_urllib3.py", line 94, in perform_request
  File "/home/vagrant/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 594, in urlopen
  File "/home/vagrant/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 350, in _make_request
  File "/home/vagrant/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 835, in _validate_conn
  File "/home/vagrant/.local/lib/python3.5/site-packages/urllib3/connection.py", line 323, in connect
  File "/home/vagrant/.local/lib/python3.5/site-packages/urllib3/util/ssl_.py", line 310, in ssl_wrap_socket
urllib3.exceptions.SSLError: [Errno 20] Not a directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/curator/curator-4.2.1/curator/utils.py", line 580, in get_client
  File "/tmp/curator/curator-4.2.1/curator/utils.py", line 424, in check_version
  File "/tmp/curator/curator-4.2.1/curator/utils.py", line 397, in get_version
  File "/home/vagrant/.local/lib/python3.5/site-packages/elasticsearch/client/utils.py", line 69, in _wrapped
  File "/home/vagrant/.local/lib/python3.5/site-packages/elasticsearch/client/__init__.py", line 220, in info
  File "/home/vagrant/.local/lib/python3.5/site-packages/elasticsearch/transport.py", line 327, in perform_request
  File "/home/vagrant/.local/lib/python3.5/site-packages/elasticsearch/connection/http_urllib3.py", line 99, in perform_request
elasticsearch.exceptions.SSLError: ConnectionError([Errno 20] Not a directory) caused by: SSLError([Errno 20] Not a directory)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vagrant/.local/lib/python3.5/site-packages/cx_Freeze/initscripts/Console.py", line 21, in <module>
  File "run_singleton.py", line 8, in <module>
  File "/home/vagrant/.local/lib/python3.5/site-packages/click/core.py", line 716, in __call__
  File "/home/vagrant/.local/lib/python3.5/site-packages/click/core.py", line 696, in main
  File "/home/vagrant/.local/lib/python3.5/site-packages/click/core.py", line 1060, in invoke
  File "/home/vagrant/.local/lib/python3.5/site-packages/click/core.py", line 889, in invoke
  File "/home/vagrant/.local/lib/python3.5/site-packages/click/core.py", line 534, in invoke
  File "/home/vagrant/.local/lib/python3.5/site-packages/click/decorators.py", line 17, in new_func
  File "/tmp/curator/curator-4.2.1/curator/singletons.py", line 468, in show_indices_singleton
  File "/tmp/curator/curator-4.2.1/curator/utils.py", line 587, in get_client
elasticsearch.exceptions.ElasticsearchException: Unable to create client connection to Elasticsearch.  Error: ConnectionError([Errno 20] Not a directory) caused by: SSLError([Errno 20] Not a directory)
```

`/home/vagrant` does not even exist on this instance, no idea why it shows up in the trace.

**Comment by untergeek** [comment]
It shows `/home/vagrant` because it was compiled in a vagrant instance.  It's running everything from a virtual directory.  

It appears to be looking for something in a directory, and not finding it, which I don't think is necessarily related to the virtual paths, as I have tested this binary against Shield/Security enabled instances manually (though not against Elastic Cloud).  When I've tested it, it's been with self-signed certificates and I've specified `--certificate`, `--client-cert`, and `--client-key`.  You have specified none of these, so I wonder if that's related, that it's not able to find the `certifi`-provided certificates in the virtual filesystem, which should be bundled.

Could you please run this with `--loglevel DEBUG` and attach the output?  Hopefully it will have more information.

**Comment by untergeek** [comment]
Confirmed (you don't have to send logs).  Troubleshooting, though I'm traveling today.  It may be next week before I get to it.

**Comment by untergeek** [comment]
It's not able to find the `cacert.pem` that is bundled with Certifi in the virtual path.  While I find a way around this, please use the certifi-cacert.pem [this zip file](https://github.com/elastic/curator/files/599214/certifi-cacert.zip) with `--certificate /path/to/certifi-cacert.pem`.
