### ISSUE TITLE
RuntimeError, click/_unicodefun.py related to locale (workaround: set LC_ALL)

### ISSUE THREAD

**Issue by jamshid** [elastic/curator#814]
Sorry I don't have full details but this stack trace was found in logs related to elasticsearch-curator. I think this is due to a recent (4.2.1?) change? It's weird because this is in a centos7 container with only python 2.7 (no python 3.x) installed.

Anyway, setting `export LC_ALL=en_US.UTF-8` seems to fix it. 

```
Traceback (most recent call last):
  File "/home/vagrant/.local/lib/python3.5/site-packages/cx_Freeze/initscripts/Console.py", line 21, in <module>
  File "run_curator.py", line 8, in <module>
  File "/home/vagrant/.local/lib/python3.5/site-packages/click/core.py", line 716, in __call__
  File "/home/vagrant/.local/lib/python3.5/site-packages/click/core.py", line 675, in main
  File "/home/vagrant/.local/lib/python3.5/site-packages/click/_unicodefun.py", line 119, in _verify_python3_env
RuntimeError: Click will abort further execution because Python 3 was configured to use ASCII as encoding for the environment.  Either run this under Python 2 or consult http://click.pocoo.org/python3/ for mitigation steps.

This system lists a couple of UTF-8 supporting locales that
you can pick from.  The following suitable locales where
discovered: aa_DJ.utf8, aa_ER.utf8, aa_ET.utf8, af_ZA.utf8,
```

**Comment by untergeek** [comment]
Curator 4.2.1 is compiled and comes with an embedded version of Python 3.5.2 to remove dependencies and prevent SSL errors that come from using old versions of Python. 

I will document this for the upcoming release.

**Comment by untergeek** [comment]
Thanks for reporting the fix.
