### ISSUE TITLE
ImportError: No module named certifi after pip install --upgrade elasticsearch-curator (old version: 4.1.2, new version: 4.2.3)

### ISSUE THREAD

**Issue by rafaelfc-olx** [elastic/curator#821]
```
~# pip install --upgrade elasticsearch-curator
Downloading/unpacking elasticsearch-curator from https://pypi.python.org/packages/29/87/af185601e127a79def222a10b26700d953e78968f971123e5f4208ca3b48/elasticsearch-curator-4.2.3.tar.gz#md5=ecf80951755958c06f62c0124572d412
  Downloading elasticsearch-curator-4.2.3.tar.gz (133kB): 133kB downloaded
  Running setup.py (path:/tmp/pip_build_root/elasticsearch-curator/setup.py) egg_info for package elasticsearch-curator
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip_build_root/elasticsearch-curator/setup.py", line 5, in <module>
        import certifi
    ImportError: No module named certifi
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip_build_root/elasticsearch-curator/setup.py", line 5, in <module>

    import certifi

ImportError: No module named certifi

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_root/elasticsearch-curator
Storing debug log for failure in /root/.pip/pip.log
```

if you install certifi and then try to upgrade elasticsearch-curator, it works

```
~# pip install certifi
Downloading/unpacking certifi
  Downloading certifi-2016.9.26-py2.py3-none-any.whl (377kB): 377kB downloaded
Installing collected packages: certifi
Successfully installed certifi
Cleaning up...

~# pip install --upgrade elasticsearch-curator
Downloading/unpacking elasticsearch-curator from https://pypi.python.org/packages/29/87/af185601e127a79def222a10b26700d953e78968f971123e5f4208ca3b48/elasticsearch-curator-4.2.3.tar.gz#md5=ecf80951755958c06f62c0124572d412
  Downloading elasticsearch-curator-4.2.3.tar.gz (133kB): 133kB downloaded
  Running setup.py (path:/tmp/pip_build_root/elasticsearch-curator/setup.py) egg_info for package elasticsearch-curator

    warning: no previously-included files matching '__pycache__' found under directory '*'
    warning: no previously-included files matching '*.py[co]' found under directory '*'
    warning: no previously-included files matching '*.pyc' found under directory 'curator'
    warning: no previously-included files matching '*.pyo' found under directory 'curator'
    warning: no previously-included files matching '*.pyc' found under directory 'docs'
    warning: no previously-included files matching '*.pyo' found under directory 'docs'
    warning: no previously-included files matching '*.pyc' found under directory 'test'
    warning: no previously-included files matching '*.pyo' found under directory 'test'
    no previously-included directories found matching 'docs/_build'
    no previously-included directories found matching 'docs/asciidoc/html_docs'
Requirement already up-to-date: elasticsearch<3.0.0,>=2.4.0 in /usr/local/lib/python2.7/dist-packages (from elasticsearch-curator)
Requirement already up-to-date: click>=6.0 in /usr/local/lib/python2.7/dist-packages (from elasticsearch-curator)
Requirement already up-to-date: pyyaml>=3.10 in /usr/local/lib/python2.7/dist-packages (from elasticsearch-curator)
Requirement already up-to-date: voluptuous>=0.9.3 in /usr/local/lib/python2.7/dist-packages (from elasticsearch-curator)
Requirement already up-to-date: certifi>=2016.09.26 in /usr/local/lib/python2.7/dist-packages (from elasticsearch-curator)
Requirement already up-to-date: setuptools>=0.6b1 in /usr/local/lib/python2.7/dist-packages (from voluptuous>=0.9.3->elasticsearch-curator)
Installing collected packages: elasticsearch-curator
  Found existing installation: elasticsearch-curator 4.2.1
    Uninstalling elasticsearch-curator:
      Successfully uninstalled elasticsearch-curator
  Running setup.py install for elasticsearch-curator

    warning: no previously-included files matching '__pycache__' found under directory '*'
    warning: no previously-included files matching '*.py[co]' found under directory '*'
    warning: no previously-included files matching '*.pyc' found under directory 'curator'
    warning: no previously-included files matching '*.pyo' found under directory 'curator'
    warning: no previously-included files matching '*.pyc' found under directory 'docs'
    warning: no previously-included files matching '*.pyo' found under directory 'docs'
    warning: no previously-included files matching '*.pyc' found under directory 'test'
    warning: no previously-included files matching '*.pyo' found under directory 'test'
    no previously-included directories found matching 'docs/_build'
    no previously-included directories found matching 'docs/asciidoc/html_docs'
    Installing curator script to /usr/local/bin
    Installing curator_cli script to /usr/local/bin
    Installing es_repo_mgr script to /usr/local/bin
  Could not find .egg-info directory in install record for elasticsearch-curator from https://pypi.python.org/packages/29/87/af185601e127a79def222a10b26700d953e78968f971123e5f4208ca3b48/elasticsearch-curator-4.2.3.tar.gz#md5=ecf80951755958c06f62c0124572d412 in /usr/local/lib/python2.7/dist-packages
Successfully installed elasticsearch-curator
Cleaning up...
```

**Comment by untergeek** [comment]
This is because I wrongly assumed PyPI would pick up the dependency from requirements.txt first.  Fix coming to master soon (though subsequent installs via pip won't have the problem since they'll already have certifi installed).

**Comment by untergeek** [comment]
v4.2.3.post1 is in PyPI now

**Comment by rafaelfc-olx** [comment]
thanks for the fast reply!
