### ISSUE TITLE
curator_cli 4.2.4 fails with "curator.exceptions.NoIndices" if no index matches the pattern

### ISSUE THREAD

**Issue by breml** [elastic/curator#848]
I run curator_cli version 4.2.4 with command `delete_indices` against an Elasticsearch (2.4.1) cluster with some indices, but no index does match the filter. In this case curator fails with the following Traceback:

```
Traceback (most recent call last):
  File "/var/vcap/packages/curator/bin/curator_cli", line 9, in <module>
    load_entry_point('elasticsearch-curator==4.2.4', 'console_scripts', 'curator_cli')()
  File "/var/vcap/packages/curator/lib/python3.4/site-packages/curator/curator_cli.py", line 5, in main
    cli(obj={})
  File "/var/vcap/packages/curator/lib/python3.4/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/var/vcap/packages/curator/lib/python3.4/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/var/vcap/packages/curator/lib/python3.4/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/var/vcap/packages/curator/lib/python3.4/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/var/vcap/packages/curator/lib/python3.4/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/var/vcap/packages/curator/lib/python3.4/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/var/vcap/packages/curator/lib/python3.4/site-packages/curator/singletons.py", line 268, in delete_indices_singleton
    ilo.iterate_filters(clean_filters)
  File "/var/vcap/packages/curator/lib/python3.4/site-packages/curator/indexlist.py", line 846, in iterate_filters
    method(**f)
  File "/var/vcap/packages/curator/lib/python3.4/site-packages/curator/indexlist.py", line 380, in filter_by_regex
    self.empty_list_check()
  File "/var/vcap/packages/curator/lib/python3.4/site-packages/curator/indexlist.py", line 184, in empty_list_check
    raise NoIndices('index_list object is empty.')
curator.exceptions.NoIndices: index_list object is empty.
```

In my opinion this exception should be handled properly and it should be possible to run curator even there is nothing to do (maybe output something like: `nothing to do, no indices matched the filter`).
The same exception occurs if I use an other command like `open` or `close`.

Command I execute:

```
curator_cli --host 127.0.0.1 --port 9200 --http_auth admin:admin --use_ssl --ssl-no-validate open --filter_list '[{"filtertype":"age","source":"name","direction":"older","unit":"days","unit_count":5,"timestring": "%Y.%m.%d"},{"filtertype":"pattern","kind":"prefix","value":"logstash"}]'
```

**Comment by breml** [comment]
I hust found out about `--ignore_empty_list`. Unfortunately the traceback is still printed.

My command:

```
curator_cli --host 127.0.0.1 --port 9200 --http_auth admin:admin --use_ssl --ssl-no-validate delete_indices --ignore_empty_list --filter_list '[{"filtertype":"age","source":"name","direction":"older","unit":"days","unit_count":5,"timestring": "%Y.%m.%d"},{"filtertype":"pattern","kind":"prefix","value":"logstash"}]'
```

Output:
```
Traceback (most recent call last):
  File "/var/vcap/packages/curator/bin/curator_cli", line 9, in <module>
    load_entry_point('elasticsearch-curator==4.2.4', 'console_scripts', 'curator_cli')()
  File "/var/vcap/packages/curator/lib/python3.4/site-packages/curator/curator_cli.py", line 5, in main
    cli(obj={})
  File "/var/vcap/packages/curator/lib/python3.4/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/var/vcap/packages/curator/lib/python3.4/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/var/vcap/packages/curator/lib/python3.4/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/var/vcap/packages/curator/lib/python3.4/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/var/vcap/packages/curator/lib/python3.4/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/var/vcap/packages/curator/lib/python3.4/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/var/vcap/packages/curator/lib/python3.4/site-packages/curator/singletons.py", line 268, in delete_indices_singleton
    ilo.iterate_filters(clean_filters)
  File "/var/vcap/packages/curator/lib/python3.4/site-packages/curator/indexlist.py", line 846, in iterate_filters
    method(**f)
  File "/var/vcap/packages/curator/lib/python3.4/site-packages/curator/indexlist.py", line 380, in filter_by_regex
    self.empty_list_check()
  File "/var/vcap/packages/curator/lib/python3.4/site-packages/curator/indexlist.py", line 184, in empty_list_check
    raise NoIndices('index_list object is empty.')
curator.exceptions.NoIndices: index_list object is empty.
```

**Comment by breml** [comment]
If I use `curator` with action file, it works as expected and also the output is nice (without traceback even if an exception is raised).

`ignore_empty_list: False` and `continue_if_exception: False`:

```
2016-12-20 13:52:21,317 INFO      Preparing Action ID: 1, "delete_indices"
2016-12-20 13:52:21,328 INFO      Trying Action ID: 1, "delete_indices": No description given
2016-12-20 13:52:21,362 ERROR     Unable to complete action "delete_indices".  No actionable items in list: <class 'curator.exceptions.NoIndices'>
```

`ignore_empty_list: True` and `continue_if_exception: True`:

```
2016-12-20 13:51:23,894 INFO      Preparing Action ID: 1, "delete_indices"
2016-12-20 13:51:23,906 INFO      Trying Action ID: 1, "delete_indices": No description given
2016-12-20 13:51:23,941 INFO      Skipping action "delete_indices" due to empty list: <class 'curator.exceptions.NoIndices'>
2016-12-20 13:51:23,941 INFO      Action ID: 1, "delete_indices" completed.
2016-12-20 13:51:23,942 INFO      Job completed.
```

**Comment by untergeek** [comment]
I'm not sure what you're doing here, but I can't replicate your results:

```
$ curator_cli --version
curator_cli, version 4.2.4
```

Command without `--ignore_empty_list`:
```
$ curator_cli --loglevel INFO --logfile '' delete_indices --filter_list '{"filtertype":"pattern","kind":"prefix","value":"not_here_dude"}'
```
Output and exit code:
```
{"@timestamp": "2016-12-21T19:57:20.354Z", "function": "_check_empty_list", "linenum": 101, "loglevel": "ERROR", "message": "Singleton action failed due to empty index list", "name": "curator.singletons"}

$ echo $?
1
```

Command with `--ignore_empty_list`:
```
$ curator_cli --loglevel INFO --logfile '' delete_indices --ignore_empty_list --filter_list '{"filtertype":"pattern","kind":"prefix","value":"not_here_dude"}'
```
Output and exit code:
```
{"@timestamp": "2016-12-21T19:57:53.779Z", "function": "_check_empty_list", "linenum": 96, "loglevel": "INFO", "message": "Singleton action not performed: empty index list", "name": "curator.singletons"}

$ echo $?
0
```

Even when I try to run multiple filters:
```
$ curator_cli --loglevel INFO --logfile '' show_indices --ignore_empty_list --filter_list '[{"filtertype":"none"},{"filtertype":"pattern","kind":"prefix","value":"not_here_dude"}]'
{"@timestamp": "2016-12-21T20:03:27.054Z", "function": "_check_empty_list", "linenum": 96, "loglevel": "INFO", "message": "Singleton action not performed: empty index list", "name": "curator.singletons"}

$ curator_cli --loglevel INFO --logfile '' show_indices --ignore_empty_list --filter_list '[{"filtertype":"pattern","kind":"prefix","value":"logstash"},{"filtertype":"pattern","kind":"prefix","value":"not_here_dude"}]'
{"@timestamp": "2016-12-21T20:04:20.392Z", "function": "_check_empty_list", "linenum": 96, "loglevel": "INFO", "message": "Singleton action not performed: empty index list", "name": "curator.singletons"}
```

Or even with your filters, both before and after:
```
$ curator_cli --loglevel INFO --logfile '' delete_indices --ignore_empty_list --filter_list '[{"filtertype":"age","source":"name","direction":"older","unit":"days","unit_count":5,"timestring": "%Y.%m.%d"},{"filtertype":"pattern","kind":"prefix","value":"logstash"}]'
{"@timestamp": "2016-12-21T20:05:17.297Z", "function": "do_action", "linenum": 478, "loglevel": "INFO", "message": "Deleting selected indices: ['logstash-2016.12.15', 'logstash-2016.12.11', 'logstash-2016.09.30', 'logstash-2016.12.16', 'logstash-2016.11.21', 'logstash-2016.12.12', 'logstash-2016.12.08', 'logstash-2016.12.14', 'logstash-2016.12.09', 'logstash-2016.12.13', 'logstash-2016.12.10', 'logstash-2016.12.07']", "name": "curator.actions.delete_indices"}
{"@timestamp": "2016-12-21T20:05:17.298Z", "function": "__chunk_loop", "linenum": 453, "loglevel": "INFO", "message": "---deleting index logstash-2016.12.15", "name": "curator.actions.delete_indices"}
{"@timestamp": "2016-12-21T20:05:17.298Z", "function": "__chunk_loop", "linenum": 453, "loglevel": "INFO", "message": "---deleting index logstash-2016.12.11", "name": "curator.actions.delete_indices"}
{"@timestamp": "2016-12-21T20:05:17.298Z", "function": "__chunk_loop", "linenum": 453, "loglevel": "INFO", "message": "---deleting index logstash-2016.09.30", "name": "curator.actions.delete_indices"}
{"@timestamp": "2016-12-21T20:05:17.298Z", "function": "__chunk_loop", "linenum": 453, "loglevel": "INFO", "message": "---deleting index logstash-2016.12.16", "name": "curator.actions.delete_indices"}
{"@timestamp": "2016-12-21T20:05:17.298Z", "function": "__chunk_loop", "linenum": 453, "loglevel": "INFO", "message": "---deleting index logstash-2016.11.21", "name": "curator.actions.delete_indices"}
{"@timestamp": "2016-12-21T20:05:17.298Z", "function": "__chunk_loop", "linenum": 453, "loglevel": "INFO", "message": "---deleting index logstash-2016.12.12", "name": "curator.actions.delete_indices"}
{"@timestamp": "2016-12-21T20:05:17.298Z", "function": "__chunk_loop", "linenum": 453, "loglevel": "INFO", "message": "---deleting index logstash-2016.12.08", "name": "curator.actions.delete_indices"}
{"@timestamp": "2016-12-21T20:05:17.298Z", "function": "__chunk_loop", "linenum": 453, "loglevel": "INFO", "message": "---deleting index logstash-2016.12.14", "name": "curator.actions.delete_indices"}
{"@timestamp": "2016-12-21T20:05:17.298Z", "function": "__chunk_loop", "linenum": 453, "loglevel": "INFO", "message": "---deleting index logstash-2016.12.09", "name": "curator.actions.delete_indices"}
{"@timestamp": "2016-12-21T20:05:17.298Z", "function": "__chunk_loop", "linenum": 453, "loglevel": "INFO", "message": "---deleting index logstash-2016.12.13", "name": "curator.actions.delete_indices"}
{"@timestamp": "2016-12-21T20:05:17.299Z", "function": "__chunk_loop", "linenum": 453, "loglevel": "INFO", "message": "---deleting index logstash-2016.12.10", "name": "curator.actions.delete_indices"}
{"@timestamp": "2016-12-21T20:05:17.299Z", "function": "__chunk_loop", "linenum": 453, "loglevel": "INFO", "message": "---deleting index logstash-2016.12.07", "name": "curator.actions.delete_indices"}
{"@timestamp": "2016-12-21T20:05:20.112Z", "function": "_actionator", "linenum": 82, "loglevel": "INFO", "message": "Singleton \"delete_indices\" action completed.", "name": "curator.singletons"}
```
I figured I might be able to get the error if the list is empty afterward, but I can't:
```
$ curator_cli --loglevel INFO --logfile '' delete_indices --ignore_empty_list --filter_list '[{"filtertype":"age","source":"name","direction":"older","unit":"days","unit_count":5,"timestring": "%Y.%m.%d"},{"filtertype":"pattern","kind":"prefix","value":"logstash"}]'
{"@timestamp": "2016-12-21T20:06:03.646Z", "function": "_check_empty_list", "linenum": 96, "loglevel": "INFO", "message": "Singleton action not performed: empty index list", "name": "curator.singletons"}
```

I'm not sure what's going on in your environment, but I cannot replicate it on my end with 4.2.4.

I do see you're using Python 3.4.  Is there a reason you're not using the pre-compiled binaries I provide now?

**Comment by breml** [comment]
@untergeek thanks for your reply. We provide services based on [Cloud Foundry](https://www.cloudfoundry.org/) and therefore use [BOSH](http://bosh.io/) for our deployments. BOSH has the concept of stemcells, which are very rudimentary Linux base images, on which every software is deployed as so called BOSH releases. These releases must bring all their dependecies with them and all the components are usualy compiled from source code (it has some analogies with Gentoo).
This is also the reason, why I am not able to use the binary packages (DEB, RPM) you mentioned.

With these preconditions I started to put together all the dependencies, as noted on [Installation from source](https://www.elastic.co/guide/en/elasticsearch/client/curator/current/python-source.html). While double-checking the dependencies I found a small bug in the documentation (#850). Because of this I was using version 6.2 of click. So I fixed this, but the problem persists.

I use the following exact versions:

* Python 3.4.3 from https://www.python.org/ftp/python/3.4.3/Python-3.4.3.tgz
* certifi 2016.09.26 from https://github.com/certifi/python-certifi/archive/2016.09.26.tar.gz
* click 6.3 from https://pypi.python.org/packages/source/c/click/click-6.3.tar.gz
* elasticsearch-curator 4.2.4 from https://github.com/elastic/curator/archive/v4.2.4.tar.gz
* elasticsearch 2.4.0 from https://github.com/elastic/elasticsearch-py/archive/2.4.0.tar.gz
* PyYAML 3.11 from http://pyyaml.org/download/pyyaml/PyYAML-3.11.tar.gz
* urllib3 1.12 from https://pypi.python.org/packages/source/u/urllib3/urllib3-1.12.tar.gz
* voluptuous 0.9.3 from https://github.com/alecthomas/voluptuous/archive/0.9.3.tar.gz

Also double checked:

```
# ls /var/vcap/packages/curator/lib/python3.4/site-packages/ -1
certifi
certifi-2016.9.26-py3.4.egg-info
click
click-6.3-py3.4.egg-info
curator
elasticsearch
elasticsearch-2.4.0-py3.4.egg-info
elasticsearch_curator-4.2.4-py3.4.egg-info
PyYAML-3.11-py3.4.egg-info
urllib3
urllib3-1.12-py3.4.egg-info
voluptuous
voluptuous-0.9.3-py3.4.egg-info
yaml
_yaml.cpython-34m.so
```

So I started with the examples you provided, with the following results:


```
curator_cli --loglevel INFO --host 127.0.0.1 --port 9200 --http_auth admin:admin --use_ssl --ssl-no-validate delete_indices --filter_list '{"filtertype":"pattern","kind":"prefix","value":"not_here_dude"}'
```

Output:

```
2016-12-22 11:13:55,886 ERROR     Singleton action failed due to empty index list
```

Put query into an array:

```
curator_cli --loglevel INFO --host 127.0.0.1 --port 9200 --http_auth admin:admin --use_ssl --ssl-no-validate delete_indices --filter_list '[{"filtertype":"pattern","kind":"prefix","value":"not_here_dude"}]'
```

Output:

```
2016-12-22 11:14:54,564 ERROR     Singleton action failed due to empty index list
```

Added second part of query:

```
curator_cli --loglevel INFO --host 127.0.0.1 --port 9200 --http_auth admin:admin --use_ssl --ssl-no-validate delete_indices --filter_list '[{"filtertype":"pattern","kind":"prefix","value":"not_here_dude"},{"filtertype":"age","source":"creation_date","direction":"older","unit":"days","unit_count":5}]'
```

Output:

```
2016-12-22 11:17:18,050 ERROR     Singleton action failed due to empty index list
```

Change order of filters:

```
curator_cli --loglevel INFO --host 127.0.0.1 --port 9200 --http_auth admin:admin --use_ssl --ssl-no-validate delete_indices --filter_list '[{"filtertype":"age","source":"creation_date","direction":"older","unit":"days","unit_count":5},{"filtertype":"pattern","kind":"prefix","value":"not_here_dude"}]'
```

Output:

```
Traceback (most recent call last):
  File "/var/vcap/packages/curator/bin/curator_cli", line 9, in <module>
    load_entry_point('elasticsearch-curator==4.2.4', 'console_scripts', 'curator_cli')()
  File "/var/vcap/packages/curator/lib/python3.4/site-packages/curator/curator_cli.py", line 5, in main
    cli(obj={})
  File "/var/vcap/packages/curator/lib/python3.4/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/var/vcap/packages/curator/lib/python3.4/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/var/vcap/packages/curator/lib/python3.4/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/var/vcap/packages/curator/lib/python3.4/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/var/vcap/packages/curator/lib/python3.4/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/var/vcap/packages/curator/lib/python3.4/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/var/vcap/packages/curator/lib/python3.4/site-packages/curator/singletons.py", line 268, in delete_indices_singleton
    ilo.iterate_filters(clean_filters)
  File "/var/vcap/packages/curator/lib/python3.4/site-packages/curator/indexlist.py", line 846, in iterate_filters
    method(**f)
  File "/var/vcap/packages/curator/lib/python3.4/site-packages/curator/indexlist.py", line 380, in filter_by_regex
    self.empty_list_check()
  File "/var/vcap/packages/curator/lib/python3.4/site-packages/curator/indexlist.py", line 184, in empty_list_check
    raise NoIndices('index_list object is empty.')
curator.exceptions.NoIndices: index_list object is empty.
```

**Here we go!** - looks like it is a problem with the ordering of the filters.

The error persists, if I change the `age` filter to `source` = `name`:

```
curator_cli --loglevel INFO --host 127.0.0.1 --port 9200 --http_auth admin:admin --use_ssl --ssl-no-validate delete_indices --filter_list '[{"filtertype":"age","source":"name","direction":"older","unit":"days","unit_count":5,"timestring": "%Y.%m.%d"},{"filtertype":"pattern","kind":"prefix","value":"not_here_dude"}]'
```

Output:

```
Traceback (most recent call last):
  File "/var/vcap/packages/curator/bin/curator_cli", line 9, in <module>
    load_entry_point('elasticsearch-curator==4.2.4', 'console_scripts', 'curator_cli')()
  File "/var/vcap/packages/curator/lib/python3.4/site-packages/curator/curator_cli.py", line 5, in main
    cli(obj={})
  File "/var/vcap/packages/curator/lib/python3.4/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/var/vcap/packages/curator/lib/python3.4/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/var/vcap/packages/curator/lib/python3.4/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/var/vcap/packages/curator/lib/python3.4/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/var/vcap/packages/curator/lib/python3.4/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/var/vcap/packages/curator/lib/python3.4/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/var/vcap/packages/curator/lib/python3.4/site-packages/curator/singletons.py", line 268, in delete_indices_singleton
    ilo.iterate_filters(clean_filters)
  File "/var/vcap/packages/curator/lib/python3.4/site-packages/curator/indexlist.py", line 846, in iterate_filters
    method(**f)
  File "/var/vcap/packages/curator/lib/python3.4/site-packages/curator/indexlist.py", line 380, in filter_by_regex
    self.empty_list_check()
  File "/var/vcap/packages/curator/lib/python3.4/site-packages/curator/indexlist.py", line 184, in empty_list_check
    raise NoIndices('index_list object is empty.')
curator.exceptions.NoIndices: index_list object is empty.
```

It also happens, if I add an `none` in front of the `age` filter:

```
curator_cli --loglevel INFO --host 127.0.0.1 --port 9200 --http_auth admin:admin --use_ssl --ssl-no-validate delete_indices --filter_list '[{"filtertype":"none"},{"filtertype":"age","source":"creation_date","direction":"older","unit":"days","unit_count":5},{"filtertype":"pattern","kind":"prefix","value":"not_here_dude"}]'
```

Output:

```
Traceback (most recent call last):
  File "/var/vcap/packages/curator/bin/curator_cli", line 9, in <module>
    load_entry_point('elasticsearch-curator==4.2.4', 'console_scripts', 'curator_cli')()
  File "/var/vcap/packages/curator/lib/python3.4/site-packages/curator/curator_cli.py", line 5, in main
    cli(obj={})
  File "/var/vcap/packages/curator/lib/python3.4/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/var/vcap/packages/curator/lib/python3.4/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/var/vcap/packages/curator/lib/python3.4/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/var/vcap/packages/curator/lib/python3.4/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/var/vcap/packages/curator/lib/python3.4/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/var/vcap/packages/curator/lib/python3.4/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/var/vcap/packages/curator/lib/python3.4/site-packages/curator/singletons.py", line 268, in delete_indices_singleton
    ilo.iterate_filters(clean_filters)
  File "/var/vcap/packages/curator/lib/python3.4/site-packages/curator/indexlist.py", line 846, in iterate_filters
    method(**f)
  File "/var/vcap/packages/curator/lib/python3.4/site-packages/curator/indexlist.py", line 380, in filter_by_regex
    self.empty_list_check()
  File "/var/vcap/packages/curator/lib/python3.4/site-packages/curator/indexlist.py", line 184, in empty_list_check
    raise NoIndices('index_list object is empty.')
curator.exceptions.NoIndices: index_list object is empty.
```

But if I remove the `age` filter again, it works again:

```
curator_cli --loglevel INFO --host 127.0.0.1 --port 9200 --http_auth admin:admin --use_ssl --ssl-no-validate delete_indices --filter_list '[{"filtertype":"none"},{"filtertype":"pattern","kind":"prefix","value":"not_here_dude"}]'
```

Output:

```
2016-12-22 11:59:37,742 ERROR     Singleton action failed due to empty index list
```

I also changed the `none` filter to an `opened` filter with the same results (works without the `age` filter, does not work with the `age` filter).

I hope, this information does help you to localize the problem.

**Comment by untergeek** [comment]
> **Here we go!** - looks like it is a problem with the ordering of the filters.

Well, of course.  You created an empty list condition with the first filter.  

It's not about the ordering as much as it's about the fact that Curator's trying to filter an already empty list.  The ordering only serves to make that happen sooner.

I found where `--ignore_empty_list` was not being caught and have a fix coming.

**Comment by breml** [comment]
@untergeek thanks for the fix.
