### ISSUE TITLE
HTTPS connection made on HTTP endpoint

### ISSUE THREAD

**Issue by mvisonneau** [elastic/curator#868]
Launching this command : 
```
/usr/local/bin/curator --debug --logfile /var/log/curator.log --loglevel DEBUG --logformat default --use_ssl --certificate /etc/mycert --ssl-no-validate --http_auth admin:password --host localhost --port 9200 close indices --prefix 'logstash-' --time-unit days --older-than 14 --timestring '\%Y.\%m.\%d'
```

Let me end up with the following :

```
2017-01-19 17:17:49,893 DEBUG          curator.cli.utils        filter_callback:198  Added filter: {'pattern': '(?P<date>\\\\\\d{4}\\.\\\\\\d{2}\\.\\\\\\d{2})', 'value': 14, 'groupname': 'date', 'time_unit': 'days', 'timestring': u'\\%Y.\\%m.\\%d', 'method': 'older_than'}
2017-01-19 17:17:49,893 DEBUG          curator.cli.utils        filter_callback:199  New list of filters: [{'pattern': '^logstash-.*$'}, {'pattern': '(?P<date>\\\\\\d{4}\\.\\\\\\d{2}\\.\\\\\\d{2})', 'value': 14, 'groupname': 'date', 'time_unit': 'days', 'timestring': u'\\%Y.\\%m.\\%d', 'method': 'older_than'}]
2017-01-19 17:17:49,893 INFO      curator.cli.index_selection                indices:62   Job starting: close indices
2017-01-19 17:17:49,893 DEBUG     curator.cli.index_selection                indices:65   Params: {'url_prefix': u'', 'http_auth': u'admin:password', 'dry_run': False, 'certificate': u'/etc/mycert', 'loglevel': u'DEBUG', 'host': u'localhost', 'client_cert': None, 'logformat': u'default', 'quiet': False, 'timeout': 30, 'debug': True, 'use_ssl': True, 'logfile': u'/var/log/curator.log', 'master_only': False, 'port': 9200, 'ssl_no_validate': True, 'client_key': None}
2017-01-19 17:17:49,893 DEBUG          curator.cli.utils             get_client:114  kwargs = {'url_prefix': u'', 'http_auth': u'admin:password', 'dry_run': False, 'certificate': u'/etc/mycert', 'loglevel': u'DEBUG', 'logformat': u'default', 'quiet': False, 'port': 9200, 'host': u'localhost', 'timeout': 30, 'debug': True, 'use_ssl': True, 'logfile': u'/var/log/curator.log', 'master_only': False, 'client_cert': None, 'ssl_no_validate': True, 'client_key': None}
2017-01-19 17:17:49,893 DEBUG         urllib3.util.retry               from_int:156  Converted retries value: False -> Retry(total=False, connect=None, read=None, redirect=0)
2017-01-19 17:17:49,893 INFO      urllib3.connectionpool              _new_conn:761  Starting new HTTPS connection (1): localhost
2017-01-19 17:17:49,903 WARNING            elasticsearch       log_request_fail:82   GET http://localhost:9200/ [status:N/A request:0.009s]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/connection/http_urllib3.py", line 94, in perform_request
    response = self.pool.urlopen(method, url, body, retries=False, headers=self.headers, **kw)
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 560, in urlopen
    body=body, headers=headers)
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 346, in _make_request
    self._validate_conn(conn)
```

Am I the only one having this issue ? I don't understand why the request is being made on `http://localhost:9200/` it should be `https://localhost:9200/`

I'm using version `3.5.1`

**Comment by untergeek** [comment]
If you note the line above, it's actually accurate:

```
Starting new HTTPS connection (1): localhost
```
The python Elasticsearch module is logging in a way that is less than 100% informative is why it says "http" instead of "https", but it _is_ connecting via HTTPS (or at least attempting to).

I see that you have `--certificate /etc/mycert`.  What exactly is in that file?  Is that a directory?  Curator requires a full path to an actual certificate (usually PEM formatted).  The `--certificate` flag is for a certificate like the ones that ship with a browser, so that Curator can verify that the SSL keys on the server side match what is expected.  If you've made a self-signed certificate, you'd likely use the CA certificate (not key) here.

As a side note, are you using an older version of Elasticsearch?  Why are you still using 3.5.1?

**Comment by mvisonneau** [comment]
Yes that is a pem formated cert that I was referring to with `/etc/mycert`

I wanted to use a puppet module that only supports 3.x but I've been able to make it run successfully using `4.1.2`. I guess I'm going to write a new module for 4.x

**Comment by untergeek** [comment]
Don't use 4.1.2. The most recent version is 4.2.5

**Comment by untergeek** [comment]
And you can use singleton actions again, like in 3.x

**Comment by mvisonneau** [comment]
Yes I've updated my repository accordingly to use 4.2.5. Working fine now. Also made a puppet module if worth of interest to some people : https://github.com/mvisonneau/puppet-curator
